module Databases (homophones, allWords, f, wordlist, synonyms, checkSyn, manualSynonyms,
                  sortedWordlist, thesaurus, keys, maleNames, femaleNames, isInWordlist,
                  isPrefix, allPrefixes, makeSynonymTable,
                  hasAbbreviation, abbreviations,
                  thesaurusSynonyms, thesaurusLookup) where

import Data.List
import Data.Maybe
import Debug.Trace
import Data.Char as Ch
import Data.List
import qualified Data.Set as Set
import qualified Data.Text as Text (lines, toLower, unpack)
import qualified Data.Text.IO as Text (readFile)
import qualified Data.Map as Map
import Data.Array.IArray
import Data.Binary
import qualified Data.ByteString.Lazy as BS (readFile)
import qualified Data.HashSet as HashSet (fromList, member)

import System.IO.Unsafe

import Types
import Utilities
import ReverseDictionary

------ SYNONYMS ------

singular ["spies"]
  = ["spy"]

isSynonym w w'
  = elem w (synonyms w')

-- Note: string like "a son" will eventually be treated as the concatenation of
-- "a" and "son" leading to "ason", but removing whitespace provides a shortcut
-- to the same thing.

-- NEED TO MAKE SYNONYMS LOWER CASE...

checkSyn s s'
  = elem s $ synonyms s'

synonyms :: String -> [String]
synonyms s
  = directSynonyms s ++
    lookUp s indirectSynonyms

-- Note: needs to include the string itself, otherwise makeSynonymTable blows
-- up (head of empty list...?)
-- Note: homophones have their own constructor
directSynonyms ('a' : ' ' : s)
  = directSynonyms s
directSynonyms s
  = s' : s'' :
    abbreviations s ++
    lookUp s manualSynonyms ++
    lookUp s nameSynonyms ++
    thesaurusSynonyms s
  where
    s' = cleanUp s
    s'' = filter (not . isSpace) s

thesaurusSynonyms s
    = map (map toLower) (filter (not . null) (thesaurusLookup s))

hasAbbreviation s
  = Map.member s abbreviationsTable

abbreviations s
  = maybe [] id (Map.lookup s abbreviationsTable)

thesaurusLookup w
  = maybe [] (\s -> map (\n -> keys ! n) s) (Map.lookup w thesaurus)

-- Synonym table - used to speed up length functions.
-- Caches synonyms sorted by length and then alphabetically.
makeSynonymTable :: String -> [ClueText] -> SynonymTable
makeSynonymTable clueText extraText
  = [(w, (makeSynArray sortedSyns mn mx)) |
       let ws = words s,
       w <- ws : substrings ws ++ extraText,  -- misnomer - should be sublists!
       let syns = synonyms (unwords w),
       let ns = map length syns,
       let sortedSyns = sort (zip ns syns),
       let (ns', syns') = unzip sortedSyns,
       let (mn, mx) = (head ns', last ns')]
  where
    s = cleanUp clueText

makeSynArray :: [(Int, String)] -> Int -> Int -> Array Int [String]
makeSynArray syns mn mx
  = listArray (mn, mx) [sort [ws | (k, ws) <- syns, k == n] | n <- [mn..mx]]


------------------------------------ MANUAL SYNONYMS -----------------------------

manualSynonyms
  = synList ++ concatMap (\(w, ws) -> map (\w' -> (w', [w])) ws) synList

synList
  = [("left", ["l"]), -- required for optimisation hack
     ("address",["orate"]),
     ("agent",["m","q"]),
     ("anaesthetic", ["number"]),
     ("archbishop", ["cantuar","laud","ebor"]),
     ("ballet",["swanlake"]),
     ("bark", ["woof"]),
     ("battle scene",["alamo"]),
     ("beer", ["draught"]),
     ("bible", ["av"]),
     ("blockbuster", ["sculptor"]),
     ("bloomer", ["flower"]),
     ("blows up", ["expands"]),
     ("bowler", ["drake"]),
     ("bribe",["bung"]),
     ("brought in",["earned"]),
     ("by",["times"]),
     ("cakesville", ["eccles"]),
     ("captain", ["old man"]),
     ("censor", ["cato"]),
     ("changing pitch", ["vibrato"]),
     ("chemical", ["nitre"]),
     ("chess piece", ["pawn"]),
     ("chess piece", ["pawn"]),
     ("chewed", ["bit"]),
     ("classical musician", ["orpheus"]),
     ("college", ["eton","poly"]),
     ("conspirator", ["cade"]),
     ("corset",["basque"]),
     ("counter", ["geiger"]),
     ("county", ["down","som","avon"]),
     ("cow", ["lower"]),
     ("cowering", ["afraid"]),
     ("conservative", ["blue"]),
     ("county", ["down","avon"]),
     ("craft", ["art"]),
     ("cry of pain", ["ow", "ouch"]),
     ("daily", ["times","char"]),
     ("dark blue", ["oxonian"]),
     ("day", ["mon", "monday", "tue", "tuesday", "wed", "wednesday",
              "thu", "thursday", "fri", "friday", "sat", "saturday",
              "sun", "sunday"]),
     ("dear", ["chere","cher"]),
     ("decentralise", ["core"]),
     ("decimally", ["intens"]),
     ("deep", ["main","sea"]),
     ("derision", ["sneers"]),
     ("detectives", ["cid","yard"]),
     ("diamond", ["ice","rock"]),
     ("director", ["scorsese"]),
     ("distressed", ["tearful"]),
     ("determined",["obdurate"]),
     ("drawback", ["ward"]),
     ("dressmaker", ["satin","silk"]),
     ("earnest request",["prayer"]),
     ("economist", ["mill","smith"]),
     ("ecstatic", ["sent"]),
     ("educational journal", ["test"]),
     ("fascist",["duce"]),
     ("flyer",["airman"]),
     ("flying",["jet"]),
     ("fondness",["endearment"]),
     ("footwear", ["shoes","plimsoles","pumps","sneakers"]),
     ("french citizen", ["parisian"]),
     ("game", ["ru"]),
     ("general", ["grant","lee"]),
     ("goddess", ["athena","isis","ate","hebe"]),
     ("goodbye", ["tata","vale"]),
     ("greek character", ["nu","alpha","lambda","omega","pi","mu","beta","chi","phi","eta","iota"]),
     ("greek letter", ["nu","alpha","lambda","omega","pi","mu","beta","chi","phi","eta","iota"]),
     ("green",["eco"]),
     ("grub", ["food", "lunch", "dinner", "snack"]),
     ("gun", ["sten","arm","lewis","bren","gat","maxim"]),
     ("hard ground", ["hearth"]),
     ("holiday apartment",["timeshare"]),
     ("home counties",["se"]),
     ("horse race", ["oaks","national","derby"]),
     ("hospital department",["ent"]),
     ("in a muddle",["shemozzle"]),
     ("indications",["signage"]),
     ("irish house", ["dail"]),
     ("jammed cylinder", ["swiss roll"]),
     ("king", ["lear"]),
     ("knocks", ["poohpoohs"]),
     ("language", ["haskil"]),
     ("lake", ["erie","loch"]),
     ("last letter", ["omega"]),
     ("lawgiver", ["moses"]),
     ("legal document", ["deed"]),
     ("letter", ["a", "bee", "cee", "dee", "e", "ef", "eff",
                 "gee", "aitch", "i", "jay", "kay", "el", "ell",
                 "em", "en", "o", "pee", "cue", "ar", "ess",
                 "tee", "u", "vee", "ex", "wy", "wye", "zee", "zed"]),
     ("liberal",["l"]),
     ("loch", ["ness"]),
     ("lock keeper", ["hair net"]),
     ("match", ["test"]),
     ("main", ["sea","deep"]),
     ("merchant of Venice", ["polo"]),
     ("money", ["tin","cent"]),
     ("monstrous regiment", ["women"]),
     ("motor race", ["carnation"]),
     ("mountaineer", ["sherpa"]),
     ("function", ["cosine","sine"]),
     ("mooring area", ["marina","harbour"]),
     ("member",["arm","leg"]),
     ("money spent",["disbursement"]),
     ("muse",["calliope","clio","euterpe","erato","melpomene",
              "polyhymnia","terpsichore","thalia","urania"]),
     ("muscle", ["pec"]),
     ("musical passage", ["stretta", "stretto"]),
     ("millers corn", ["grist"]),
     ("misanthrope", ["timon"]),
     ("mole", ["spy","pier"]),
     ("neat sound", ["lowing","moo"]),
     ("new York", ["gotham","ny"]),
     ("newspaper", ["sun"]),
     ("no longer", ["ex"]),
     ("noahs son",["shem"]),
     ("not public",["secret"]),
     ("notice",["ack"]),
     ("notice",["sign"]),
     ("old city", ["ur","troy"]),
     ("old fighter", ["gladiator"]),
     ("old", ["ex"]),
     ("old lady", ["mother"]),
     ("old people", ["iceni"]),
     ("old prime minister", ["pitt","eden"]),
     ("old scholar", ["erasmus"]),
     ("on purpose", ["meant"]),
     ("one fifteen", ["aside"]),
     ("oxford dreamer", ["spire"]),
     ("oven",["oast"]),
     ("paper in the street",["litter"]),
     ("paradise", ["eden"]),
     ("paragliding", ["sport", "thrilling sport"]),
     ("parties",["thrashes"]),
     ("party",["thrash"]),
     ("philosopher", ["plato","bacon"]),
     ("piece", ["bit","pawn","man"]),
     ("poor horse", ["rosinante"]),
     ("port", ["rio","aden"]),
     ("princess", ["ina","regan","ida","anne","di"]),
     ("prison", ["bird","jug","quad","cooler","pen","nick","hock","stir","can"]),
     ("provided",["if"]),
     ("providing",["if"]),
     ("put food in this",["tuckerbag"]),
     ("race", ["oaks","national","derby"]),
     ("record", ["log","disc","entry"]),
     ("result", ["win", "draw", "lose"]),
     ("river", ["po","isis","ure","cam","ea","dee","alph","aire","fal","tay","exe","ouse","tees"]),
     ("rocking scale", ["richter"]),
     ("row", ["ado","tier"]),
     ("rowing boat", ["eight","four"]),
     ("rousted", ["disturbed"]),
     ("rubbish",["tat"]),
     ("runner", ["river"]),
     ("running", ["admin"]),
     ("russian fighter",["mig"]),
     ("sea", ["main","mer","deep"]),
     ("shipping company", ["line"]),
     ("source", ["parent"]),
     ("skipping", ["omitting"]),
     ("school",["groom"]),
     ("scorer", ["composer", "engraver"]),
     ("scot", ["mon","jock","mac","ian"]),
     ("scotsman", ["jock","mac","ian","mon"]),
     ("screecher", ["swift"]),
     ("second rate", ["b"]),
     ("secretary", ["temp"]),
     ("show ring", ["manifesto"]),
     ("shoes", ["trainers"]),
     ("side",["eleven"]),
     ("skin disease",["mange"]),
     ("small space",["alcove"]),
     ("small worker",["ant"]),
     ("sober",["tt"]),
     ("spy",["m","q"]),
     ("stuff",["tuck"]),
     ("tantalus prisoner", ["decanter"]),
     ("term", ["hilary", "michaelmas", "trinity"]),
     ("theme",["leitmotif"]),
     ("this evening",["tonight"]),
     ("twenty five pounds", ["pony"]),
     ("unfashionable", ["out","square"]),
     ("used to be", ["was"]),
     ("vermouth", ["it"]),
     ("vessel", ["pan","tin","can"]),
     ("warning", ["fore","cave"]),
     ("waste paper",["litter"]),
     ("weight", ["tonne"]),
     ("welsh riots", ["rebecca"]),
     ("wicked sister", ["regan"]),
     ("wigging", ["earful"]),
     ("wine", ["aseti","asti","port","tent"]),
     ("with a tenant", ["let"]),
     ("with tenant", ["let"]),
     ("woman", ["her","she"]),
     ("word processor", ["ear"]),
     ("work", ["opus","go","do"]),
     ("worker", ["ant","man","hand","bee"]),
     ("working",["on"]),
     ("zero", ["ring", "circle"]),
     ("young feller", ["washington"]),

-- Reverse dictionary synonyms...
     ("holiday apartment", ["timeshare"])]

indirectSynonyms
  = map (\(w, w') -> (w, directSynonyms w')) indirectSynonymsTable

indirectSynonymsTable
  = [("land", "region"),
     ("title", "status"),
     ("bread", "money"),
     ("distance", "measure"),
     ("maths function", "function"),
     ("six footer", "insect"),
     ("swimmer", "fish"),
     ("holiday island", "island"),
     ("the day", "day")]


------- NAME SYNONYMS --------

associate syns names
  = map (\s -> (s,names)) syns

nameSynonyms
  = associate malesynonyms (Set.elems maleNames) ++
    associate femalesynonyms (Set.elems femaleNames)

malesynonyms
  = ["man", "him", "his name", "name", "boy", "he", "fellow"]

femalesynonyms
  = ["woman", "lady", "her", "her name", "name", "girl", "she"]


------- ABBREVIATONS --------

-- Only need genuine abbreviations.
abbreviationsTable
  = Map.fromList [("12.5 cents", ["dime"]),
     ("45 minutes", ["our","hou"]),
     ("666", ["mb"]),
     ("a", ["i"]),
     ("a follower", ["b"]),
     ("able seaman", ["ab"]),
     ("able to", ["can"]),
     ("about", ["ca","on","re","c"]),
     ("about turn", ["u"]),
     ("abstaining", ["tt"]),
     ("academic", ["ma","prof"]),
     ("academician", ["ra","a","ara","pra","prof"]),
     ("academy", ["rada","ra"]),
     ("acceptable", ["u","ok"]),
     ("accepted", ["a"]),
     ("account", ["ac","acc"]),
     ("a and e", ["ae"]),
     ("a & e", ["ae"]),
     ("a&e", ["ae"]),
     ("accident and emergency", ["ae"]),
     ("accountant", ["ca","aca","ac"]),
     ("ace", ["a","ai"]),
     ("acknowledge", ["ack"]),
     ("acknowledgement", ["ack"]),
     ("acre", ["a"]),
     ("across", ["x"]),
     ("act", ["do"]),
     ("acting", ["on"]),
     ("active", ["a"]),
     ("actuary", ["aia","fia"]),
     ("admitting", ["am","iam","im"]),
     ("adult", ["a"]),
     ("advanced", ["lent","a"]),
     ("advertisement", ["ad"]),
     ("aeroplane", ["mig"]),
     ("after date", ["ad"]),
     ("after the style of", ["ala"]),
     ("afternoon", ["a","iam","pm"]),
     ("again", ["bis","re"]),
     ("against", ["con","v"]),
     ("age", ["eon"]),
     ("aged", ["aet","ae"]),
     ("agent", ["rep","spy","v","g"]),
     ("agreement", ["ay","ja","aye","yea","da","oui","si"]),
     ("airborne soldier", ["para"]),
     ("aircraftsman", ["ac","lac"]),
     ("airline", ["ba","bac","bea"]),
     ("airman", ["po"]),
     ("alabama", ["al","ala"]),
     ("alan", ["al"]),
     ("alaska", ["alas"]),
     ("albania", ["al"]),
     ("albert", ["al"]),
     ("alcoholic state", ["dt"]),
     ("aleph", ["a"]),
     ("alien", ["et"]),
     ("all right", ["ok"]),
     ("alloy", ["y"]),
     ("alpha", ["a"]),
     ("alternating current", ["ac"]),
     ("alternative", ["or"]),
     ("alternatively", ["or"]),
     ("alto", ["a"]),
     ("aluminium", ["al"]),
     ("always", ["ay","ere","aye","eer"]),
     ("amateur", ["a", "diy"]),
     ("amateurs department", ["diy"]),
     ("ambassador", ["he"]),
     ("america", ["us","usa","am"]),
     ("american", ["am","amer","us"]),
     ("american detective", ["fed","g man"]),
     ("american lawyer", ["da"]),
     ("american man", ["bo"]),
     ("american policeman", ["bull"]),
     ("american railway", ["el"]),
     ("american soldier", ["joe","gi"]),
     ("ampere", ["a"]),
     ("an", ["a","i"]),
     ("anarchist", ["red"]),
     ("ancient city", ["ur","troy"]),
     ("ancient times", ["bc"]),
     ("and", ["et"]),
     ("ane", ["a","i"]),
     ("anger", ["ire"]),
     ("angle", ["l"]),
     ("anglo saxon", ["as"]),
     ("angstrom", ["a"]),
     ("annual meeting", ["agm"]),
     ("answer", ["a","ans"]),
     ("ante", ["a"]),
     ("appeal", ["sos"]),
     ("appearance", ["air"]),
     ("application", ["use"]),
     ("apprentice", ["l"]),
     ("approval", ["ok"]),
     ("approx", ["ca","some","c"]),
     ("approximately", ["some","c","ca"]),
     ("arab", ["ar"]),
     ("archdeacon", ["ven"]),
     ("archer", ["tell"]),
     ("are", ["r","a"]),
     ("argy", ["rg"]),
     ("argy bargy", ["rg"]),
     ("arithmetic", ["r"]),
     ("army", ["ta"]),
     ("army regulation", ["ar"]),
     ("around", ["o","c"]),
     ("arrival", ["arr","ar"]),
     ("arrive", ["arr","ar"]),
     ("ars", ["rr"]),
     ("art nouveau", ["rat","tar"]),
     ("article", ["a","an","the"]),
     ("axis", ["x", "y", "z"]),
     ("french article", ["la","les","le"]),
     ("french friend", ["ami"]),
     ("french way", ["rue"]),
     ("german article", ["der","die","das"]),
     ("italian article", ["il","la"]),
     ("spanish article", ["la","el","los"]),
     ("artillery", ["ra"]),
     ("artist", ["ra","lely","ara","pra","etty"]),
     ("arty", ["rt"]),
     ("as", ["s","qua"]),
     ("as above", ["us"]),
     ("asian", ["e"]),
     ("associate", ["a"]),
     ("at home", ["in"]),
     ("at one on", ["ation"]),
     ("at university", ["up"]),
     ("atomic", ["a"]),
     ("attempt", ["try"]),
     ("aught", ["o"]),
     ("australia", ["a","aus","oz"]),
     ("australian", ["a","aus","oz"]),
     ("austria", ["a"]),
     ("author", ["pen"]),
     ("authorisation", ["ok"]),
     ("autobiography", ["cv"]),
     ("average", ["ave","aver"]),
     ("avogadros number", ["n"]),
     ("award", ["om","obe","ch"]),
     ("away", ["out"]),
     ("ay", ["a","i"]),
     ("aye", ["i","a"]),
     ("ayes", ["is","as"]),
     ("ays", ["is","as"]),
     ("azed", ["az"]),
     ("bach", ["b"]),
     ("bachs works", ["s"]),
     ("bachelor", ["b","ba"]),
     ("bachelor of arts", ["ba"]),
     ("bad actor", ["ham"]),
     ("bad french", ["mal"]),
     ("badly", ["ill"]),
     ("bald patch", ["o"]),
     ("ball", ["o"]),
     ("bandage", ["t"]),
     ("bank rate", ["br"]),
     ("banker", ["river"]),
     ("bar", ["t","z"]),
     ("barbarian", ["hun"]),
     ("bargain", ["go"]),
     ("barium", ["ba"]),
     ("baron", ["b"]),
     ("barrel", ["b"]),
     ("barrels", ["b"]),
     ("barrier", ["dam"]),
     ("bass", ["b"]),
     ("batting", ["in"]),
     ("beady", ["bd"]),
     ("beard", ["awn"]),
     ("bears", ["has"]),
     ("beat", ["lam","tan"]),
     ("bed", ["cot"]),
     ("bedbug", ["b"]),
     ("bee", ["b"]),
     ("beer", ["ale"]),
     ("bees", ["bs","bb"]),
     ("beethoven", ["b"]),
     ("before", ["or","a","an","ere"]),
     ("before christ", ["ac","bc"]),
     ("before food", ["ac"]),
     ("before the day", ["ad"]),
     ("beginning", ["alpha"]),
     ("being broadcast", ["on"]),
     ("bel", ["b"]),
     ("belgium", ["b"]),
     ("bend", ["u","z","s"]),
     ("bender", ["knee"]),
     ("beta", ["b"]),
     ("beth", ["b"]),
     ("beware", ["kv"]),
     ("bible", ["rv","av"]),
     ("big", ["os"]),
     ("big banger", ["tnt"]),
     ("big bell", ["tom"]),
     ("big guns", ["ra"]),
     ("big noise", ["vip"]),
     ("bikini", ["atoll"]),
     ("bill", ["ac","acc"]),
     ("bird", ["prison","tit"]),
     ("bishop", ["bp","rr","b","odo"]),
     ("bit", ["ort"]),
     ("black", ["b"]),
     ("blob", ["o"]),
     ("blood group", ["o","b","a"]),
     ("bloody", ["red","b"]),
     ("blue", ["sad"]),
     ("bluetit", ["nun"]),
     ("blunder", ["err"]),
     ("boasting", ["am","iam","im"]),
     ("boat", ["q","e","u"]),
     ("bob", ["s"]),
     ("body", ["x"]),
     ("bomb", ["v","a","egg","h"]),
     ("bonds boss", ["m"]),
     ("bone", ["os","t"]),
     ("book", ["b","nt","ot","lib","vol","bk"]),
     ("bookmaker", ["amos","job"]),
     ("books", ["bb","ot","nt"]),
     ("born", ["n","ne","nat","b","nee"]),
     ("boron", ["b"]),
     ("bound", ["bd"]),
     ("bowled", ["b"]),
     ("boy", ["b"]),
     ("brahms", ["b"]),
     ("brakes", ["abs"]),
     ("branch", ["br"]),
     ("brazilian", ["para"]),
     ("breadth", ["b"]),
     ("bridge", ["br"]),
     ("bridge opponents", ["nw","sw","ne","se"]),
     ("bridge partners", ["ns","ew"]),
     ("bridge players", ["n","e","s","w"]),
     ("brief reply", ["ans"]),
     ("brig", ["br"]),
     ("britain", ["b","br"]),
     ("british", ["b","br"]),
     ("british company", ["bl"]),
     ("british museum", ["bm"]),
     ("british rail", ["br"]),
     ("brother", ["bro","br","fr"]),
     ("brown", ["br","tan"]),
     ("bull", ["ox"]),
     ("business", ["co","biz","ado"]),
     ("busy", ["tec"]),
     ("butler", ["rab"]),
     ("butter", ["ram"]),
     ("buzzer", ["bee"]),
     ("by", ["per"]),
     ("cagey", ["kg"]),
     ("calcium", ["ca"]),
     ("california", ["cal"]),
     ("can", ["may","tin","able"]),
     ("cape", ["c"]),
     ("capeks play", ["rur"]),
     ("capital", ["ai"]),
     ("capital authority", ["glc"]),
     ("capone", ["al"]),
     ("captain", ["cid"]),
     ("capture", ["net"]),
     ("caput", ["c"]),
     ("car", ["rr","mini"]),
     ("car test", ["mot"]),
     ("carat", ["car","ct"]),
     ("carbon", ["c"]),
     ("carbon monoxide", ["co"]),
     ("card", ["ace"]),
     ("care of", ["co"]),
     ("cart", ["t"]),
     ("cases", ["ca"]),
     ("cash", ["tin"]),
     ("castle", ["oo","r"]),
     ("cat", ["tom","mog","rex"]),
     ("cattle", ["kine","neat"]),
     ("caught", ["ct","c"]),
     ("cave", ["kv"]),
     ("cavity", ["o"]),
     ("cavy", ["kv"]),
     ("cayenne", ["kn"]),
     ("cedi", ["c"]),
     ("cedilla", ["z"]),
     ("celsius", ["c"]),
     ("celt", ["q","p"]),
     ("cent", ["red","ct","c"]),
     ("centi ", ["c"]),
     ("centigrade", ["c"]),
     ("centime", ["ct","c"]),
     ("central heating", ["ch"]),
     ("century", ["c"]),
     ("champion", ["ace","ch"]),
     ("channel islands", ["ci"]),
     ("chapter", ["ch","cap","c"]),
     ("charles", ["c"]),
     ("che", ["i"]),
     ("cheat", ["do"]),
     ("cheers", ["ta"]),
     ("chemist", ["mps"]),
     ("cherished", ["pet"]),
     ("chess grandmaster", ["tal"]),
     ("chi", ["x"]),
     ("chief", ["ch","cid"]),
     ("chief executive", ["dg"]),
     ("child", ["c","ch"]),
     ("childless", ["sp"]),
     ("children", ["seed"]),
     ("chimney", ["lum"]),
     ("china", ["ch","ming"]),
     ("china area", ["fare"]),
     ("chinese dynasty", ["han","ming"]),
     ("chlorine", ["cl"]),
     ("christ", ["x"]),
     ("christian era", ["ad"]),
     ("christmas period", ["dec"]),
     ("chromosome", ["y","x"]),
     ("church", ["c","ce","rc","ch"]),
     ("church of england", ["ce"]),
     ("cipher", ["o"]),
     ("circa", ["c"]),
     ("circle", ["ring","disc","o"]),
     ("circuit", ["o"]),
     ("circular letter", ["o"]),
     ("citation", ["cit"]),
     ("city", ["ec","ely"]),
     ("civil service", ["cs"]),
     ("class", ["cl"]),
     ("clause", ["cl"]),
     ("clear", ["rid"]),
     ("clef", ["f","g"]),
     ("cleric", ["bd","dd"]),
     ("close", ["nie"]),
     ("cloth", ["t","rep"]),
     ("cloudy", ["c"]),
     ("club", ["c"]),
     ("clubs", ["c"]),
     ("cobalt", ["co"]),
     ("cockney girl", ["er"]),
     ("cocktail", ["egg"]),
     ("cold", ["c"]),
     ("collection", ["ans"]),
     ("college", ["c"]),
     ("colombia", ["co"]),
     ("commander", ["oc","cinc","co","com"]),
     ("commanding officer", ["co"]),
     ("commotion", ["todo"]),
     ("communist", ["red"]),
     ("companion", ["ch"]),
     ("companion of honour", ["ch"]),
     ("company", ["two","co"]),
     ("completely", ["all"]),
     ("complex number", ["c"]),
     ("concerning", ["re"]),
     ("condition", ["if"]),
     ("confusion", ["pi"]),
     ("connecticut", ["ct"]),
     ("conservative", ["c","con","u"]),
     ("constant", ["k"]),
     ("contemporary", ["ad"]),
     ("continent", ["eur"]),
     ("contralto", ["c"]),
     ("contrivance", ["art"]),
     ("cook", ["do"]),
     ("copper", ["d","p","cu","pc"]),
     ("copy", ["ape"]),
     ("copyright", ["c"]),
     ("corn", ["rip"]),
     ("corner", ["l"]),
     ("cornwall", ["sw"]),
     ("corporation", ["tum"]),
     ("correct", ["ok"]),
     ("corruption", ["rot"]),
     ("coulomb", ["c"]),
     ("counter", ["gm"]),
     ("county", ["co","som"]),
     ("county council", ["cc"]),
     ("court", ["ct"]),
     ("cove", ["man"]),
     ("credit", ["cr", "iou"]),
     ("credit note", ["iou"]),
     ("credit notes", ["ious"]),
     ("cross", ["t","x","zo","tau"]),
     ("crossed", ["t"]),
     ("crown", ["cr"]),
     ("cry of delight", ["ole"]),
     ("cry of triumph", ["io"]),
     ("cuba", ["c"]),
     ("cue", ["q"]),
     ("cunning", ["art"]),
     ("cup holder", ["hebe"]),
     ("current", ["ac","dc"]),
     ("curse", ["ban"]),
     ("curve", ["arc"]),
     ("custom", ["use"]),
     ("cutie", ["qt"]),
     ("czechoslovakia", ["cs"]),
     ("dads army", ["hg"]),
     ("dagger", ["da"]),
     ("daisy", ["cow"]),
     ("damn", ["d"]),
     ("dance", ["pas"]),
     ("date", ["d"]),
     ("daughter", ["d"]),
     ("dawn", ["nus"]),
     ("day", ["v","d"]),
     ("days", ["dd"]),
     ("dead", ["d","obit"]),
     ("dead reckoning", ["dr"]),
     ("debtor", ["dr"]),
     ("decay", ["rot"]),
     ("deci", ["d"]),
     ("decisive blow", ["ko"]),
     ("decree", ["act"]),
     ("dee", ["d"]),
     ("degree", ["ma","deg","ba","d"]),
     ("delete", ["d"]),
     ("delta", ["d"]),
     ("democrat", ["d"]),
     ("denmark", ["dk"]),
     ("density", ["d"]),
     ("desert", ["rat"]),
     ("desert fighter", ["rat"]),
     ("deserted", ["d"]),
     ("deserter", ["rat"]),
     ("designer", ["dior"]),
     ("dessert", ["fool"]),
     ("detective", ["det","tec"]),
     ("deuterium", ["d"]),
     ("deutsch", ["d"]),
     ("devon", ["sw"]),
     ("dial", ["o"]),
     ("diameter", ["d"]),
     ("diamond", ["d"]),
     ("diamonds", ["d"]),
     ("died", ["d","obit"]),
     ("differential operator", ["d"]),
     ("difficulty", ["ado","er"]),
     ("dime", ["ioc"]),
     ("diplomat", ["cd"]),
     ("diracs constant", ["h"]),
     ("direction", ["e","s","w","n"]),
     ("director", ["d"]),
     ("director general", ["dg"]),
     ("directors", ["board"]),
     ("disadvantage", ["ward"]),
     ("disc", ["o"]),
     ("display", ["air"]),
     ("district attorney", ["da"]),
     ("ditch", ["haha"]),
     ("ditto", ["do"]),
     ("divine", ["dd"]),
     ("do it yourself", ["diy"]),
     ("doctor", ["bm","mb","who","md","mo","dd","dr","gp","healer"]),
     ("doctor of divinity", ["dd"]),
     ("doctrine", ["ism"]),
     ("doll", ["qp"]),
     ("dollar", ["s"]),
     ("dont change it", ["stet"]),
     ("donkey", ["ned","ass"]),
     ("double", ["di","bi","ka"]),
     ("double act", ["dodo"]),
     ("doubt", ["um"]),
     ("doughboy", ["gi"]),
     ("drag", ["d"]),
     ("dram", ["dr"]),
     ("draw", ["x"]),
     ("drawer", ["dr"]),
     ("drinking", ["on"]),
     ("drowned valley", ["ria"]),
     ("drunk", ["lit"]),
     ("dry", ["sec","tt"]),
     ("duck", ["o"]),
     ("ducks eggs", ["oo"]),
     ("duke", ["fist","d"]),
     ("durham area", ["ne"]),
     ("dutch uncle", ["oom"]),
     ("each", ["ea"]),
     ("early morning", ["iam"]),
     ("earth", ["ge","e"]),
     ("ease", ["es","ee"]),
     ("east", ["e","ost"]),
     ("east africa", ["ea"]),
     ("eastern", ["e"]),
     ("ecclesiastical title", ["ven"]),
     ("ecuador", ["ec"]),
     ("editor", ["ed"]),
     ("educated man", ["ma"]),
     ("educational establishment", ["u"]),
     ("edward", ["e","ed","ted"]),
     ("effect", ["a"]),
     ("egg", ["o"]),
     ("egypt", ["et"]),
     ("eight", ["e"]),
     ("eight thousand", ["e"]),
     ("eighty", ["r"]),
     ("eighty thousand", ["r"]),
     ("el", ["l"]),
     ("elected", ["in"]),
     ("electoral system", ["pr"]),
     ("electrical capacity", ["c"]),
     ("electrical charge", ["q"]),
     ("electrical current", ["i"]),
     ("electrical flux", ["d"]),
     ("elevated railway", ["l"]),
     ("eleven", ["xi","o","ii"]),
     ("eleven thousand", ["o"]),
     ("elizabeth", ["e"]),
     ("ell", ["l"]),
     ("ells", ["ll","ls"]),
     ("els", ["ll","ls"]),
     ("em", ["m"]),
     ("employ", ["use"]),
     ("employment", ["use"]),
     ("empty", ["o"]),
     ("empty container", ["tion"]),
     ("ems", ["mm","ms"]),
     ("en", ["n"]),
     ("enclosure", ["pen"]),
     ("encourage", ["egg"]),
     ("energy", ["go","e"]),
     ("engineer", ["ce","re"]),
     ("engineers", ["re","reme","ce"]),
     ("england", ["eng","e"]),
     ("english", ["eng","e"]),
     ("ens", ["ns","nn"]),
     ("envy", ["nv"]),
     ("epistle", ["ep"]),
     ("epsilon", ["e"]),
     ("era", ["ad"]),
     ("ergo", ["so"]),
     ("err", ["sin"]),
     ("es", ["s"]),
     ("ess", ["s"]),
     ("essay", ["sa","try"]),
     ("essen", ["sn"]),
     ("essex", ["sx"]),
     ("estimated time of arrival", ["eta"]),
     ("eta", ["e"]),
     ("ever", ["er","eer","ay","aye"]),
     ("everybody", ["all"]),
     ("everything", ["all"]),
     ("evil", ["sin"]),
     ("ewe", ["u"]),
     ("ewes", ["us","uu"]),
     ("ex", ["x"]),
     ("examination", ["test","a","o","oral"]),
     ("excel", ["xl"]),
     ("excellency", ["he"]),
     ("excited", ["up"]),
     ("exe", ["x"]),
     ("exercise", ["pe", "pt"]),
     ("exist", ["be"]),
     ("existing state", ["asis"]),
     ("exists", ["iss"]),
     ("exotic", ["et"]),
     ("expert", ["ace","dab","able","pro"]),
     ("explosive", ["tnt","he"]),
     ("extraterrestrial", ["et"]),
     ("extremity", ["toe"]),
     ("eye", ["i"]),
     ("eyes", ["ii","is"]),
     ("eyesore", ["stye"]),
     ("fabric", ["net"]),
     ("fabulous bird", ["roc"]),
     ("fabulous hare", ["loser"]),
     ("fabulous tortoise", ["winner"]),
     ("fahrenheit", ["f"]),
     ("fairly quiet", ["mp"]),
     ("fairy queen", ["mab"]),
     ("farad", ["f"]),
     ("farewell", ["vale"]),
     ("farthing", ["q","f"]),
     ("fashion", ["rage","ton"]),
     ("fashionable", ["in"]),
     ("fashionable people", ["ton"]),
     ("fast car", ["gt","rod"]),
     ("father", ["da","pa","dad","pop","time","fr"]),
     ("fathom", ["f"]),
     ("favoured", ["in"]),
     ("favourite", ["pet"]),
     ("feet", ["ft"]),
     ("fellow", ["f","man","gent","don"]),
     ("female", ["her","f","hen","she"]),
     ("female support", ["bra"]),
     ("female supporter", ["bra"]),
     ("feminine", ["f"]),
     ("fertiliser", ["nitre"]),
     ("field", ["ley","lea"]),
     ("fifty", ["a","l"]),
     ("fifty one", ["li"]),
     ("fifty pounds", ["ll"]),
     ("fifty thousand", ["l"]),
     ("fifty fifty", ["ll"]),
     ("fighter", ["man","gi"]),
     ("fighters", ["uff"]),
     ("filly", ["f"]),
     ("film", ["et","u","a","x"]),
     ("filthy place", ["sty"]),
     ("final letter", ["omega","z"]),
     ("final message", ["obit","rip"]),
     ("final word", ["amen","omega"]),
     ("fine", ["scot","ok","f"]),
     ("firm", ["fast","co"]),
     ("first", ["ist"]),
     ("first character", ["a","adam","alpha"]),
     ("first class", ["ai","a"]),
     ("first item in sale", ["loti"]),
     ("first lady", ["eve"]),
     ("first letter", ["a","alpha"]),
     ("first mate", ["eve"]),
     ("first murderer", ["cain"]),
     ("first person", ["me","adam","i"]),
     ("first victim", ["abel"]),
     ("fish", ["ide","id","eel","gar","cod","ling"]),
     ("five", ["v","e"]),
     ("five hundred", ["a","q","d"]),
     ("five hundred and one", ["di"]),
     ("five hundred thousand", ["q"]),
     ("five thousand", ["a","e"]),
     ("fleet", ["rn"]),
     ("fliers", ["raf"]),
     ("florida", ["fla"]),
     ("flourished", ["fl"]),
     ("flower", ["river","lis","rose"]),
     ("flowers", ["lei"]),
     ("fluorine", ["f"]),
     ("fly larva", ["bot"]),
     ("fly by night", ["bat","moth"]),
     ("folio", ["fo","f","fol"]),
     ("folios", ["ff"]),
     ("following", ["f"]),
     ("followings", ["ff"]),
     ("fool", ["ass"]),
     ("foot", ["f","ft"]),
     ("football", ["fa","ru"]),
     ("footnote", ["ps"]),
     ("for", ["pro"]),
     ("for all to see", ["u"]),
     ("for each", ["per"]),
     ("for example", ["eg","vg"]),
     ("for instance", ["eg"]),
     ("force", ["f","vis"]),
     ("forced", ["fz"]),
     ("foreign office", ["fo"]),
     ("former", ["ex"]),
     ("former squadron", ["red"]),
     ("forte", ["f"]),
     ("fortissimo", ["ff"]),
     ("forty", ["f"]),
     ("four", ["d","iv"]),
     ("four feet", ["ell"]),
     ("four hundred", ["p","g"]),
     ("four hundred thousand", ["p"]),
     ("four thousand", ["d"]),
     ("fourth man", ["seth"]),
     ("fox", ["tod"]),
     ("fragment", ["fr","ort"]),
     ("franc", ["fr"]),
     ("france", ["f"]),
     ("franco german agreement", ["ouija"]),
     ("free", ["rid"]),
     ("free of charge", ["foc"]),
     ("free on board", ["fob"]),
     ("free on rail", ["for"]),
     ("french", ["fr"]),
     ("french art", ["es"]),
     ("french king", ["sm","roi"]),
     ("french man", ["m","rene"]),
     ("french men", ["mm"]),
     ("french queen", ["reine","sm"]),
     ("french wine", ["vin"]),
     ("frequency", ["f"]),
     ("frequently", ["fr"]),
     ("friar", ["tuck"]),
     ("friday", ["f","man"]),
     ("from", ["ex","de"]),
     ("from the", ["dela","du"]),
     ("full moon", ["o"]),
     ("function", ["cot","asin","acos","cos","log","tan","sin"]),
     ("fuss", ["ado"]),
     ("gaelic", ["gael","erse"]),
     ("gallery", ["tate"]),
     ("game", ["nim", "ru"]),
     ("gamma", ["g"]),
     ("gamut", ["g"]),
     ("gangster", ["al"]),
     ("garden", ["eden","plot"]),
     ("gas", ["he","ne","f","cl","n","h","co","o"]),
     ("gauss", ["g"]),
     ("gee", ["g"]),
     ("gee gee", ["gg"]),
     ("general", ["gen","goc"]),
     ("general service", ["gs"]),
     ("general staff", ["gs"]),
     ("generation", ["era"]),
     ("genesis", ["gen"]),
     ("genius", ["id","ka"]),
     ("george", ["gr","g"]),
     ("georgia", ["ga"]),
     ("german", ["hun"]),
     ("german soldier", ["ss"]),
     ("germany", ["d","g"]),
     ("gift", ["gab"]),
     ("gin cocktail", ["ign","ing"]),
     ("girl", ["gal","g"]),
     ("girlfriend", ["gf"]),
     ("globe", ["o"]),
     ("god", ["ra","pan","lar"]),
     ("gods", ["s"]),
     ("gold", ["bull","or","au"]),
     ("good", ["g","ai","pi","a"]),
     ("good book", ["ot","nt"]),
     ("good man", ["dean","st"]),
     ("gorts men", ["bef"]),
     ("gotham", ["ny"]),
     ("government issue", ["gi"]),
     ("governor", ["he"]),
     ("gracious me", ["my"]),
     ("gradually", ["eric"]),
     ("graduate", ["ba","ma"]),
     ("grain", ["gr"]),
     ("gram", ["g"]),
     ("grammar", ["gr"]),
     ("gramme", ["g","gr"]),
     ("grand", ["g"]),
     ("graphite", ["kish"]),
     ("gravity", ["g"]),
     ("great britain", ["gb"]),
     ("greece", ["gr"]),
     ("greek", ["gr"]),
     ("greeting", ["ave","hi"]),
     ("group", ["set"]),
     ("group of workers", ["bee"]),
     ("grouse", ["gr"]),
     ("guerrilla", ["che"]),
     ("guinea", ["gu","g"]),
     ("gulf", ["o","g"]),
     ("gunmen", ["grs","ra"]),
     ("gunner", ["ra"]),
     ("gunners", ["ra"]),
     ("gym", ["pe"]),
     ("gypsy", ["rom","chal"]),
     ("gypsy woman", ["chai"]),
     ("hail", ["ave"]),
     ("hairdresser", ["comb"]),
     ("half", ["semi","hf","demi"]),
     ("half an em", ["n"]),
     ("half century", ["l"]),
     ("half day", ["pm","am"]),
     ("half ditch", ["ha"]),
     ("half dozen", ["vi"]),
     ("half dry", ["t"]),
     ("half minute", ["min","mo","ute"]),
     ("hand", ["man","h","l","ab","r"]),
     ("handwriting", ["ms"]),
     ("hard", ["h"]),
     ("hard water", ["ice"]),
     ("has", ["s"]),
     ("head", ["ras","pate","ness"]),
     ("healer", ["dr"]),
     ("heart", ["h"]),
     ("hearts", ["h"]),
     ("heat", ["j"]),
     ("heath", ["ted"]),
     ("heather", ["ling"]),
     ("hebrew letter", ["lamed","vau","resh","aleph","beth","teth"]),
     ("hedge", ["haw"]),
     ("height", ["h"]),
     ("helium", ["he"]),
     ("hell", ["pit","tor","dis"]),
     ("hello", ["hi"]),
     ("henry", ["h"]),
     ("her majesty", ["hm"]),
     ("here in rome", ["hic"]),
     ("here is", ["hs"]),
     ("hesitation", ["er","um","ur"]),
     ("high class", ["ai","u","a"]),
     ("high explosive", ["he"]),
     ("high tension", ["ht"]),
     ("hill", ["mt"]),
     ("hindrance", ["let"]),
     ("hire purchase", ["hp"]),
     ("his", ["s"]),
     ("his excellency", ["he"]),
     ("his majesty", ["hm"]),
     ("hole", ["f","o"]),
     ("hollow", ["o"]),
     ("holy writ", ["nt","ot"]),
     ("home counties", ["se"]),
     ("honey", ["mel"]),
     ("honour", ["obe","ch","om"]),
     ("hoop", ["o"]),
     ("horse", ["cob","nag","arab","gg","h","barb","gee"]),
     ("hospital", ["h"]),
     ("hot", ["h"]),
     ("hour", ["h","hr"]),
     ("house", ["semi","ho","co","cot","h"]),
     ("housekeeper", ["lar"]),
     ("humberside", ["ne"]),
     ("hundred", ["c","ton","ic"]),
     ("hundred and fifty", ["cl"]),
     ("hundred and one", ["ci"]),
     ("hundred and sixty", ["t"]),
     ("hundred and sixty thousand", ["t"]),
     ("hundred thousand", ["lac","c","lakh"]),
     ("hundreds", ["cs","d"]),
     ("hungary", ["h"]),
     ("hunter", ["orion"]),
     ("husband", ["h","man"]),
     ("hush", ["st","sh"]),
     ("hydrant", ["h"]),
     ("hydrogen", ["h"]),
     ("hymns", ["am"]),
     ("i", ["ane","an","ay","aye","eye","a"]),
     ("i am", ["am","iam","im"]),
     ("i had", ["id"]),
     ("i have", ["ive"]),
     ("i say", ["eye","aye"]),
     ("i see", ["ic"]),
     ("i shall", ["ill"]),
     ("i would", ["id"]),
     ("i, being french", ["je"]),
     ("iceland", ["is"]),
     ("identification", ["id"]),
     ("if", ["an"]),
     ("if it", ["ant"]),
     ("illegal army", ["ira","plo","eta"]),
     ("illinois", ["ill"]),
     ("illiterates signature", ["x"]),
     ("illness", ["flu"]),
     ("image building", ["pr"]),
     ("imaginary number", ["i"]),
     ("i felt", ["ow"]),
     ("in bed", ["bed"]),
     ("in charge", ["ic"]),
     ("in court", ["up"]),
     ("in fashion", ["in"]),
     ("in good condition", ["go"]),
     ("in paris, i", ["je"]),
     ("in the afternoon", ["pm"]),
     ("in the main", ["deep"]),
     ("in the modern age", ["ad"]),
     ("in the morning", ["am"]),
     ("in the same place", ["ibid","ib"]),
     ("in the style of", ["ala"]),
     ("in the year of our lord", ["ad"]),
     ("indeed", ["deed"]),
     ("indefinite number", ["n","no"]),
     ("india", ["ind"]),
     ("individual", ["i"]),
     ("individuality", ["ka"]),
     ("inductance", ["l"]),
     ("inexperienced driver", ["l"]),
     ("infantry", ["foot"]),
     ("inferior", ["b"]),
     ("inferior horse", ["tit"]),
     ("information", ["gen"]),
     ("informer", ["nose","grass"]),
     ("inn", ["bar"]),
     ("instinct", ["id"]),
     ("integers", ["z"]),
     ("intended", ["ment"]),
     ("international", ["cap","un"]),
     ("international organisation", ["uno"]),
     ("invariably", ["eer"]),
     ("inventor", ["edison"]),
     ("iodine", ["i"]),
     ("iota", ["i"]),
     ("iowa", ["ia"]),
     ("iran", ["ir"]),
     ("ireland", ["irl"]),
     ("irish police", ["ruc"]),
     ("iron", ["fe"]),
     ("is", ["est","s"]),
     ("is able to", ["can"]),
     ("island", ["ait","iom","is","man","eyot","i","inch"]),
     ("isle of man", ["iom"]),
     ("israel", ["il"]),
     ("issue", ["son"]),
     ("it", ["sa","a"]),
     ("italian", ["it"]),
     ("italian banker", ["po"]),
     ("italian flower", ["po"]),
     ("italy", ["i"]),
     ("ivy", ["iv"]),
     ("izzard", ["z"]),
     ("Jack", ["j"]),
     ("jade", ["yu"]),
     ("Jamaica", ["ja"]),
     ("Japan", ["j"]),
     ("jay", ["j"]),
     ("jazz fan", ["cat"]),
     ("jelly", ["gel"]),
     ("jolly", ["rm"]),
     ("joule", ["j"]),
     ("journalist", ["ed"]),
     ("joyful cry", ["io"]),
     ("judge", ["j"]),
     ("junction", ["t"]),
     ("justice", ["j"]),
     ("kale", ["kl"]),
     ("kappa", ["k"]),
     ("kay", ["k"]),
     ("kelt", ["q","p"]),
     ("kelvin", ["k"]),
     ("kentucky", ["ky"]),
     ("kewpie", ["qp"]),
     ("key", ["c","f","d","e","a","g","b"]),
     ("khmer republic", ["k"]),
     ("kick off", ["ko"]),
     ("killer", ["cain"]),
     ("kilo", ["k"]),
     ("kilometre", ["km"]),
     ("king", ["k","gr","hm","cr","roi","r","sm","er"]),
     ("king emperor", ["ri"]),
     ("king george", ["gr"]),
     ("kirkpatrick", ["k"]),
     ("kiss", ["x"]),
     ("knave", ["j"]),
     ("knew", ["wist"]),
     ("knight", ["kt","k","sir","n"]),
     ("knock out", ["ko"]),
     ("koechel", ["k"]),
     ("koppa", ["q"]),
     ("krypton", ["kr"]),
     ("label", ["tag","tab"]),
     ("laboratory", ["lab"]),
     ("labour", ["lab","l"]),
     ("lady", ["di","eve"]),
     ("lake", ["l"]),
     ("lambda", ["l"]),
     ("lambert", ["l"]),
     ("landline", ["ry","br","rly"]),
     ("large", ["l"]),
     ("large amount", ["ton","lot"]),
     ("large letters", ["os"]),
     ("largesse", ["s"]),
     ("last character", ["z"]),
     ("last letter", ["z"]),
     ("last month", ["ult","dec"]),
     ("last word", ["obit","rip","amen"]),
     ("late", ["ex"]),
     ("latin", ["l"]),
     ("latitude", ["l"]),
     ("laugh", ["haha","hehe","ha"]),
     ("lawman", ["earp","bl","da"]),
     ("lawrence", ["te"]),
     ("lawyer", ["bl","da"]),
     ("lawyers", ["bar"]),
     ("layer", ["hen","e"]),
     ("lead", ["pb"]),
     ("leading", ["noi"]),
     ("league", ["l"]),
     ("learner", ["l"]),
     ("learning", ["l"]),
     ("leave", ["part"]),
     ("leaves", ["tea"]),
     ("left", ["l"]),
     ("left hand", ["vo","lh"]),
     ("leftist", ["red"]),
     ("leg", ["on"]),
     ("legate", ["he"]),
     ("length", ["ell","l"]),
     ("lettuce", ["cos"]),
     ("level", ["a","y"]),
     ("liberal", ["l","lib"]),
     ("libya", ["lar"]),
     ("licentiate", ["l"]),
     ("lieutenant", ["lt"]),
     ("life symbol", ["ankh"]),
     ("light", ["very"]),
     ("like", ["as"]),
     ("lincoln", ["abe"]),
     ("line", ["row","l","i","ry"]),
     ("liner", ["ss"]),
     ("lines", ["ry","br","rly"]),
     ("lira", ["l"]),
     ("lire", ["l"]),
     ("listener", ["ear"]),
     ("litre", ["l"]),
     ("little", ["wee"]),
     ("little devil", ["imp"]),
     ("little horse", ["gg","ned","gee","nag"]),
     ("little way", ["st","rd","ry"]),
     ("little woman", ["jo"]),
     ("live", ["l","be"]),
     ("lived so long", ["av"]),
     ("loaded", ["lit"]),
     ("local", ["ph","inn","pub"]),
     ("logarithm base", ["e"]),
     ("london area", ["se"]),
     ("london district", ["ec"]),
     ("long", ["l"]),
     ("long playing", ["lp"]),
     ("long time", ["age"]),
     ("look", ["v","see","la","vide","lo"]),
     ("looker", ["eye"]),
     ("loop", ["o"]),
     ("los angeles", ["la"]),
     ("lot", ["d","m","c"]),
     ("loud", ["f"]),
     ("louisiana", ["la"]),
     ("love", ["o","nil"]),
     ("low", ["moo"]),
     ("low down", ["gen"]),
     ("low grade", ["e"]),
     ("lower", ["cow"]),
     ("lumen", ["l"]),
     ("luminance", ["l"]),
     ("lunchtime", ["one","i"]),
     ("luxembourg", ["l"]),
     ("magnesium", ["mg"]),
     ("magnetic flux", ["b"]),
     ("maiden", ["over","io","m"]),
     ("maiden over", ["m"]),
     ("mailboat", ["rms"]),
     ("main road", ["ai","mi"]),
     ("male", ["m","he","him"]),
     ("malta", ["m"]),
     ("man", ["isle","iom","g","vir","m"]),
     ("manage", ["run"]),
     ("managed", ["ran"]),
     ("management", ["admin"]),
     ("manuscript", ["ms"]),
     ("manuscripts", ["mss"]),
     ("many", ["l","c","m","d"]),
     ("mare", ["m"]),
     ("marine", ["jolly","rm"]),
     ("mark", ["m","d","dm"]),
     ("mark of the beast", ["mb"]),
     ("married", ["m"]),
     ("marshal", ["ney"]),
     ("masculine", ["m"]),
     ("mass", ["m"]),
     ("massachusetts", ["mass"]),
     ("master", ["ma","m"]),
     ("master of arts", ["ma"]),
     ("master of ceremonies", ["mc"]),
     ("maths function", ["cot","asin","acos","cos","log","tan","sin"]),
     ("mathematical function", ["cot","asin","acos","cos","log","tan","sin"]),
     ("mayfair", ["wi"]),
     ("meal ticket", ["lv"]),
     ("meant", ["ment"]),
     ("measure", ["ell","ft","m","em","el","en","yd","y"]),
     ("medal", ["td","mc","mm"]),
     ("meeting", ["agm"]),
     ("member", ["m","mp"]),
     ("member of parliament", ["mp"]),
     ("memory", ["rom","ram"]),
     ("men", ["or"]),
     ("merchant navy", ["mn"]),
     ("mercury", ["hg"]),
     ("merseyside", ["nw"]),
     ("meso ", ["m"]),
     ("meta ", ["m"]),
     ("meter", ["m"]),
     ("metre", ["m"]),
     ("midday", ["a","m","n"]),
     ("midnight", ["g"]),
     ("mile", ["m"]),
     ("military police", ["mp"]),
     ("miners", ["num"]),
     ("minor", ["wee"]),
     ("mischevious child", ["imp"]),
     ("mischief", ["ate"]),
     ("missiles", ["ammo"]),
     ("mississippi", ["miss"]),
     ("missouri", ["mo"]),
     ("mister", ["mr"]),
     ("model", ["t"]),
     ("modern journalism", ["eng"]),
     ("modern times", ["ad"]),
     ("modulus", ["m"]),
     ("monarch", ["k","r","er"]),
     ("monday", ["mon","m"]),
     ("money", ["m","l"]),
     ("monsieur", ["m"]),
     ("month", ["mo","r","m"]),
     ("months", ["mos"]),
     ("moon", ["m"]),
     ("morning", ["am"]),
     ("moth", ["y"]),
     ("mother", ["mum","ma","dam","mam"]),
     ("motoring organisation", ["aa","rac"]),
     ("motorway", ["m","mi"]),
     ("mountain", ["mt","tor","alp"]),
     ("mountain retreat", ["pla"]),
     ("mounted", ["up"]),
     ("mounted police", ["mp"]),
     ("mountie", ["mp"]),
     ("mounties", ["mp"]),
     ("mouthpiece", ["lips"]),
     ("mozarts works", ["k"]),
     ("mu", ["m"]),
     ("murder victim", ["abel"]),
     ("murderer", ["cain"]),
     ("music school", ["ram"]),
     ("muslim leader", ["aga"]),
     ("name", ["n"]),
     ("name unknown", ["nu"]),
     ("named", ["dit"]),
     ("namely", ["sc"]),
     ("national", ["n"]),
     ("nationalist", ["n"]),
     ("nationalists", ["sdp"]),
     ("native", ["abo"]),
     ("naught", ["o"]),
     ("naval commander", ["corn"]),
     ("navy", ["rn"]),
     ("near", ["nie"]),
     ("neck", ["col","v"]),
     ("neckline", ["v"]),
     ("neon", ["ne"]),
     ("neper", ["n"]),
     ("network", ["rete"]),
     ("neuter", ["n"]),
     ("neutral", ["n"]),
     ("never never", ["hp"]),
     ("new", ["n"]),
     ("new driver", ["l"]),
     ("new Jersey", ["nj"]),
     ("new orleans", ["no"]),
     ("new testament", ["nt"]),
     ("new York", ["ny"]),
     ("new York opera", ["met"]),
     ("newspaper", ["ft"]),
     ("newton", ["n"]),
     ("next month", ["prox"]),
     ("nickel", ["ni"]),
     ("nil", ["o"]),
     ("nine", ["ix"]),
     ("ninety", ["xc","n","q"]),
     ("ninety nine", ["ic"]),
     ("ninety thousand", ["n","q"]),
     ("nitrogen", ["n"]),
     ("no", ["o","nae","non","na"]),
     ("no date", ["nd"]),
     ("no good", ["ng","us"]),
     ("no one", ["noi"]),
     ("no way", ["ord"]),
     ("nobleman", ["don"]),
     ("noisy", ["f"]),
     ("non commissioned officer", ["rsm","sgt","sm","nco"]),
     ("non commissioned officers", ["or"]),
     ("noon", ["n","m"]),
     ("north", ["n"]),
     ("north america", ["na"]),
     ("north dakota", ["nd"]),
     ("north pole", ["np"]),
     ("northeastern", ["ne"]),
     ("northwestern", ["nw"]),
     ("north east", ["ne"]),
     ("north west", ["nw"]),
     ("north north east", ["nne"]),
     ("north north west", ["nnw"]),
     ("northern", ["n"]),
     ("northern ireland", ["ni"]),
     ("northern territories", ["nt"]),
     ("norway", ["n"]),
     ("not", ["nae","na","ne"]),
     ("not at home", ["out"]),
     ("not clear", ["nl"]),
     ("not dated", ["nd"]),
     ("not far", ["nl"]),
     ("not out", ["no","in"]),
     ("not permitted", ["nl"]),
     ("not specific", ["ns"]),
     ("nota bene", ["nb"]),
     ("notch", ["v"]),
     ("note", ["nb","lah","a","me","re","tic","soh","doh","te","g","ti","la","n","c","b","f","si","d","mi","fah","so","e","do","fa","ut","sol"]),
     ("nothing", ["o","nil"]),
     ("nothing to america", ["ous"]),
     ("notice", ["ack", "d","ad"]),
     ("nought", ["o"]),
     ("noun", ["n"]),
     ("novel", ["she"]),
     ("novice", ["l"]),
     ("now", ["anon","ad"]),
     ("nowadays", ["ad"]),
     ("nu", ["n"]),
     ("number", ["n","ether","d","pin","no"]),
     ("number one", ["noi","ein","uno","i","un","adam","une","me","una"]),
     ("number one returning", ["ion"]),
     ("number plate", ["l"]),
     ("nurse", ["srn","vad"]),
     ("objector", ["co"]),
     ("occupational therapy", ["ot"]),
     ("odds", ["sp"]),
     ("of", ["de"]),
     ("of the", ["dela","del","du","des"]),
     ("offensive", ["tet"]),
     ("office", ["loo","den"]),
     ("officer", ["co","lt"]),
     ("officer commanding", ["oc"]),
     ("officer in charge", ["oic"]),
     ("ogee", ["og"]),
     ("oh", ["o"]),
     ("oh, why", ["oy"]),
     ("ohio", ["o"]),
     ("ohs", ["oo","os"]),
     ("okay", ["ok"]),
     ("old age", ["eld"]),
     ("old bob", ["s"]),
     ("old boy", ["ob"]),
     ("old contemptibles", ["bef"]),
     ("old english", ["oe"]),
     ("old etonian", ["oe"]),
     ("old fiddle", ["gue","gu"]),
     ("old goat", ["gate"]),
     ("old injury", ["teen","tene"]),
     ("old irish magistrate", ["rm"]),
     ("old king", ["offa","cole","lud"]),
     ("old lady", ["ma", "mum"]),
     ("old man", ["dad","pop","pa"]),
     ("old paint", ["limn"]),
     ("old penny", ["d"]),
     ("old railway", ["sr","lner"]),
     ("old shilling", ["s","bob"]),
     ("old ship", ["argo"]),
     ("old style", ["os"]),
     ("old testament", ["ot"]),
     ("old thing", ["res"]),
     ("old way", ["via"]),
     ("old way of dating", ["auc"]),
     ("old woman", ["ma"]),
     ("omega", ["z"]),
     ("omicron", ["o"]),
     ("on", ["leg"]),
     ("on the menu", ["on"]),
     ("on the wagon", ["tt"]),
     ("on view to all", ["u"]),
     ("one", ["i","un","an","a","j","ane","ace"]),
     ("one answer", ["ians"]),
     ("one hundred and fifty", ["cl"]),
     ("one member", ["amp","imp"]),
     ("one pound", ["alb","al","il","l","lb","ilb"]),
     ("one thousand five hundred", ["md"]),
     ("one time", ["ex"]),
     ("ones", ["as","is"]),
     ("open university", ["ou"]),
     ("opening", ["o"]),
     ("operating", ["on"]),
     ("operation", ["op"]),
     ("opposing", ["v"]),
     ("opposite", ["op"]),
     ("opus", ["op"]),
     ("orb", ["o"]),
     ("orchestra", ["lso"]),
     ("order", ["obe","ch","po","om"]),
     ("ordinary seaman", ["os"]),
     ("organ", ["ear"]),
     ("orient", ["e"]),
     ("oriental", ["e","ine"]),
     ("ortho ", ["o"]),
     ("otorhinolaryngology", ["ent"]),
     ("ought", ["o"]),
     ("ounce", ["oz"]),
     ("our era", ["ad"]),
     ("our islands", ["gb"]),
     ("our man", ["he"]),
     ("our time", ["ad"]),
     ("out of print", ["op"]),
     ("outdated hairdo", ["da"]),
     ("outlaw", ["ban"]),
     ("outsize", ["os"]),
     ("over", ["supra","re"]),
     ("overhead railway", ["l"]),
     ("owe", ["o"]),
     ("owes", ["os","oo"]),
     ("own", ["ain"]),
     ("own goal", ["og"]),
     ("ox", ["neat","kine"]),
     ("oxygen", ["o"]),
     ("page", ["p"]),
     ("pages", ["pp"]),
     ("painter", ["ra","ara","ney","pra"]),
     ("painting", ["art"]),
     ("pair", ["pr"]),
     ("palladium", ["po"]),
     ("panama", ["pa"]),
     ("paper", ["ms","b","a"]),
     ("papers", ["mss"]),
     ("paragon", ["saint","s","st"]),
     ("park", ["p"]),
     ("parking", ["p"]),
     ("part", ["pt"]),
     ("part of bible", ["nt","ot"]),
     ("part of collar", ["s"]),
     ("participle", ["p"]),
     ("particle", ["x"]),
     ("partnership", ["we","sn","ew","ns"]),
     ("party", ["con","lib","do","lab","tory"]),
     ("pass", ["col"]),
     ("pawn", ["p"]),
     ("paying guest", ["pg"]),
     ("pea", ["p"]),
     ("peacekeepers", ["un"]),
     ("peacemakers", ["acas"]),
     ("peak", ["alp"]),
     ("peas", ["pp","ps"]),
     ("peavy", ["pv"]),
     ("pedal", ["p"]),
     ("pee", ["p"]),
     ("pees", ["pp","ps"]),
     ("peg", ["tee","t","p"]),
     ("pellet", ["o"]),
     ("pen", ["j"]),
     ("penny", ["d","p"]),
     ("per", ["a"]),
     ("perfect letter", ["t"]),
     ("performance", ["act"]),
     ("performing", ["on"]),
     ("period", ["age","bc","ad"]),
     ("permit", ["let"]),
     ("permitted", ["let"]),
     ("peru", ["pe"]),
     ("phosphorous", ["p"]),
     ("physical education", ["pe"]),
     ("physical training", ["pt"]),
     ("pi", ["p"]),
     ("pianissimo", ["pp"]),
     ("piano", ["p"]),
     ("pilot", ["george","ace"]),
     ("pint", ["p","pt"]),
     ("plancks constant", ["h"]),
     ("plate", ["t"]),
     ("platinum", ["pt"]),
     ("play", ["noh","no"]),
     ("playing", ["in","on"]),
     ("plotters street", ["cato"]),
     ("pluto", ["dis"]),
     ("pms address", ["ten","x"]),
     ("poet", ["ae"]),
     ("point", ["head","e","ness","tor","s","pt","w","n"]),
     ("poise", ["p"]),
     ("poland", ["pl"]),
     ("pole", ["rod","po","sp","np","s","n"]),
     ("police", ["force","met","cid"]),
     ("policeman", ["pc","mp"]),
     ("politician", ["con","mp","lib","lab","tory"]),
     ("poor actor", ["ham"]),
     ("poor horse", ["tit"]),
     ("port", ["l"]),
     ("port authority", ["pla"]),
     ("portugal", ["p"]),
     ("posh", ["u"]),
     ("post office", ["po"]),
     ("post town", ["pt"]),
     ("postscript", ["ps"]),
     ("potassium", ["k"]),
     ("pound", ["lb","lam","ezra","l"]),
     ("power", ["p","vis"]),
     ("practice", ["use"]),
     ("practise", ["use"]),
     ("present day", ["ad"]),
     ("preservationists", ["nt"]),
     ("president", ["pres","p","pr","chair"]),
     ("pretty girl", ["cutie","dish"]),
     ("prevent", ["bar"]),
     ("price", ["pr"]),
     ("priest", ["pr","eli","abbe","rev","cure"]),
     ("primate", ["ape"]),
     ("prime minister", ["pm"]),
     ("primitive", ["ur"]),
     ("prince", ["p","pr","ras"]),
     ("princess", ["p","di"]),
     ("printers measure", ["em","el","en"]),
     ("private", ["gi"]),
     ("prohibition", ["ban"]),
     ("prominence", ["tor"]),
     ("promises to pay", ["ious"]),
     ("promotion", ["ad"]),
     ("prophet", ["eli"]),
     ("provided", ["if"]),
     ("providing", ["if"]),
     ("psychotic state", ["dt"]),
     ("public relations", ["pr"]),
     ("public relations officer", ["pro"]),
     ("puerto rico", ["pr"]),
     ("puff", ["ad"]),
     ("pupil", ["l"]),
     ("pure", ["net"]),
     ("put", ["set"]),
     ("put on", ["don"]),
     ("qe", ["er"]),
     ("quality", ["q"]),
     ("quart", ["qt","qu"]),
     ("quarter", ["e","s","sw","w","n","nw","ne","se"]),
     ("quebec", ["q"]),
     ("queen", ["r","hm","q","qu","er","liz","mab","bess"]),
     ("queensland", ["q"]),
     ("query", ["q"]),
     ("question", ["q"]),
     ("queue", ["cue","q"]),
     ("quiet", ["p","mum","sh","qt"]),
     ("quintal", ["q"]),
     ("rabbi", ["r"]),
     ("rabbit", ["brer"]),
     ("race", ["nation","tt"]),
     ("radius", ["r"]),
     ("rage", ["ire"]),
     ("rail", ["ry","t"]),
     ("railway", ["br","rly","l","ry"]),
     ("railways", ["br"]),
     ("rain", ["r"]),
     ("rand", ["r"]),
     ("rare", ["r"]),
     ("rate", ["mph"]),
     ("rating", ["ab"]),
     ("rational numbers", ["q"]),
     ("ray", ["x"]),
     ("reading", ["r"]),
     ("ready", ["set","go"]),
     ("real numbers", ["r"]),
     ("reaumur", ["r"]),
     ("recipe", ["r","rec"]),
     ("record", ["cd","lp","ep"]),
     ("rector", ["r"]),
     ("refusal", ["no"]),
     ("regina", ["r"]),
     ("relation", ["sib"]),
     ("relationship", ["pi"]),
     ("relative", ["rel"]),
     ("religious", ["pi"]),
     ("religious education", ["re"]),
     ("remains", ["ash"]),
     ("reported", ["dit"]),
     ("representative", ["mp"]),
     ("republican", ["r"]),
     ("reserves", ["ta"]),
     ("resident magistrate", ["rm"]),
     ("resistance", ["r"]),
     ("restrain", ["dam"]),
     ("retreat", ["den"]),
     ("rev up", ["ver"]),
     ("revolutionary", ["che","red"]),
     ("rex", ["r"]),
     ("rho", ["r"]),
     ("rhode island", ["ri"]),
     ("riding", ["up"]),
     ("right", ["r","rt"]),
     ("right hand", ["rh","ro"]),
     ("right reverend", ["rr"]),
     ("ring", ["disc","o"]),
     ("ring road", ["ord"]),
     ("river", ["r"]),
     ("road", ["ave","r","a","rd","st"]),
     ("rolls royce", ["rr"]),
     ("roman", ["vir"]),
     ("roman catholic", ["rc"]),
     ("roman people", ["pr"]),
     ("romania", ["r"]),
     ("romans", ["rom","pr"]),
     ("romeo", ["r"]),
     ("rontgen unit", ["r"]),
     ("roof", ["m"]),
     ("rook", ["r"]),
     ("roughly", ["c","ca"]),
     ("round", ["o"]),
     ("royal", ["r"]),
     ("royal academician", ["ra"]),
     ("royal academy", ["ra"]),
     ("royal artillery", ["ra"]),
     ("royal badge", ["er"]),
     ("royal engineer", ["re"]),
     ("royal engineers", ["re"]),
     ("royal marine", ["rm"]),
     ("royal marines", ["rm"]),
     ("royal navy", ["rn"]),
     ("rubber", ["ule"]),
     ("rugby", ["ru"]),
     ("run", ["r"]),
     ("running water", ["ea"]),
     ("russian river", ["ob"]),
     ("sabbath", ["s"]),
     ("said", ["idem","dit"]),
     ("sailor", ["os","ab"]),
     ("sailors", ["rn"]),
     ("saint", ["s","st"]),
     ("saints", ["sts","ss"]),
     ("salesman", ["rep"]),
     ("salt", ["ab","jack","tar"]),
     ("same", ["do","id"]),
     ("same place", ["ib"]),
     ("sandhurst", ["rma"]),
     ("sapper", ["re"]),
     ("sappers", ["re"]),
     ("saturday", ["s","sat"]),
     ("save", ["bar"]),
     ("say", ["dit"]),
     ("scab", ["rat"]),
     ("scarlattis works", ["k"]),
     ("schmieder", ["s"]),
     ("scholar", ["ma","ba"]),
     ("school", ["eton"]),
     ("schuberts works", ["d"]),
     ("science centre", ["lab"]),
     ("scope, plenty of", ["az"]),
     ("scriptures", ["nt","ot"]),
     ("scruple", ["scr"]),
     ("seabee", ["cb"]),
     ("seaman", ["ab"]),
     ("seas", ["cc","cs"]),
     ("second", ["sec","mo","b","s"]),
     ("second child", ["abel"]),
     ("second class", ["b"]),
     ("second letter", ["b"]),
     ("second thoughts", ["ps"]),
     ("second hand", ["sh"]),
     ("secret service", ["cia"]),
     ("see", ["vid","c","v","vide","lo","ely"]),
     ("see why", ["cy"]),
     ("see you", ["cu"]),
     ("seedy", ["cd"]),
     ("seer", ["eye","optic"]),
     ("self confessed", ["iam","am","im"]),
     ("self contained", ["sc"]),
     ("senior", ["sr"]),
     ("sergeant", ["nco","sgt"]),
     ("service", ["rn","rm","ace","raf"]),
     ("serving man", ["gi"]),
     ("setter", ["me", "i"]),
     ("settled", ["lit"]),
     ("seven", ["s","z"]),
     ("seven thousand", ["s","z"]),
     ("sex appeal", ["it","sa"]),
     ("shares", ["scrip"]),
     ("shark", ["nurse"]),
     ("sheep", ["ram"]),
     ("shilling", ["s"]),
     ("ship", ["ss"]),
     ("shirt", ["t"]),
     ("short answer", ["ans"]),
     ("short break", ["hol"]),
     ("short time", ["t","sec","mo"]),
     ("side", ["xi","l","s","r","xv"]),
     ("siemens", ["s"]),
     ("sign", ["v"]),
     ("sign of love", ["x"]),
     ("sign of the times", ["x"]),
     ("silence", ["mum","st","sh","tace"]),
     ("silicon", ["si"]),
     ("silver", ["ag"]),
     ("simple", ["herb"]),
     ("sin", ["err"]),
     ("single", ["i"]),
     ("sister", ["sis","s"]),
     ("six", ["vi"]),
     ("sixpence", ["vid","vip"]),
     ("sixth sense", ["esp"]),
     ("skill", ["art"]),
     ("sling", ["ign","ing"]),
     ("sloth", ["ai"]),
     ("small", ["s"]),
     ("small capitals", ["sc"]),
     ("small change", ["p"]),
     ("small illustration", ["fig"]),
     ("small measure", ["cc","em","el","en"]),
     ("small quantity", ["cc"]),
     ("small square", ["m","em"]),
     ("small weight", ["wt","oz","gr","ct"]),
     ("smuggle", ["run"]),
     ("smuggled", ["ran"]),
     ("snake", ["asp","boa"]),
     ("snoring", ["zz"]),
     ("snow", ["s"]),
     ("so", ["ergo"]),
     ("soak", ["ret"]),
     ("sober", ["tt"]),
     ("soccer blunder", ["og"]),
     ("social worker", ["ant","bee"]),
     ("socialist", ["red"]),
     ("socially acceptable", ["u"]),
     ("society", ["s"]),
     ("sodium", ["na"]),
     ("soft", ["p","b","pp"]),
     ("softly", ["p","pp"]),
     ("soldier", ["ra","re","ta","ant","man","ney","gi"]),
     ("soldiers", ["ra","re","men","ta","sas","impi","or","gis"]),
     ("solver", ["you"]),
     ("some french", ["du","des"]),
     ("son", ["s"]),
     ("song", ["lay","aria","air"]),
     ("sons", ["s"]),
     ("soprano", ["sop","s"]),
     ("sound of sleep", ["z"]),
     ("sound of snoring", ["zz"]),
     ("south", ["s"]),
     ("southeastern", ["se"]),
     ("southwestern", ["sw"]),
     ("south east", ["se"]),
     ("south west", ["sw"]),
     ("south south east", ["sse"]),
     ("south south west", ["ssw"]),
     ("south africa", ["sa"]),
     ("south america", ["sa"]),
     ("south dakota", ["sd"]),
     ("south island", ["si"]),
     ("south pole", ["sp"]),
     ("southern", ["s"]),
     ("sovereign", ["l"]),
     ("soviet union", ["ussr","su"]),
     ("space", ["s"]),
     ("spade", ["s"]),
     ("spades", ["s"]),
     ("spain", ["e"]),
     ("spangle", ["o"]),
     ("spanish hero", ["cid"]),
     ("spasm", ["tic"]),
     ("speakers", ["lips"]),
     ("special", ["s"]),
     ("species", ["sp"]),
     ("specifically", ["as","sc"]),
     ("spectacles", ["oo"]),
     ("spectator", ["eye"]),
     ("speculator", ["stag","bear"]),
     ("speed", ["rate","mph"]),
     ("speed of light", ["c"]),
     ("spies", ["cia"]),
     ("spike", ["ear"]),
     ("sports car", ["rod","gt"]),
     ("spot marked", ["x"]),
     ("spring", ["spa","c"]),
     ("spy", ["agent"]),
     ("spymaster", ["m"]),
     ("square", ["t","s"]),
     ("square root of  1", ["j","i"]),
     ("stand in", ["sub"]),
     ("standard", ["par"]),
     ("starting price", ["sp"]),
     ("steamship", ["ss"]),
     ("step", ["pas"]),
     ("stokes", ["s","st"]),
     ("stone", ["st"]),
     ("stop", ["colon","pt"]),
     ("straight line", ["i"]),
     ("street", ["rue","st"]),
     ("strikebreaker", ["rat"]),
     ("string", ["g","d","a","e"]),
     ("strings", ["d","a","g"]),
     ("strong", ["f"]),
     ("student", ["l"]),
     ("students", ["nus"]),
     ("students union", ["nus"]),
     ("study", ["den","con"]),
     ("stumped", ["st"]),
     ("stunner", ["ko"]),
     ("submariner", ["nemo"]),
     ("substitute", ["sub"]),
     ("succeeded", ["s"]),
     ("success", ["go"]),
     ("suit", ["g"]),
     ("suitable for children", ["u"]),
     ("sulphur", ["s"]),
     ("sum", ["add"]),
     ("summer", ["bst"]),
     ("summer time", ["bst"]),
     ("sun", ["s","ra"]),
     ("sun god", ["ra"]),
     ("sun god", ["sol"]),
     ("sunday school", ["ss"]),
     ("superior", ["u","up"]),
     ("support", ["bra","leg"]),
     ("supposed force", ["od"]),
     ("surgeon", ["vet"]),
     ("sweden", ["s"]),
     ("sweetheart", ["jo"]),
     ("swindle", ["con"]),
     ("switzerland", ["ch"]),
     ("take", ["r","rec"]),
     ("tales", ["ana"]),
     ("tanner", ["vid","vip"]),
     ("tanzania", ["eat"]),
     ("tap", ["h","c"]),
     ("tar", ["ab"]),
     ("tau", ["t"]),
     ("tax", ["scot","vat"]),
     ("tax officer", ["to"]),
     ("te", ["t"]),
     ("tea", ["cha","t"]),
     ("tea time", ["iv"]),
     ("teachers", ["nut"]),
     ("team", ["xv","xi","side"]),
     ("teas", ["ts","tt"]),
     ("tee", ["t","peg"]),
     ("teepee", ["tp"]),
     ("tees", ["ts","tt"]),
     ("teetotal", ["tt"]),
     ("teetotaller", ["tt"]),
     ("telepathy", ["esp"]),
     ("ten", ["io","x"]),
     ("ten thousand", ["x"]),
     ("tenor", ["t"]),
     ("terriers", ["ta"]),
     ("territorial army", ["ta"]),
     ("territorials", ["ta"]),
     ("terrorists", ["ira","plo","provos","eta"]),
     ("tesla", ["t"]),
     ("test", ["oral","mot"]),
     ("text", ["ms"]),
     ("thailand", ["t"]),
     ("thank you", ["ta","tt"]),
     ("thanks", ["ta"]),
     ("that", ["yt","id"]),
     ("that is", ["ie","sc"]),
     ("thats", ["ie"]),
     ("the", ["der","el","t","la","die","ye","das","le","il"]),
     ("the french", ["le","la","les"]),
     ("the german", ["die","der", "das"]),
     ("the italian", ["il","la"]),
     ("the greatest", ["ali"]),
     ("the man", ["he"]),
     ("the pope", ["hh"]),
     ("the same", ["do"]),
     ("the spanish", ["la","el","los"]),
     ("the thing", ["it","play"]),
     ("the woman", ["she"]),
     ("the womans", ["her"]),
     ("them", ["em"]),
     ("theologian", ["bd","dd"]),
     ("theory", ["ism"]),
     ("therefore", ["so"]),
     ("third man", ["abel"]),
     ("thirty seconds", ["min"]),
     ("this", ["hic","cet","ce"]),
     ("this country", ["uk"]),
     ("this era", ["ad"]),
     ("this island", ["uk"]),
     ("this month", ["inst"]),
     ("this year", ["ha"]),
     ("thoroughfare", ["st"]),
     ("thousand", ["g","x","k","m"]),
     ("a thousand", ["g","x","k","m"]),
     ("three", ["tri","ter"]),
     ("three hundred", ["b"]),
     ("three thousand", ["b"]),
     ("three times a day", ["tid"]),
     ("thrice", ["tri","ter"]),
     ("through", ["per"]),
     ("thus", ["sic","so"]),
     ("time", ["t","eon","sec","mo","age"]),
     ("times", ["by","x"]),
     ("tin", ["sn"]),
     ("tinker", ["sly"]),
     ("to the", ["aux","ala","au"]),
     ("today", ["ad"]),
     ("ton", ["t"]),
     ("tonne", ["t"]),
     ("torpedo boat", ["tb","mtb"]),
     ("tostis song", ["tata"]),
     ("tot", ["add"]),
     ("touching", ["re"]),
     ("track", ["y"]),
     ("tradesmen", ["tu"]),
     ("traffic signal", ["go","stop"]),
     ("trainee", ["l"]),
     ("training", ["pt","pe"]),
     ("trains", ["br"]),
     ("tramp", ["hobo"]),
     ("transaction", ["tr"]),
     ("transatlantic", ["us"]),
     ("translation", ["tr"]),
     ("transport", ["rly","ry","br"]),
     ("trap", ["u"]),
     ("traveller", ["rom","rep"]),
     ("tree ring", ["mayo"]),
     ("trendy", ["in"]),
     ("tribe", ["dan","gad"]),
     ("trick", ["con"]),
     ("triple", ["tri","ter"]),
     ("tritium", ["t"]),
     ("triumphant cry", ["io"]),
     ("trivial sum", ["ip"]),
     ("troops", ["re"]),
     ("trouble", ["ail","ado"]),
     ("troy", ["t"]),
     ("tube", ["u"]),
     ("tuesday", ["t"]),
     ("tune", ["air"]),
     ("tungsten", ["w"]),
     ("turkey", ["tr"]),
     ("turn", ["u"]),
     ("twenty", ["k"]),
     ("twenty feet", ["rope"]),
     ("twenty thousand", ["k"]),
     ("twice", ["bis"]),
     ("twitching", ["tic"]),
     ("two", ["bi","ii","di","pr","bis"]),
     ("two hundred", ["h","cc"]),
     ("two hundred and fifty", ["k","e"]),
     ("two hundred and fifty thousand", ["e"]),
     ("two hundred thousand", ["h"]),
     ("tyneside", ["ne"]),
     ("tyro", ["l"]),
     ("u boat", ["sub"]),
     ("ulster", ["ni"]),
     ("un", ["an","i","a"]),
     ("uncle", ["pawnbroker","eme","sam"]),
     ("undergarment", ["bra"]),
     ("undersecretary", ["us"]),
     ("understood", ["ment"]),
     ("underworld", ["dis"]),
     ("undivided", ["one"]),
     ("unfavourable aspect", ["n"]),
     ("unidentified", ["nu"]),
     ("union", ["u"]),
     ("unionist", ["u"]),
     ("unit", ["i","a"]),
     ("united kingdom", ["uk"]),
     ("united nations", ["un"]),
     ("universal", ["u"]),
     ("universal set", ["e"]),
     ("university", ["u"]),
     ("university teacher", ["don"]),
     ("unknown", ["x","z","y"]),
     ("unknown number", ["n"]),
     ("unlimited number", ["n"]),
     ("unpaid", ["hon"]),
     ("unservicable", ["us"]),
     ("unwell", ["ill"]),
     ("upper class", ["u"]),
     ("uppish", ["u"]),
     ("upright", ["i","pi"]),
     ("upsilon", ["u"]),
     ("uranium", ["u"]),
     ("uruguay", ["uru","u"]),
     ("us", ["s"]),
     ("use", ["uu","us"]),
     ("used", ["sh"]),
     ("useless", ["us"]),
     ("utah", ["u"]),
     ("vacant", ["e"]),
     ("vanadium", ["v"]),
     ("various years", ["vy"]),
     ("Vatican", ["v"]),
     ("vee", ["v"]),
     ("velocity", ["v"]),
     ("verb", ["vb","v"]),
     ("verse", ["v"]),
     ("versus", ["v"]),
     ("very", ["tres","unco","v"]),
     ("very black", ["bb"]),
     ("very hard", ["hh"]),
     ("very large", ["os"]),
     ("very loud", ["ff"]),
     ("very quiet", ["pp"]),
     ("very softly", ["pp"]),
     ("very strong", ["ff"]),
     ("vestment", ["alb"]),
     ("vicar", ["rev"]),
     ("victory", ["vj","v","ve"]),
     ("vide", ["v"]),
     ("violin string", ["a","e","g","d"]),
     ("violin strings", ["g","e"]),
     ("Virginia", ["va"]),
     ("viscount", ["vis"]),
     ("vitamin", ["h","k","bi","f","p","b","a","l","c","m","d","e","x"]),
     ("viz", ["sc"]),
     ("volt", ["v"]),
     ("volume", ["v","vol"]),
     ("volunteers", ["ta"]),
     ("vote", ["x"]),
     ("wall", ["mur"]),
     ("wander", ["err"]),
     ("warrant officer", ["rsm"]),
     ("warship", ["sub"]),
     ("washington", ["dc"]),
     ("water", ["ea","aq"]),
     ("waterfall", ["rain"]),
     ("watt", ["w"]),
     ("way", ["rly","ry","rd","st","ave"]),
     ("way of working", ["mo"]),
     ("weak", ["w"]),
     ("wearing", ["in"]),
     ("wednesday", ["w"]),
     ("week", ["w"]),
     ("weight", ["g","oz","ton","gr","st","ct","wt"]),
     ("well", ["so"]),
     ("welsh", ["w"]),
     ("west", ["w"]),
     ("west indies", ["wi"]),
     ("western", ["w"]),
     ("westminster", ["wi"]),
     ("whales", ["gam"]),
     ("what", ["que"]),
     ("when", ["as"]),
     ("who", ["qui"]),
     ("whole numbers", ["w"]),
     ("why", ["y"]),
     ("wicket", ["w"]),
     ("width", ["w"]),
     ("wife", ["ux","rib","dutch","w"]),
     ("will", ["ill","to"]),
     ("william", ["w"]),
     ("win", ["v"]),
     ("wings", ["ala"]),
     ("winner", ["ace"]),
     ("wise", ["ys","yy"]),
     ("witchcraft", ["obi"]),
     ("with", ["con"]),
     ("without", ["sin","sine"]),
     ("without a day fixed", ["sd"]),
     ("without children", ["sp"]),
     ("without date", ["sa"]),
     ("wizard place", ["oz"]),
     ("woman", ["f","w"]),
     ("work", ["op"]),
     ("wreath", ["lei"]),
     ("writer", ["pen","elia","nib"]),
     ("writing", ["r","ms"]),
     ("wrong", ["sin"]),
     ("wrong sign", ["x"]),
     ("xi", ["x"]),
     ("Xmas", ["x"]),
     ("yard", ["y"]),
     ("year", ["a","y","yr"]),
     ("year of reign", ["ar"]),
     ("yearly meeting", ["agm"]),
     ("yellow", ["or"]),
     ("yen", ["y"]),
     ("yes", ["ja","oui","si","da","ay","aye"]),
     ("yew", ["u"]),
     ("yews", ["uu","us"]),
     ("you", ["u","ye"]),
     ("you and i", ["us","we"]),
     ("you and me", ["us","we"]),
     ("you are", ["ur"]),
     ("you queue", ["uq"]),
     ("you see", ["uc"]),
     ("young", ["y"]),
     ("young sheep", ["teg"]),
     ("your", ["yr"]),
     ("yours truly", ["i"]),
     ("youth leaders", ["ys","wise"]),
     ("yttrium", ["y"]),
     ("zaire", ["zr"]),
     ("zambia", ["z"]),
     ("zed", ["z"]),
     ("zee", ["z"]),
     ("zero", ["z","o"]),
     ("zeta", ["z"])]

------ HOMOPHONES ------

homophones s
  = fromMaybe [] (Map.lookup s homophoneTable)

homophoneTable
  = Map.fromList (Prelude.concatMap makeMap homophonesRaw)
  where
    makeMap xs = [(k, xs Data.List.\\ [k]) | k <- xs]

homophonesRaw
  = [["accessary", "accessory"],
  ["ad", "add"],
  ["ail", "ale"],
  ["air", "heir"],
  ["aisle", "ill", "isle"],
  ["all", "awl"],
  ["allowed", "aloud"],
  ["alms", "arms"],
  ["altar", "alter"],
  ["arc", "ark"],
  ["are", "ah", "r"],
  ["arent", "aunt"],
  ["ate", "eight"],
  ["auger", "augur"],
  ["auk", "orc"],
  ["aural", "oral"],
  ["away", "aweigh"],
  ["awe", "oar", "or", "ore"],
  ["axel", "axle"],
  ["aye", "eye", "i"],
  ["bail", "bale"],
  ["bait", "bate"],
  ["baize", "bays"],
  ["bald", "bawled"],
  ["ball", "bawl"],
  ["band", "banned"],
  ["bard", "barred"],
  ["bare", "bear"],
  ["bark", "barque"],
  ["baron", "barren"],
  ["base", "bass"],
  ["bay", "bey"],
  ["bazaar", "bizarre"],
  ["be", "bee", "b"],
  ["beach", "beech"],
  ["bean", "been"],
  ["beat", "beet"],
  ["beau", "bow"],
  ["beer", "bier"],
  ["bel", "bell", "belle"],
  ["burn", "bern"],
  ["berry", "bury"],
  ["berth", "birth"],
  ["bight", "bite", "byte"],
  ["billed", "build"],
  ["bitten", "bittern"],
  ["blew", "blue"],
  ["bloc", "block"],
  ["boar", "bore"],
  ["board", "bored"],
  ["boarder", "border"],
  ["bold", "bowled"],
  ["boos", "booze"],
  ["born", "borne"],
  ["bough", "bow"],
  ["boy", "buoy"],
  ["brae", "bray"],
  ["braid", "brayed"],
  ["braise", "brays", "braze"],
  ["brake", "break"],
  ["bread", "bred"],
  ["brews", "bruise"],
  ["bridal", "bridle"],
  ["broach", "brooch"],
  ["bur", "burr"],
  ["but", "butt"],
  ["buy", "by", "bye"],
  ["buyer", "byre"],
  ["calendar", "calender"],
  ["call", "caul"],
  ["canvas", "canvass"],
  ["cast", "caste"],
  ["caster", "castor"],
  ["caught", "court"],
  ["caw", "core", "corps"],
  ["cede", "seed"],
  ["ceiling", "sealing"],
  ["cell", "sell"],
  ["censer", "censor", "sensor"],
  ["cent", "scent", "sent"],
  ["cereal", "serial"],
  ["cheap", "cheep"],
  ["check", "cheque"],
  ["choir", "quire"],
  ["chord", "cord"],
  ["cite", "sight", "site"],
  ["clack", "claque"],
  ["clew", "clue"],
  ["climb", "clime"],
  ["close", "cloze"],
  ["coal", "kohl"],
  ["coarse", "course"],
  ["coign", "coin"],
  ["colonel", "kernel"],
  ["complacent", "complaisant"],
  ["complement", "compliment"],
  ["coo", "coup"],
  ["cops", "copse"],
  ["council", "counsel"],
  ["cousin", "cozen"],
  ["creak", "creek"],
  ["crews", "cruise"],
  ["cue", "kyu", "queue"],
  ["curb", "kerb"],
  ["currant", "current"],
  ["cymbol", "symbol"],
  ["dam", "damn"],
  ["days", "daze"],
  ["dear", "deer"],
  ["dee", "d"],
  ["descent", "dissent"],
  ["desert", "dessert"],
  ["deviser", "divisor"],
  ["dew", "due"],
  ["die", "dye"],
  ["discreet", "discrete"],
  ["dissent", "descent", "decent"],
  ["doe", "doh", "dough"],
  ["done", "dun"],
  ["douse", "dowse"],
  ["draft", "draught"],
  ["dual", "duel"],
  ["earn", "urn"],
  ["eery", "eyrie"],
  ["ewe", "yew", "you"],
  ["ex", "x"],
  ["faint", "feint"],
  ["fah", "far"],
  ["fair", "fare"],
  ["farther", "father"],
  ["fate", "fête"],
  ["faun", "fawn"],
  ["fay", "fey"],
  ["faze", "phase"],
  ["feat", "feet"],
  ["ferrule", "ferule"],
  ["few", "phew"],
  ["fie", "phi"],
  ["file", "phial"],
  ["find", "fined"],
  ["fir", "fur"],
  ["fizz", "phiz"],
  ["flair", "flare"],
  ["flaw", "floor"],
  ["flea", "flee"],
  ["flex", "flecks"],
  ["flew", "flu", "flue"],
  ["floe", "flow"],
  ["flour", "flower"],
  ["foaled", "fold"],
  ["for", "fore", "four"],
  ["foreword", "forward"],
  ["fort", "fought"],
  ["forth", "fourth"],
  ["foul", "fowl"],
  ["franc", "frank"],
  ["freeze", "frieze"],
  ["friar", "fryer"],
  ["furs", "furze"],
  ["gait", "gate"],
  ["galipot", "gallipot"],
  ["gallop", "galop"],
  ["gamble", "gambol"],
  ["gays", "gaze"],
  ["gee", "g"],
  ["genes", "jeans"],
  ["gild", "guild"],
  ["gilt", "guilt"],
  ["giro", "gyro"],
  ["gnaw", "nor"],
  ["gneiss", "nice"],
  ["gorilla", "guerilla"],
  ["grate", "great"],
  ["greave", "grieve"],
  ["greys", "graze"],
  ["grisly", "grizzly"],
  ["groan", "grown"],
  ["guessed", "guest"],
  ["hail", "hale"],
  ["hair", "hare"],
  ["hall", "haul"],
  ["hangar", "hanger"],
  ["hart", "heart"],
  ["haw", "hoar", "whore"],
  ["hay", "hey"],
  ["heal", "heel", "hell"],
  ["hear", "here"],
  ["heard", "herd"],
  ["hed", "heed"],
  ["heroin", "heroine"],
  ["hew", "hue"],
  ["hi", "high"],
  ["higher", "hire"],
  ["him", "hymn"],
  ["ho", "hoe"],
  ["hoard", "horde"],
  ["hoarse", "horse"],
  ["holey", "holy", "wholly"],
  ["hour", "our"],
  ["idle", "idol"],
  ["in", "inn"],
  ["indict", "indite"],
  ["its", "its"],
  ["jay", "j"],
  ["jewel", "joule"],
  ["key", "quay"],
  ["knave", "nave"],
  ["knead", "need"],
  ["knew", "new"],
  ["knight", "night"],
  ["knit", "nit"],
  ["knob", "nob"],
  ["knock", "nock"],
  ["knot", "not"],
  ["know", "no"],
  ["knows", "nose"],
  ["laager", "lager"],
  ["lac", "lack"],
  ["lade", "laid"],
  ["lain", "lane"],
  ["lam", "lamb"],
  ["laps", "lapse"],
  ["larva", "lava"],
  ["lase", "laze"],
  ["law", "lore"],
  ["lay", "ley"],
  ["lea", "lee"],
  ["leach", "leech"],
  ["lead", "led"],
  ["leak", "leek"],
  ["lean", "lien"],
  ["lessen", "lesson"],
  ["levee", "levy"],
  ["liar", "lyre"],
  ["licence", "license"],
  ["licker", "liquor"],
  ["lie", "lye"],
  ["lieu", "loo"],
  ["links", "lynx"],
  ["lo", "low"],
  ["load", "lode"],
  ["loan", "lone"],
  ["locks", "lox"],
  ["loop", "loupe"],
  ["loot", "lute"],
  ["made", "maid"],
  ["mail", "male"],
  ["main", "mane"],
  ["maize", "maze"],
  ["mall", "maul"],
  ["manna", "manner"],
  ["mantel", "mantle"],
  ["mare", "mayor"],
  ["mark", "marque"],
  ["marshal", "martial"],
  ["marten", "martin"],
  ["mask", "masque"],
  ["maw", "more"],
  ["me", "mi"],
  ["mean", "mien"],
  ["meat", "meet", "mete"],
  ["medal", "meddle"],
  ["metal", "mettle"],
  ["meter", "metre"],
  ["might", "mite"],
  ["miner", "minor", "mynah"],
  ["mind", "mined"],
  ["missed", "mist"],
  ["moat", "mote"],
  ["mode", "mowed"],
  ["moor", "more"],
  ["moose", "mousse"],
  ["morning", "mourning"],
  ["muscle", "mussel"],
  ["naval", "navel"],
  ["nay", "neigh"],
  ["nigh", "nye"],
  ["none", "nun"],
  ["od", "odd"],
  ["ode", "owed"],
  ["oh", "owe"],
  ["one", "won"],
  ["packed", "pact"],
  ["packs", "pax"],
  ["pail", "pale"],
  ["pain", "pane"],
  ["pair", "pare", "pear"],
  ["palate", "palette", "pallet"],
  ["pascal", "paschal"],
  ["paten", "patten", "pattern"],
  ["pause", "paws", "pores", "pours"],
  ["pawn", "porn"],
  ["pea", "pee", "p"],
  ["peace", "piece"],
  ["peak", "peek", "peke", "pique"],
  ["peal", "peel"],
  ["pearl", "purl"],
  ["pedal", "peddle"],
  ["peer", "pier"],
  ["pi", "pie"],
  ["pica", "pika"],
  ["place", "plaice"],
  ["plain", "plane"],
  ["pleas", "please"],
  ["plum", "plumb"],
  ["pole", "poll"],
  ["poof", "pouffe"],
  ["practice", "practise"],
  ["praise", "prays", "preys"],
  ["principal", "principle"],
  ["profit", "prophet"],
  ["quarts", "quartz"],
  ["quean", "queen"],
  ["queue", "q"],
  ["rain", "reign", "rein"],
  ["raise", "rays", "raze"],
  ["rap", "wrap"],
  ["raw", "roar"],
  ["read", "reed"],
  ["read", "red"],
  ["real", "reel"],
  ["reek", "wreak"],
  ["rest", "wrest"],
  ["retch", "wretch"],
  ["review", "revue"],
  ["rheum", "room"],
  ["right", "rite", "wright", "write"],
  ["ring", "wring"],
  ["road", "rode"],
  ["roe", "row"],
  ["role", "roll"],
  ["roo", "roux", "rue"],
  ["rood", "rude"],
  ["root", "route"],
  ["rose", "rows"],
  ["rota", "rotor"],
  ["rote", "wrote"],
  ["rough", "ruff"],
  ["rouse", "rows"],
  ["rung", "wrung"],
  ["rye", "wry"],
  ["saver", "savour"],
  ["spade", "spayed"],
  ["sale", "sail"],
  ["sane", "seine"],
  ["satire", "satyr"],
  ["sauce", "source"],
  ["saw", "soar", "sore"],
  ["scene", "seen"],
  ["scull", "skull"],
  ["sea", "see", "c"],
  ["seam", "seem"],
  ["sear", "seer", "sere"],
  ["seas", "sees", "seize"],
  ["sew", "so", "sow"],
  ["shake", "sheikh"],
  ["shear", "sheer"],
  ["shoe", "shoo"],
  ["sic", "sick"],
  ["side", "sighed"],
  ["sign", "sine"],
  ["sink", "synch"],
  ["slay", "sleigh"],
  ["sloe", "slow"],
  ["sole", "soul"],
  ["some", "sum"],
  ["son", "sun"],
  ["sort", "sought"],
  ["spa", "spar"],
  ["staid", "stayed"],
  ["stair", "stare"],
  ["stake", "steak"],
  ["stalk", "stork"],
  ["stationary", "stationery"],
  ["steal", "steel"],
  ["stile", "style"],
  ["storey", "story"],
  ["straight", "strait"],
  ["sweet", "suite"],
  ["swat", "swot"],
  ["tacks", "tax"],
  ["tale", "tail"],
  ["talk", "torque"],
  ["tare", "tear"],
  ["taught", "taut", "tort"],
  ["te", "tea", "tee", "t"],
  ["team", "teem"],
  ["tear", "tier"],
  ["teas", "tease"],
  ["terce", "terse"],
  ["tern", "turn"],
  ["there", "their", "theyre"],
  ["threw", "through"],
  ["throes", "throws"],
  ["throne", "thrown"],
  ["thyme", "time"],
  ["tic", "tick"],
  ["tide", "tied"],
  ["tire", "tyre"],
  ["to", "too", "two"],
  ["toad", "toed", "towed"],
  ["told", "tolled"],
  ["tole", "toll"],
  ["ton", "tun"],
  ["tor", "tore"],
  ["tough", "tuff"],
  ["troop", "troupe"],
  ["tuba", "tuber"],
  ["vain", "vane", "vein"],
  ["vale", "veil"],
  ["vial", "vile"],
  ["wail", "wale", "whale"],
  ["wain", "wane"],
  ["waist", "waste"],
  ["wait", "weight"],
  ["waive", "wave"],
  ["wall", "waul"],
  ["war", "wore"],
  ["ware", "wear", "where"],
  ["warn", "worn"],
  ["wart", "wort"],
  ["watt", "what"],
  ["wax", "whacks"],
  ["way", "weigh", "whey"],
  ["we", "wee", "whee"],
  ["weak", "week"],
  ["wed", "weed"],
  ["weal", "well", "wheel"],
  ["wean", "ween"],
  ["weather", "whether"],
  ["weaver", "weever"],
  ["weir", "were"],
  ["were", "whirr"],
  ["wet", "whet"],
  ["wheald", "wheeled"],
  ["which", "witch"],
  ["whig", "wig"],
  ["while", "wile"],
  ["whine", "wine"],
  ["whirl", "whorl"],
  ["whirled", "world"],
  ["whit", "wit"],
  ["white", "wight"],
  ["whos", "whose"],
  ["woe", "whoa"],
  ["wood", "would"],
  ["why", "y"],
  ["yaw", "yore", "your", "youre"],
  ["yoke", "yolk"],
  ["you", "u"],
  ["youll", "yule"]]


----- EXTERNAL WORDLISTS -----

read_malenames = do
    ls <- fmap Text.lines (Text.readFile "data/malenames")
    (return . Set.fromList . string_read . toString . Text.toLower . Prelude.head) ls

temp_malenames = unsafePerformIO $ do read_malenames
output_malenames = encodeFile "malenames.bin" temp_malenames

read_bytes_malenames :: IO (Set.Set String)
read_bytes_malenames = do
    return . decode =<< BS.readFile "malenames.bin"

maleNames
  = trace "Male names..." (unsafePerformIO $ do read_bytes_malenames)

read_femalenames = do
    ls <- fmap Text.lines (Text.readFile "data/femalenames")
    (return . Set.fromList . string_read . toString . Text.toLower . Prelude.head) ls

temp_femalenames = unsafePerformIO $ do read_femalenames
output_femalenames = encodeFile "femalenames.bin" temp_femalenames

read_bytes_femalenames :: IO (Set.Set String)
read_bytes_femalenames = do
    return . decode =<< BS.readFile "femalenames.bin"

femaleNames
  = trace "Female names" (unsafePerformIO $ do read_bytes_femalenames)

read_wordlist = do
    ls <- fmap Text.lines (Text.readFile "data/straight-wordlist")
    (return . Set.fromList . string_read . toString . Prelude.head) ls

temp_wordlist = unsafePerformIO $ do read_wordlist
output_wordlist = encodeFile "wordlist.bin" temp_wordlist

read_bytes_wordlist :: IO (Set.Set String)
read_bytes_wordlist = do
    return . decode =<< BS.readFile "wordlist.bin"

wordlist
  = trace "Word list..." (unsafePerformIO $ do read_bytes_wordlist)

-- Need foldl' to avoid stack overflow...
sortedWordlist
  = trace "Sorted word map..." (Map.fromList (foldl' f [("",[])] ps))
  where
    ps = sortBy (\x y -> compare (fst x) (fst y))
                (Prelude.map makeEl (Set.elems allWords))
    makeEl w = (sort w, w)

f acc@((cs', ws) : m) (cs, w)
  | cs == cs' = (cs', w : ws) : m
  | otherwise = (cs, [w]) : acc

-- THESAURUS

read_thesaurus = do
    ls <- fmap Text.lines (Text.readFile "data/thesaurus-list")
    (return . Map.fromList . map_read . toString . Prelude.head) ls
  where
    f = Prelude.map Ch.toLower

temp_thesaurus = unsafePerformIO $ do read_thesaurus
output_thesaurus = encodeFile "thesaurus.bin" temp_thesaurus

read_bytes_thesaurus :: IO (Map.Map String [Int])
read_bytes_thesaurus = do
    return . decode =<< BS.readFile "thesaurus.bin"

thesaurus :: Map.Map String [Int]
thesaurus
  = trace "Thesaurus..." (unsafePerformIO $ do read_bytes_thesaurus)

-- KEYS

read_keys = do
    ls <- fmap Text.lines (Text.readFile "data/thesaurus-list-keys")
    (return . makeArray . string_read . toString . Prelude.head) ls

temp_keys = unsafePerformIO $ do read_keys
output_keys = encodeFile "keys.bin" temp_keys

read_bytes_keys :: IO (Array Int String)
read_bytes_keys = do
    return . decode =<< BS.readFile "keys.bin"

keys
  = trace "Keys..." (unsafePerformIO $ do read_bytes_keys)

-- Stuff...

makeArray :: [String] -> Array Int String
makeArray ss = listArray (0, (Prelude.length ss) - 1) ss

toString = Text.unpack

map_read :: String -> [(String, [Int])]
map_read = read

string_read :: String -> [String]
string_read = read


------ WORD LOOKUP ------

-- Note: some words in the manual list may not be in the databases, so
-- we need to add them.
allWords
  = foldr1 Set.union [Set.fromList (Map.keys thesaurus),
                      Set.fromList manualAdditions,
                      wordlist,
                      maleNames,
                      femaleNames]
  where
    manualAdditions = map fst manualSynonyms ++ concatMap snd manualSynonyms

isInWordlist w
  = Set.member w allWords

------ PREFIXES ------

allPrefixes
  = trace "Prefixes..." (HashSet.fromList (Prelude.concatMap prefixes (Set.elems allWords)))

isPrefix s
  = HashSet.member s allPrefixes

------ SUFFIXES ------

allSuffixes
  = trace "Suffixes..." (HashSet.fromList (Prelude.concatMap suffixes (Set.elems allWords)))

isSuffix s
  = HashSet.member s allSuffixes
