module Indicators where

import qualified Data.Set as Set
import Stemmer
import Data.List

-- Noise words are removed completely from the indicators lists and from
-- the text being tested.
-- The words in Ind1 count as indicators in their own right but also
-- count as components (qualifiers, adverbs...) of longer indicators
-- made from each of a. noise words, b. Ind1 words and c. Ind2 words.
-- E.g. "in a terrible mess".
-- It's not perfect, e.g. f "in" is in Ind1 and "found in" is in Ind2
-- then "found" seen as a 'removeEnds' indicator even though it's
-- missing the "in" - a false positive. We might code it this was to
-- catch also "found within", "found inside"..., in order to avoid false
-- negatives.


-- All of these will be stemmed and Ind2 will be pruned
-- (Ind2 --> Ind2 - Noise - Ind1) before being used.

defNoise
  = ["it",
     "up",
     "we",
     "may",
     "might"]

defInd1
  = ["and",
     "is",
     "a",
     "after",
     "and",
     "its",
     "it's",
     "as",
     "at",
     "been",
     "being",
     "caused by",
     "by",
     "can",
     "come",
     "does",
     "from",
     "has",
     "have",
     "get",
     "got",
     "if",
     "in",
     "let",
     "like",
     "on",
     "of",
     "see",
     "seen",
     "sees",
     "so",
     "take",
     "that",
     "the",
     "they",
     "to",
     "was",
     "when",
     "with"]

defInd2
  = ["became",
     "be",
     "become",
     "brings",
     "caused by",
     "come",
     "for",
     "get",
     "give",
     "gives",
     "giving",
     "lead",
     "made",
     "make",
     "makes",
     "need",
     "obtain",
     "to get to",
     "or",
     "produces",
     "revealing",
     "causing",
     "having",
     "exposes",
     "reveals",
     "may reveal",
     "see",
     "seen",
     "show",
     "provide",
     "yield"]

anagramNoise
  = ["a",
     "after",
     "all",
     "an",
     "by",
     "for",
     "from",
     "gay",
     "go",
     "goes",
     "going",
     "gone",
     "in",
     "is",
     "of",
     "the",
     "up",
     "was",
     "with"]

anagramInd1
  = ["about",
     "abnormal",
     "awful",
     "bad",
     "change",
     "disorder",
     "frightful",
     "ghastly",
     "horrible",
     "ill",
     "incredible",
     "nasty",
     "order",
     "riotous",
     "rough",
     "sad",
     "strange",
     "poor",
     "terrible",
     "out"]

anagramInd2
  = anagramIndicatorsL ++ anagramIndicatorsR

anagramIndicatorsL
  = ["byzantine",
     "machiavellian",
     "abandon",
     "abandoned",
     "aberrated",
     "aberration",
     "aberrations",
     "abnormal",
     "abnormally",
     "abominable",
     "about",
     "abroad",
     "abstract",
     "absurd",
     "abuse",
     "abused",
     "abysmal",
     "accident",
     "acrobatics",
     "action",
     "active",
     "adapt",
     "adapted",
     "addled",
     "adjust",
     "adjusted",
     "administer",
     "ado",
     "adrift",
     "adulterate",
     "adverse",
     "affect",
     "affected",
     "afflict",
     "afresh",
     "after a fashion",
     "aggravate",
     "aggrieve",
     "agile",
     "agitate",
     "agitated",
     "ail",
     "alien",
     "all over the place",
     "alter",
     "altered",
     "alternative",
     "amazing",
     "amend",
     "amended",
     "amendment",
     "amiss",
     "amok",
     "amorphous",
     "amuse",
     "analysis",
     "anarchic",
     "anew",
     "angry",
     "state of anger",
     "animated",
     "annoy",
     "anomalous",
     "anomaly",
     "another",
     "antagonize",
     "antic",
     "anxious",
     "anyhow",
     "anyway",
     "approximate",
     "arbitrary",
     "architecture",
     "around",
     "arouse",
     "arrange",
     "arrangement",
     "art",
     "artful",
     "artifice",
     "askew",
     "assault",
     "assemble",
     "assembled",
     "assort",
     "assorted",
     "astray",
     "at odds",
     "at random",
     "at sea",
     "at sixes and sevens",
     "atrocious",
     "attack",
     "attempt",
     "atypical",
     "awful",
     "awkward",
     "awry",
     "babble",
     "bad",
     "badly",
     "baffle",
     "baffled",
     "bake",
     "ballet",
     "bananas",
     "barking",
     "basketcase",
     "bastardization",
     "bats",
     "battered",
     "battle",
     "batty",
     "beat",
     "beaten",
     "beaten up",
     "become",
     "bedlam",
     "befuddle",
     "belted",
     "bend",
     "bendy",
     "bent",
     "berserk",
     "bespoke",
     "bewilder",
     "bicker",
     "bits",
     "bizarre",
     "blast",
     "blasted",
     "blazing",
     "blend",
     "blighted",
     "blithering",
     "blotto",
     "blow",
     "blown up",
     "blunder",
     "bluster",
     "bob",
     "boil",
     "boiled",
     "boisterous",
     "bomb",
     "booby",
     "boozy",
     "botch",
     "bother",
     "bounce",
     "bound",
     "bow",
     "box",
     "brawl",
     "breach",
     "break",
     "break up",
     "breeze",
     "brew",
     "brewed",
     "broach",
     "broadcast",
     "broken",
     "broth",
     "buckle",
     "buckled",
     "budge",
     "buffalo",
     "buffet",
     "build",
     "building",
     "built",
     "bully",
     "bump",
     "bungle",
     "bungled",
     "burst",
     "bust",
     "bustle",
     "bustling",
     "busy",
     "butcher",
     "by arrangement",
     "by mistake",
     "calamity",
     "camouflage",
     "can be",
     "caper",
     "caprice",
     "career",
     "careless",
     "carry on",
     "carve",
     "carved up",
     "cast",
     "casual",
     "cause",
     "cavalier",
     "cavort",
     "cavorting",
     "change",
     "changed",
     "changes shape",
     "changing",
     "chaotic",
     "characters",
     "chemistry",
     "chew",
     "chop",
     "chopped up",
     "choppy",
     "chuck",
     "churn",
     "circulate",
     "circulated",
     "circus",
     "clash",
     "clever",
     "clobber",
     "cloud",
     "clumsy",
     "coarse",
     "cockup",
     "cock up",
     "cocktail",
     "code",
     "collage",
     "collapse",
     "collate",
     "collect",
     "comedy",
     "comical",
     "commotion",
     "compilation",
     "compile",
     "complex",
     "complicate",
     "complicated",
     "compose",
     "composition",
     "compound",
     "comprising",
     "compromise",
     "concealed",
     "conceive",
     "concoct",
     "concoction",
     "confection",
     "configure",
     "conflict",
     "confound",
     "confuse",
     "confused",
     "constituents",
     "construction",
     "construe",
     "contentious",
     "contort",
     "contorted",
     "contradict",
     "contrary",
     "contrast",
     "contrive",
     "contrived",
     "controversy",
     "conversion",
     "convert",
     "converted",
     "converts",
     "convolute",
     "convoluted",
     "convulse",
     "convulsing",
     "cook",
     "cooked",
     "corked",
     "correct",
     "correction",
     "corrupt",
     "could be",
     "counterfeit",
     "cower",
     "crack",
     "cracked",
     "cracked up",
     "crackers",
     "craftily",
     "crafty",
     "cranky",
     "crash",
     "crashed",
     "crazy",
     "create",
     "creep",
     "crime",
     "criminal",
     "cripple",
     "crisis",
     "crooked",
     "crude",
     "crumble",
     "crumbly",
     "crush",
     "crushed",
     "cryptic",
     "cuckoo",
     "cultivate",
     "culture",
     "cunning",
     "cunningly",
     "curdle",
     "cure",
     "curious",
     "cut and paste",
     "daft",
     "damage",
     "damaged",
     "dance",
     "dancing",
     "dash",
     "dashing",
     "deal",
     "debacle",
     "debauch",
     "debris",
     "decadent",
     "decay",
     "deceive",
     "decipher",
     "decline",
     "decode",
     "decompose",
     "deconstruct",
     "defective",
     "deform",
     "deformed",
     "degenerate",
     "delinquent",
     "delirious",
     "delude",
     "demented",
     "demolish",
     "deplorable",
     "deploy",
     "deployed",
     "deprave",
     "derange",
     "deranged",
     "derelict",
     "derive",
     "derived from",
     "describe",
     "design",
     "despair",
     "desperate",
     "destroy",
     "destroyed",
     "destruction",
     "desultory",
     "deteriorate",
     "devastate",
     "devastated",
     "develop",
     "developed",
     "deviant",
     "deviate",
     "devilish",
     "devious",
     "diabolical",
     "dicky",
     "different",
     "difficult",
     "digress",
     "dilapidated",
     "dilemma",
     "dire",
     "disarray",
     "disaster",
     "discomfort",
     "discompose",
     "disconcert",
     "discord",
     "disease",
     "disengage",
     "disfigure",
     "disfigured",
     "disgrace",
     "disgruntled",
     "disguise",
     "disguised",
     "dished out",
     "dishevelled",
     "disingenuous",
     "disintegrating",
     "disjoint",
     "disjointed",
     "dislocate",
     "dislocated",
     "dislodge",
     "dismantle",
     "dismantled",
     "dismember",
     "disobey",
     "disorder",
     "disorderly",
     "disorganised",
     "disorganized",
     "disorientated",
     "disperse",
     "dispersed",
     "displace",
     "display",
     "dispose",
     "disposed",
     "dispute",
     "disrepair",
     "disrupt",
     "disrupted",
     "dissect",
     "disseminated",
     "dissipate",
     "dissolute",
     "dissolve",
     "distilled",
     "distort",
     "distorted",
     "distract",
     "distraught",
     "distress",
     "distressed",
     "distribute",
     "distributed",
     "distribution",
     "disturb",
     "disturbance",
     "after disturbance",
     "disturbed",
     "dither",
     "diverse",
     "divert",
     "dizzy",
     "doctor",
     "doddery",
     "dodge",
     "dodgy",
     "done",
     "dotty",
     "doubt",
     "drag",
     "dreadful",
     "dress",
     "dressed",
     "drift",
     "drifting",
     "drive",
     "drunk",
     "dubious",
     "dud",
     "duff",
     "dynamic",
     "easily",
     "eccentric",
     "eccentried",
     "ecstasy",
     "edgy",
     "edit",
     "elaborate",
     "elastic",
     "else",
     "embroidered",
     "embroil",
     "emendation",
     "emerge",
     "energy",
     "engage",
     "engendering",
     "engineer",
     "enigma",
     "ensemble",
     "entangle",
     "entertain",
     "entwine",
     "equivocal",
     "err",
     "errant",
     "erratic",
     "erroneous",
     "erupt",
     "eruption",
     "evolution",
     "evolve",
     "exacerbate",
     "exceptional",
     "exchange",
     "exchanged",
     "excite",
     "excited",
     "excursion",
     "execute",
     "exercise",
     "exercising",
     "exotic",
     "expatiate",
     "explode",
     "exploit",
     "explosive",
     "extraordinary",
     "extravagant",
     "fabricated",
     "fail",
     "fake",
     "fall",
     "false",
     "falter",
     "fanatical",
     "fancy",
     "fantastic",
     "fantasy",
     "fashion",
     "fault",
     "faulty",
     "fermented",
     "fever",
     "fiasco",
     "fickle",
     "fiddle",
     "fiddled",
     "fidget",
     "fierce",
     "figures",
     "finesse",
     "fishy",
     "fitful",
     "fix",
     "fixed",
     "fizzy",
     "flailing",
     "flaky",
     "flap",
     "flaw",
     "flexible",
     "flexibly",
     "flicker",
     "flighty",
     "flimsy",
     "flirt",
     "flit",
     "floppy",
     "flounce",
     "flounder",
     "floundering",
     "flourish",
     "flow",
     "fluctuate",
     "fluid",
     "flurry",
     "fluster",
     "flustered",
     "flux",
     "fly",
     "flying",
     "fold",
     "foolish",
     "for a change",
     "for revision",
     "for wrestling",
     "forced",
     "foreign",
     "forge",
     "forged",
     "form",
     "formulate",
     "foul",
     "fracture",
     "fractured",
     "fragile",
     "fragment",
     "fragmented",
     "frantic",
     "freak",
     "freaking out",
     "free",
     "freely",
     "frenetic",
     "frenzied",
     "frenzy",
     "fresh",
     "freshly",
     "frightful",
     "frightfully",
     "frisky",
     "frivolous",
     "frolic",
     "frolicsome",
     "fuddled",
     "fudge",
     "funny",
     "furiously",
     "furore",
     "fury",
     "fuse",
     "fuss",
     "gad about",
     "gaffe",
     "gallivant",
     "gambol",
     "gangling",
     "garble",
     "garbled",
     "gauche",
     "gear",
     "generate",
     "generating",
     "germinate",
     "gets",
     "ghastly",
     "gibber",
     "giddily",
     "giddy",
     "giggle",
     "gingerly",
     "glide",
     "gnarl",
     "gnash",
     "go",
     "go off",
     "going crazy",
     "gone",
     "googly",
     "grapple",
     "grate",
     "grave",
     "grief",
     "grim",
     "grind",
     "groggy",
     "groomed",
     "gross",
     "grotesque",
     "ground",
     "group",
     "grow",
     "guise",
     "gyrate",
     "hack",
     "haggard",
     "hallucination",
     "hammer",
     "hammered",
     "handicraft",
     "handiwork",
     "handle",
     "haphazard",
     "harass",
     "harassed",
     "harm",
     "harmed",
     "harsh",
     "hash",
     "hatch",
     "havoc",
     "haywire",
     "hazard",
     "haze",
     "heave",
     "hectic",
     "helpless",
     "helter-skelter",
     "hesitant",
     "hideous",
     "higgledy-piggledy",
     "high",
     "hit",
     "hook",
     "hop",
     "horrible",
     "horribly",
     "horrid",
     "horrific",
     "horse around",
     "horseplay",
     "hotch-potch",
     "hotchpotch",
     "hover",
     "however",
     "hurl",
     "hurt",
     "hybrid",
     "hysteria",
     "idiosyncratic",
     "idiotic",
     "ill",
     "ill bred",
     "ill defined",
     "ill disposed",
     "ill formed",
     "ill treated",
     "illegal",
     "illicit",
     "illusion",
     "imagine",
     "impair",
     "impede",
     "imperfect",
     "impersonate",
     "impolitic",
     "impromptu",
     "improper",
     "improvise",
     "impure",
     "in a ferment",
     "in a jumble",
     "in a mess",
     "in a state",
     "in a way",
     "in a whirl",
     "in disarray",
     "in disguise",
     "in error",
     "in motion",
     "in pieces",
     "in resort",
     "in ruins",
     "in solution",
     "in violation",
     "inaccurate",
     "incoherent",
     "incompetent",
     "incongruous",
     "incorrect",
     "incredible",
     "indecent",
     "indefinite",
     "indirect",
     "indispose",
     "indistinct",
     "individual",
     "indulge",
     "inebriate",
     "inebriated",
     "inept",
     "inexact",
     "infirm",
     "informal",
     "ingenius",
     "ingredients",
     "injure",
     "injured",
     "inordinate",
     "inquietude",
     "insanely",
     "interfere",
     "interfered with",
     "interpret",
     "intoxicated",
     "intricate",
     "intrigue",
     "invalid",
     "invent",
     "invention",
     "involve",
     "involved",
     "irregular",
     "irresolute",
     "irritate",
     "irritated",
     "itch",
     "itinerant",
     "jam",
     "jar",
     "jargon",
     "jaunt",
     "jaunty",
     "jazz",
     "jazzy",
     "jerk",
     "jerky",
     "jib",
     "jiggle",
     "jiggling",
     "jitter",
     "jittery",
     "jive",
     "jockey",
     "joke",
     "jolly",
     "jolt",
     "jolting",
     "jostle",
     "jostling",
     "journey",
     "joust",
     "juddering",
     "juggle",
     "jumble",
     "jumbled",
     "jump",
     "jumping",
     "jungle",
     "junk",
     "just",
     "kick",
     "kind",
     "kind of",
     "kinematic",
     "kinetic",
     "kink",
     "kinky",
     "knead",
     "knit",
     "knock",
     "knocked about",
     "knocked out",
     "knot",
     "knotted",
     "labour",
     "laboured",
     "labyrinth",
     "labyrinthine",
     "lament",
     "languid",
     "lark",
     "latent",
     "latitude",
     "lawless",
     "lax",
     "lay",
     "laze",
     "leap",
     "legerdemain",
     "lenient",
     "liberal",
     "liberally",
     "licence",
     "limber",
     "liquid",
     "lissom",
     "lively",
     "loll",
     "loony",
     "loose",
     "loosely",
     "lost",
     "lounge",
     "lousy",
     "ludicrous",
     "lunatic",
     "lurch",
     "machinate",
     "mad",
     "made-up",
     "madness",
     "maelstrom",
     "magic",
     "make",
     "make changes",
     "make changes in",
     "make up",
     "malaise",
     "malcontent",
     "malformation",
     "malformed",
     "malfunction",
     "malicious",
     "malleable",
     "malleably",
     "maltreat",
     "maltreated",
     "manage",
     "managed",
     "mangle",
     "manic",
     "manipulate",
     "manoeuvre",
     "manufacture",
     "manufacturing",
     "mar",
     "marvel",
     "mash",
     "mashed",
     "masquerade",
     "massage",
     "masticate",
     "material",
     "matter",
     "maul",
     "maybe",
     "mayhem",
     "meandering",
     "meddle",
     "medley",
     "melange",
     "melee",
     "melodrama",
     "melt",
     "melted",
     "menace",
     "mend",
     "mental",
     "mercurial",
     "merry",
     "mesh",
     "mess",
     "messy",
     "metamorphosis",
     "might be",
     "migrate",
     "mince",
     "mingle",
     "mint",
     "misbehave",
     "misbehaves",
     "misbehaving",
     "mischief",
     "mischievously",
     "misconduct",
     "misconstrue",
     "misdirect",
     "miserable",
     "misery",
     "misfit",
     "misguided",
     "mishandle",
     "mishandled",
     "mishap",
     "mishmash",
     "misinterpret",
     "mislead",
     "mismanagement",
     "misplace",
     "misprint",
     "misrepresent",
     "misrepresented",
     "misshape",
     "misshapen",
     "misspell",
     "mistake",
     "mistreat",
     "misty",
     "misunderstand",
     "misuse",
     "mix",
     "mix-up",
     "mixed up",
     "mixture",
     "mobile",
     "mobilize",
     "model",
     "modelled",
     "moderate",
     "modification",
     "modify",
     "modulate",
     "mongrel",
     "monstrous",
     "motion",
     "motive",
     "mould",
     "mount",
     "move",
     "movement",
     "moving",
     "muddle",
     "muddled",
     "muff",
     "munching",
     "murky",
     "mush",
     "mushy",
     "mutate",
     "mutation",
     "mutilate",
     "mutilation",
     "mutinous",
     "mutiny",
     "mysterious",
     "nastily",
     "nasty",
     "naughty",
     "neatened",
     "neglect",
     "negotiate",
     "negotiated",
     "nervous",
     "new",
     "nimble",
     "nobble",
     "nomadic",
     "nonconforming",
     "nonplus",
     "nonsense",
     "nonstandard",
     "not in order",
     "not properly",
     "not right",
     "nouveau",
     "novel",
     "nuts",
     "nutty",
     "objectionable",
     "oblique",
     "obscene",
     "obscure",
     "obstreperous",
     "odd",
     "oddball",
     "off",
     "offend",
     "onslaught",
     "operate",
     "option",
     "orchestra",
     "ordeal",
     "order",
     "orderly",
     "orders",
     "organisation",
     "organization",
     "organize",
     "organized",
     "orgy",
     "original",
     "originally",
     "ornate",
     "oscillate",
     "ostensible",
     "otherwise",
     "ought to be",
     "out",
     "out of hand",
     "out of joint",
     "out of order",
     "out of place",
     "out of shape",
     "out of sorts",
     "outlandish",
     "outrageous",
     "outwardly",
     "overcome",
     "overhaul",
     "overt",
     "overthrow",
     "overturn",
     "overwhelm",
     "overwrought",
     "palpitate",
     "pan",
     "panic",
     "pants",
     "paradox",
     "paranormal",
     "parody",
     "particular",
     "parts",
     "passion",
     "pastiche",
     "patch",
     "pathetic",
     "pattern",
     "peculiar",
     "peeve",
     "pell-mell",
     "pelt",
     "penal",
     "perform",
     "performing",
     "perhaps",
     "perish",
     "perky",
     "permutation",
     "perpetrate",
     "perplex",
     "perplexed",
     "persecute",
     "persuade",
     "perturb",
     "perverse",
     "perversion",
     "pervert",
     "petulant",
     "phoney",
     "phony",
     "physical jerks",
     "pick out",
     "pick to pieces",
     "pickle",
     "pickled",
     "pie",
     "piecemeal",
     "pieces",
     "pique",
     "pirouette",
     "pitch",
     "pitching",
     "pitiful",
     "pivot",
     "place",
     "plastered",
     "plastic",
     "play",
     "playing",
     "pliably",
     "plight",
     "plot",
     "ply",
     "poke",
     "pooh pooh",
     "poor",
     "poorly",
     "pop",
     "pose",
     "position",
     "possible",
     "possibly",
     "potential",
     "potty",
     "pound",
     "prance",
     "prancing",
     "prank",
     "precarious",
     "predicament",
     "preparation",
     "preparation of",
     "prepare",
     "prepared",
     "press",
     "pretend",
     "primitive",
     "problem",
     "process",
     "processed",
     "produce",
     "profligate",
     "program",
     "propel",
     "protest",
     "provoke",
     "pseudo",
     "pull into line",
     "pull to pieces",
     "pulp",
     "pulverize",
     "pummel",
     "pummelled",
     "punch",
     "punish",
     "push",
     "put in order",
     "put off",
     "put right",
     "put straight",
     "puzzle",
     "puzzling",
     "quaint",
     "quake",
     "quandary",
     "quarrel",
     "queer",
     "question",
     "questionable",
     "quirky",
     "quiver",
     "quivering",
     "rabble",
     "rack",
     "radical",
     "raffish",
     "ragged",
     "rail",
     "raillery",
     "rally",
     "ramble",
     "rambling",
     "rampage",
     "rampant",
     "ramshackle",
     "random",
     "randomly",
     "range",
     "rare",
     "rattle",
     "ratty",
     "ravage",
     "ravaged",
     "raving",
     "raw",
     "re-edit",
     "reaction",
     "rearrange",
     "rearranged",
     "reassemble",
     "reassembled",
     "rebel",
     "rebuild",
     "rebuilt",
     "recast",
     "recipe",
     "reckless",
     "recollect",
     "recollected",
     "recombine",
     "recondition",
     "reconfigured",
     "reconsider",
     "reconstruct",
     "reconstructed",
     "reconstruction",
     "reconstruction of",
     "recreate",
     "recreated",
     "rectified",
     "rectify",
     "recycle",
     "recycled",
     "redesign",
     "redevelop",
     "redeveloped",
     "redirect",
     "rediscover",
     "redistributed",
     "redraft",
     "redraw",
     "reel",
     "reeling",
     "refashioned",
     "refined",
     "refit",
     "reform",
     "reformed",
     "refurbished",
     "regenerate",
     "regenerated",
     "regrettable",
     "regulated",
     "rehash",
     "reincarnate",
     "rejig",
     "relaunch",
     "relax",
     "relaxed",
     "relay",
     "relocate",
     "remade",
     "remarkable",
     "remodel",
     "rend",
     "render",
     "renew",
     "renovate",
     "renovated",
     "rent",
     "reorder",
     "reorganise",
     "repackage",
     "repair",
     "repaired",
     "replace",
     "replaced",
     "repositioned",
     "represent",
     "reproduce",
     "resettle",
     "resettled",
     "reshaped",
     "reshuffle",
     "resolve",
     "resort",
     "restitution",
     "restless",
     "restoration",
     "restore",
     "restructure",
     "revamp",
     "review",
     "reviewed",
     "revise",
     "revision",
     "revolt",
     "revolting",
     "revolutionary",
     "revolve",
     "rework",
     "rewrite",
     "rewritten",
     "rickety",
     "riddle",
     "ridicule",
     "ridiculous",
     "rig",
     "riot",
     "riotously",
     "rip",
     "ripple",
     "roam",
     "rock",
     "rocky",
     "rogue",
     "roll",
     "rollicking",
     "rolls",
     "rotten",
     "rough",
     "roughly",
     "round",
     "roundabout",
     "rouse",
     "rove",
     "row",
     "rubbish",
     "ruffle",
     "ruin",
     "ruination",
     "rum",
     "rumble",
     "run",
     "run riot",
     "run wild",
     "rupture",
     "ruptured",
     "rustic",
     "sabotage",
     "sack",
     "sad",
     "sadly",
     "salad",
     "savage",
     "scandal",
     "scathe",
     "scatter",
     "scattered",
     "scheme",
     "scraggy",
     "scramble",
     "scrap",
     "scrappy",
     "screw",
     "screwed",
     "screwy",
     "scruffy",
     "scuffle",
     "sculpture",
     "seedy",
     "seesaw",
     "seizure",
     "serve",
     "served",
     "set",
     "set in motion",
     "set out",
     "set right",
     "shake",
     "shaken",
     "sham",
     "shambles",
     "shape",
     "shaped",
     "shatter",
     "shattered",
     "shift",
     "shifty",
     "shimmer",
     "shimmy",
     "shiver",
     "shock",
     "shocked",
     "shoddy",
     "shot",
     "shove",
     "shown off",
     "shred",
     "shredded",
     "shudder",
     "shuffle",
     "shuffled",
     "sick",
     "silly",
     "singular",
     "sinuous",
     "sketchy",
     "skip",
     "skittish",
     "slapdash",
     "slaughtered",
     "sleight",
     "slide",
     "slip",
     "sloppy",
     "smack",
     "smash",
     "smashed",
     "smashing",
     "smudge",
     "snarled",
     "solution",
     "solve",
     "somehow",
     "somersault",
     "somewhat",
     "sophisticated",
     "sorry",
     "sort",
     "sort of",
     "soup",
     "sozzled",
     "spank",
     "spasmodic",
     "spattered",
     "special",
     "speculate",
     "spill",
     "spilled",
     "spin",
     "spinning",
     "spirited",
     "splintered",
     "split",
     "spoil",
     "spoilt",
     "sport",
     "sprawl",
     "spray",
     "sprayed",
     "spread",
     "sprightly",
     "spring",
     "sprinkle",
     "spun",
     "spurious",
     "squiffy",
     "squirm",
     "staged",
     "stagger",
     "staggering",
     "stampede",
     "startle",
     "stew",
     "stir",
     "storm",
     "stormy",
     "straighten",
     "strange",
     "strangely",
     "strategy",
     "stray",
     "in a strop",
     "structured",
     "struggle",
     "struggling",
     "stumble",
     "stunt",
     "stupid",
     "stupidly",
     "style",
     "styled",
     "stylistic",
     "substance",
     "substituted",
     "suffer",
     "supple",
     "supply",
     "surgery",
     "surprise",
     "surprising",
     "suspect",
     "swagger",
     "sway",
     "swilled",
     "swim",
     "swimming",
     "swing",
     "swirl",
     "swirling",
     "switch",
     "switched",
     "synthetic",
     "tackle",
     "tactics",
     "tailor",
     "tainted",
     "take badly",
     "take by surprise",
     "take ill",
     "take liberties",
     "take wing",
     "tamper",
     "tangle",
     "tawdry",
     "tear",
     "tease",
     "teeter",
     "teetering",
     "temperamental",
     "tempered",
     "terrible",
     "theatrical",
     "thrash",
     "thrashing about",
     "threaten",
     "throb",
     "throw",
     "tickle",
     "tidy",
     "tight",
     "tinker",
     "tipsy",
     "to make",
     "to wrestle",
     "tongue in cheek",
     "topsy turvy",
     "torment",
     "tormented",
     "torn",
     "tortuous",
     "torture",
     "tortured",
     "toss",
     "totter",
     "touchy",
     "tour",
     "tousle",
     "toy",
     "tragic",
     "train",
     "trained",
     "transfer",
     "transform",
     "transformed",
     "transition",
     "translate",
     "translated",
     "translation",
     "transmute",
     "transport",
     "transported",
     "transpose",
     "transposed",
     "trash",
     "trashed",
     "travel",
     "treachery",
     "treat",
     "treated",
     "treatment",
     "tremble",
     "trepidation",
     "trial",
     "tribulation",
     "trick",
     "tricky",
     "trim",
     "trip",
     "trips",
     "trouble",
     "tumble",
     "tumbling",
     "tumult",
     "tumultuous",
     "turbulent",
     "turmoil",
     "turn",
     "turning",
     "tweak",
     "tweaked",
     "twirl",
     "twist",
     "twisted",
     "twitch",
     "type",
     "ugly",
     "unbalanced",
     "unbridled",
     "unbundle",
     "uncanny",
     "uncertain",
     "uncivilised",
     "uncontrolled",
     "unconventional",
     "uncultivated",
     "uncured",
     "undecided",
     "undefined",
     "undisciplined",
     "undone",
     "undulate",
     "unearthly",
     "unexpected",
     "unfaithful",
     "unfamiliar",
     "unfettered",
     "unfit",
     "unfortunate",
     "unfurl",
     "ungainly",
     "ungoverned",
     "unhappy",
     "unhealthy",
     "unkempt",
     "unlawful",
     "unlikely",
     "unnatural",
     "unordered",
     "unorthodox",
     "unpredictable",
     "unprepared",
     "unravel",
     "unravelling",
     "unrecognisable",
     "unrest",
     "unrestrained",
     "unrestricted",
     "unruly",
     "unscrambled",
     "unscrupulous",
     "unseemly",
     "unsettle",
     "unsettled",
     "unsound",
     "unstable",
     "unsteady",
     "untamed",
     "untethered",
     "untidy",
     "untoward",
     "untrained",
     "untrue",
     "untutored",
     "unusual",
     "unwieldy",
     "up in the air",
     "up in arms",
     "upheaval",
     "uprise",
     "uproar",
     "upset",
     "vacillate",
     "vacillating",
     "vagrant",
     "vague",
     "vaguely",
     "vandalized",
     "variant",
     "variation",
     "variety",
     "various",
     "vary",
     "veer",
     "venture",
     "versatile",
     "version",
     "vex",
     "vibrate",
     "vicious",
     "vigorous",
     "vigorously",
     "violated",
     "violation of",
     "violent",
     "violently",
     "volatile",
     "wacky",
     "wag",
     "wander",
     "wandering",
     "warp",
     "warped",
     "wasted",
     "wave",
     "waver",
     "wayward",
     "weaved",
     "weird",
     "whack",
     "whip up",
     "whirl",
     "whisk",
     "wicked",
     "wiggle",
     "wild",
     "wind",
     "winding",
     "wise",
     "wobble",
     "wonder",
     "woolly",
     "work",
     "worked",
     "worried",
     "worry",
     "wound",
     "woven",
     "wreck",
     "wrecked",
     "wrestle",
     "wrestling",
     "wretched",
     "wriggle",
     "wring",
     "writhe",
     "writhing",
     "wrong",
     "wrought",
     "yielding",
     "zany"]

anagramIndicatorsR
  = []

oddsNoise
  = ["all",
     "at",
     "bits",
     "must"]

oddsInd1
  = []

oddsInd2
  = oddsIndicatorsL ++ oddsIndicatorsR

oddsIndicatorsL
  = ["oddly",
     "not even",
     "uneven",
     "at odds",
     "even go",
     "at odds with",
     "every other",
     "alternately",
     "regularly"]

oddsIndicatorsR
  = []

evensNoise
  = ["all",
     "at",
     "bits",
     "must",
     "of"]

evensInd1
  = []

evensInd2
  = evensIndicatorsL ++ evensIndicatorsR

evensIndicatorsL
  = ["evens",
     "even",
     "evenly",
     "not odd",
     "not at all odd",
     "not at odds",
     "no odds",
     "odd go",
     "odds removed",
     "removed odds",
     "every other",
     "alternately",
     "regularly"]

evensIndicatorsR
  = []

removeMiddleNoise
  = ["of",
     "the"]

removeMiddleInd1
  = []

removeMiddleInd2
  = removeMiddleIndicatorsL ++ removeMiddleIndicatorsR

removeMiddleIndicatorsL
  = ["empty",
     "emptied",
     "empties",
     "heartless",
     "disheartened",
     "gutted",
     "gutless",
     "void",
     "voided",
     "sides of",
     "ends",
     "ends of",
     "extremely",
     "extremes",
     "extremes of",
     "peripherals"]

removeMiddleIndicatorsR
  = ["emptied",
     "heartless",
     "disheartened",
     "gutted",
     "dropping guts",
     "extremes",
     "unoccupied",
     "without",
     "without guts"]

removeEndsNoise
  = ["of",
     "the"]

removeEndsInd1
  = ["in",
     "within"]

removeEndsInd2
  = removeEndsIndicatorsL ++ removeEndsIndicatorsR

removeEndsIndicatorsL
  = ["within",
     "somewhat",
     "found in",
     "needed by",
     "from",
     "inside",
     "part of",
     "peeling",
     "stored in",
     "middle",
     "centre",
     "centre of",
     "heart of",
     "inner",
     "core",
     "central",
     "inside",
     "guts",
     "served by",
     "internals",
     "chunk of",
     "seen in",
     "stores",
     "innards",
     "bit of",
     "most of",
     "mostly",
     "partly",
     "almost",
     "nearly",
     "chunk of"]

removeEndsIndicatorsR
  = []

-- This is all of them. During evaluation we pick off the one(s) we need
-- to apply.
subTextNoise
  = firstLettersNoise ++ lastLettersNoise ++ removeEndsNoise ++ removeMiddleNoise

subTextInd1
  = firstLettersInd1 ++ lastLettersInd1 ++ removeEndsInd1 ++ removeMiddleInd1

subTextInd2
  = firstLettersIndicatorsL ++ firstLettersIndicatorsR ++
    lastLettersIndicatorsL ++ lastLettersIndicatorsR ++
    removeEndsIndicatorsL ++ removeEndsIndicatorsR ++
    removeMiddleIndicatorsL ++ removeMiddleIndicatorsR

firstLettersNoise
  = ["all,",
     "at",
     "in",
     "of",
     "the",
     "to"]

firstLettersInd1
  = []

firstLettersInd2
  = firstLettersIndicatorsL ++ firstLettersIndicatorsR

firstLettersIndicatorsL
  = ["all leaders",
     "all leaders in",
     "almost",
     "at first",
     "beginners",
     "beginning",
     "beginning of",
     "cap",
     "capital",
     "bit of",
     "brief",
     "endless",
     "front",
     "front of",
     "first",
     "first of",
     "firstly",
     "incomplete",
     "head",
     "head of",
     "heading",
     "initially",
     "lead",
     "leading",
     "leader",
     "leaders",
     "mostly",
     "opener",
     "opening",
     "part of",
     "start of",
     "start to",
     "starts to",
     "to open",
     "tailless",
     "top"]

firstLettersIndicatorsR
  = []

lastLettersNoise
  = ["at",
     "bit",
     "character",
     "in",
     "letter",
     "of",
     "part",
     "the"]

lastLettersInd1
  = []

lastLettersInd2
  = lastLettersIndicatorsL ++ lastLettersIndicatorsR

lastLettersIndicatorsL
  = ["topless",
     "headless",
     "last",
     "lastly",
     "mostly",
     "back",
     "back of",
     "bottom",
     "tail",
     "suffix",
     "suffices",
     "suffixes",
     "tail of",
     "end",
     "end of",
     "in the end",
     "ultimately",
     "finally"]

lastLettersIndicatorsR
  = []

hiddenWordNoise
  = ["be",
     "by",
     "is",
     "of",
     "to",
     "was"]

hiddenWordInd1
  = ["in"]

hiddenWordInd2
  = hiddenWordIndicatorsL ++ hiddenWordIndicatorsR

hiddenWordIndicatorsL
  = ["within",
     "somewhat",
     "consumed by",
     "contained in",
     "found in",
     "hidden in",
     "hides",
     "hiding in",
     "houses",
     "inside",
     "needed by",
     "from",
     "part of",
     "seen in",
     "spotted in",
     "spanning",
     "engaged in",
     "some",
     "stores"]

hiddenWordIndicatorsR
  = []

duplicateNoise
  = ["a",
     "of",
     "over",
     "times",
     "up"]

duplicateInd1
  = []

duplicateInd2
  = duplicateIndicatorsL ++ duplicateIndicatorsR

duplicateIndicatorsL
  = ["and again",
     "double",
     "duplicate",
     "in duplicate",
     "pair",
     "repeat",
     "repetition",
     "two",
     "twice",
     "twin"]

duplicateIndicatorsR
  = []

homophoneNoise
  = ["as",
     "in",
     "is",
     "it",
     "it's",
     "on",
     "out",
     "so",
     "to",
     "the"]

homophoneInd1
  = []

homophoneInd2
  = homophoneIndicatorsL ++ homophoneIndicatorsR

homophoneIndicatorsL
  = ["according to hearsay",
     "announced",
     "aloud",
     "as we hear",
     "audible",
     "audibly",
     "auditors",
     "auditioned",
     "aurally",
     "call",
     "called",
     "called out",
     "by the mouth",
     "by the sound of it",
     "dictated",
     "discussed",
     "for the audience",
     "for the auditor",
     "for the listener",
     "heard",
     "hearers",
     "in audition",
     "in conversation",
     "in recital",
     "in speaking",
     "in speech",
     "it is said",
     "listeners",
     "by radio",
     "on the radio",
     "orally",
     "overheard",
     "pronounced",
     "report",
     "reported",
     "reportedly",
     "said",
     "say",
     "so it's said",
     "so to speak",
     "so we hear",
     "sound",
     "sounded",
     "sounding",
     "sounds like",
     "speakers",
     "spoken",
     "they say",
     "as they say",
     "so they say",
     "as it's said",
     "to the audience",
     "to the auditor",
     "to the listener",
     "vocal",
     "voiced",
     "we hear",
     "when heard"]

homophoneIndicatorsR
  = []

exampleOfNoise
  = ["of"]

exampleOfInd1
  = []

exampleOfInd2
  = exampleOfIndicatorsL ++ exampleOfIndicatorsR

exampleOfIndicatorsL
  = ["example of",
     "sort of",
     "type of",
     "maybe"]

exampleOfIndicatorsR
  = ["for example",
     "perhaps",
     "in particular",
     "maybe"]

--remove: spring, springs, for
reversalNoise
  = ["after",
     "been",
     "come",
     "being",
     "go",
     "goes",
     "going",
     "gone",
     "has",
     "have",
     "in",
     "is",
     "send",
     "sent",
     "to",
     "was"]

reversalInd1
  = ["over",
     "back"]

reversalInd2
  = reversalIndicatorsL ++ reversalIndicatorsR

reversalIndicatorsL
  = ["up",
     "flipping",
     "flipped",
     "reversed",
     "reversal",
     "in reverse",
     "reversing",
     "backward",
     "backwards",
     "back",
     "backed",
     "after recovery",
     "in retirement",
     "recovering",
     "returned",
     "returns",
     "around",
     "going around",
     "after going around",
     "raised",
     "raising",
     "reflected",
     "reflecting",
     "rejected",
     "revolve",
     "for revolution",
     "revolution",
     "on reflection",
     "roundabout",
     "round about",
     "upset",
     "upsets",
     "thrown over",
     "over",
     "springs back",
     "about",
     "turn",
     "turns",
     "turned",
     "east",
     "west",
     "north",
     "left",
     "right",
     "from the bottom",
     "from the south",
     "up",
     "uprising",
     "upwardly mobile"]

reversalIndicatorsR
  = ["riser"]

insertionNoise
  = ["as",
     "been",
     "by",
     "has",
     "is",
     "lies",
     "locate",
     "place",
     "sits",
     "to",
     "was"]

insertionInd1
  = []

insertionInd2L1
  = ["around",
     "outside",
     "about",
     "bracketing",
     "surrounding",
     "ringing",
     "enveloping",
     "flanking",
     "holding",
     "including",
     "carrying",
     "swallowing",
     "eating",
     "inhaling",
     "consuming",
     "munching",
     "encasing",
     "containing",
     "circling",
     "covered by",
     "clutching",
     "encircling",
     "embracing",
     "enfolding",
     "grasping",
     "packing",
     "harbouring",
     "sheltering",
     "housing",
     "accommodating",
     "imbibing",
     "hiding",
     "lining",
     "internalising",
     "introducing",
     "smuggling",
     "securing",
     "admitting",
     "restraining",
     "taking in",
     "ringing"]

insertionInd2L2
  = ["within",
     "inside",
     "amidst",
     "amongst",
     "between",
     "carried by",
     "during",
     "ringed by",
     "included in",
     "hidden in",
     "hiding in",
     "landed in",
     "in",
     "internal to",
     "inherent in",
     "intrinsic to",
     "involved in",
     "wrapping"]

-- insert x y -> insert x into y
insertionInd2C1
  = ["about",
     "admission to",
     "amidst",
     "amongst",
     "between",
     "carried by",
     "cuts",
     "introduced to",
     "admitted to",
     "occupying",
     "occupies",
     "occupied",
     "boarding",
     "boards",
     "boarded",
     "piercing",
     "pierces",
     "pierced",
     "dividing",
     "divides",
     "divided",
     "during",
     "embraced by",
     "entering",
     "enters",
     "entered",
     "filling",
     "fills",
     "filled",
     "held in",
     "landed in",
     "stuffing",
     "stuffs",
     "stuffed",
     "to secure",
     "penetrating",
     "penetrates",
     "penetrated",
     "pinching",
     "within",
     "hidden within",
     "wearing",
     "put in",
     "put into",
     "tucked into",
     "inside",
     "admitted to",
     "ringed by",
     "surrounded by",
     "carried in by",
     "in",
     "included in",
     "hidden in",
     "internal to",
     "inherent in",
     "intrinsic to",
     "involved in",
     "tucked into",
     "to invade",
     "to open",
     "invades",
     "taken in by"]

insertionInd2C2
  = ["across",
     "crossing",
     "keeping",
     "without",
     "receives",
     "around",
     "round",
     "put round",
     "outside",
     "about",
     "bracketing",
     "covering",
     "curtains",
     "brackets",
     "bracketed",
     "surrounding",
     "surrounds",
     "surrounded",
     "ringing",
     "rings",
     "ringed",
     "enveloping",
     "envelopes",
     "enveloped",
     "flanking",
     "flanks",
     "flanked",
     "given",
     "holding",
     "holds",
     "held",
     "including",
     "includes",
     "included",
     "carrying",
     "carries",
     "carried",
     "swallowing",
     "swallows",
     "swallowed",
     "inhaling",
     "inhales",
     "inhaled",
     "consuming",
     "consumes",
     "consumed",
     "munching",
     "munches",
     "munched",
     "eating",
     "eats",
     "ate",
     "takes",
     "taking in",
     "takes in",
     "took in",
     "wrapping",
     "wraps",
     "wrapped",
     "encasing",
     "encases",
     "encased",
     "containing",
     "contains",
     "contained",
     "circling",
     "circles",
     "circled",
     "covering",
     "covers",
     "covered",
     "clutching",
     "clutches",
     "clutched",
     "encircling",
     "encircles",
     "encircled",
     "embracing",
     "embraces",
     "embraced",
     "enfolding",
     "enfolds",
     "enfolded",
     "grasping",
     "grasps",
     "grasped",
     "packing",
     "packs",
     "packed",
     "harbouring",
     "harbours",
     "harboured",
     "sheltering",
     "shelters",
     "sheltered",
     "housing",
     "houses",
     "housed",
     "accommodating",
     "accommodates",
     "accommodated",
     "imbibing",
     "imbibes",
     "imbibed",
     "hiding",
     "hides",
     "hid",
     "lining",
     "lines",
     "lined",
     "internalising",
     "internalises",
     "internalised",
     "introducing",
     "introduces",
     "introduced",
     "smuggling",
     "smuggles",
     "smuggled",
     "secures",
     "admitting",
     "admits",
     "admitted",
     "restraining",
     "restrains",
     "restrained",
     "burying",
     "buries",
     "buried",
     "furnishing",
     "furnishes",
     "furnished",
     "camouflaging",
     "camouflages",
     "camouflaged",
     "besieging",
     "besieges",
     "besieged",
     "boxing",
     "boxes",
     "boxed",
     "catching",
     "catches",
     "caught",
     "packing",
     "packs",
     "packed",
     "welcomes",
     "welcome"]

insertionInd2R1
  = []

insertionInd2R2
  = ["within",
     "amidst",
     "amongst",
     "between",
     "in",
     "inside",
     "put in",
     "put inside"]

subtractionNoise
  = ["after",
     "been",
     "being",
     "has",
     "have",
     "is",
     "of",
     "on",
     "was",
     "by"]

subtractionInd1
  = ["from"]

--remove: out
subtractionInd2L1
  = ["having removed",
     "having lost",
     "lost",
     "losing",
     "missing",
     "missed",
     "missing out",
     "missed out",
     "missing out on",
     "missed out on",
     "deprived of",
     "dropping",
     "dropped",
     "deleting",
     "deleted",
     "without",
     "minus",
     "letting slip",
     "let slip",
     "abandoning",
     "abandons",
     "erasing",
     "wiping"
     ]

subtractionInd2L2
  = ["erasing",
     "losing",
     "dropping",
     "without",
     "letting slip"]

subtractionInd2C1
  = ["flees",
     "left",
     "leaves",
     "missing from",
     "missed from",
     "was missed from",
     "dropping from",
     "dropped from",
     "was dropped from",
     "deleting from",
     "deleted from",
     "was deleted from",
     "taken from",
     "was taken from",
     "missing from",
     "withdrawing from",
     "withdrawn from",
     "was withdrawn from",
     "withdrew from"]

subtractionInd2C2
  = subtractionInd2L1

-- Exceptionally rare...
subtractionInd2R1
  = []

subtractionInd2R2
  = ["removed",
     "left",
     "deleted",
     "lost",
     "goes",
     "missing",
     "being removed",
     "being deleted",
     "being lost",
     "from",
     "dropped",
     "deleted",
     "scrapped",
     "sacked",
     "without",
     "let slip"]

-- remove: came, comes
charadeNoise
  = ["come",
     "go",
     "goes",
     "going",
     "gone",
     "is",
     "lies",
     "sits",
     "was"]

charadeInd1
  = []

charadeInd2L1
  = ["after",
     "concluding",
     "under",
     "opposite",
     "following"]

charadeInd2L2
  = ["before",
     "over",
     "above",
     "next to",
     "with",
     "beside",
     "by",
     "above",
     "and",
     "takes",
     "needing",
     "follows"
                  ]
charadeInd2C1
  = ["and",
     "before",
     "by",
     "has",
     "having",
     "holding",
     "given",
     "leading to",
     "next to",
     "together with",
     "followed by",
     "meeting",
     "met",
     "on",
     "beside",
     "above",
     "to",
     "over",
     "going to",
     "is going to",
     "and",
     "takes",
     "taking",
     "needing",
     "with"]

charadeInd2C2
  = ["after",
     "behind",
     "concluding",
     "covered by",
     "on",
     "opposite",
     "to support",
     "follows",
     "following"]

charadeInd2R1
  = ["after",
     "came after",
     "comes after",
     "afterwards",
     "following",
     "follows",
     "followed"]

charadeInd2R2
  = ["before",
     "earlier",
     "precedes"]
