module Synonyms where

import qualified Data.Set as Set
import qualified Data.Map as Map
import Data.Array.IArray
import Data.Char
import Data.List

import Databases
import Utilities
import Types

------ SYNONYMS ------

singular ["spies"]
  = ["spy"]

isSynonym w w'
  = elem w (synonyms w')

-- Note: string like "a son" will eventually be treated as the concatenation of
-- "a" and "son" leading to "ason", but removing whitespace provides a shortcut
-- to the same thing.

-- NEED TO MAKE SYNONYMS LOWER CASE...

checkSyn s s'
  = elem s $ map fst $ synonyms s'

-- Experiment: synonyms do NOT include the word itself...
synonyms :: String -> [(String, StringType)]
synonyms s
--  = (s', Syn) : (s'', Syn) : (
--  map (map toLower) (filter (not . null) $ thesaurusLookup s) ++
  = (map makeSyn (lookUp s manualDefinitions) ++
     map (makeSyn . map toLower) (filter (not . null) (thesaurusLookup s)) ++
     map makeAbbr (maybe [] id (Map.lookup s abbreviations)) ++
     map makeName (lookUp s nameSynonyms))
{-
  where
    s' = cleanUp s
    s'' = filter (not . isSpace) s
-}

makeSyn s
  = (s, Syn)
makeAbbr s
  = (s, Abbr)
makeName s
  = (s, Name)

thesaurusLookup w
  = maybe [] (\s -> map (\n -> keys ! n) s) (Map.lookup w thesaurus)

-- Synonym table - used to speed up length functions.
-- Caches synonyms sorted by length and then alphabetically.
makeSynonymTable :: Clue -> SynonymTable
makeSynonymTable (clueText, n)
  = [(w, (makeArray sorted mn mx)) | 
       w <- substrings (words s), 
       let syns = synonyms (unwords w),
       let ns = map (length . fst) syns,
       let sorted = sort (zip ns syns),
       let (ns', syns') = unzip sorted,
       let (mn, mx) = (head ns', last ns')]
  where
    s = cleanUp clueText
       
makeArray :: [(Int, AnnotatedString)] -> Int -> Int -> Array Int [AnnotatedString]
makeArray syns mn mx
  = listArray (mn, mx) [sort [ws | (k, ws) <- syns, k == n] | n <- [mn..mx]]


------------------------------------ MANUAL FACTS -----------------------------

manualDefinitions
  = [("left", ["l"]), -- added to do performance test
     ("noahs son", ["shem"]),
     ("in a muddle", ["shemozzle"]),
     ("russian fighter", ["mig"]),
     ("skin disease", ["mange"]),
     ("battle scene", ["alamo"]),
     ("small space", ["alcove"]),
     ("money spent", ["disbursement"]),
     ("brought in", ["earned"]), 
     ("ballet", ["swanlake"]), 
     ("green", ["eco"]), 
     ("member", ["arm", "leg"]), 
     ("muse", ["calliope", "clio", "euterpe", "erato", "melpomene",
               "polyhymnia", "terpsichore", "thalia", "urania"]),
     ("put food in this", ["tuckerbag"]),
     ("home counties", ["se"]),
     ("small worker", ["ant"]),
     ("hospital department", ["ent"]),
     ("wine", ["aseti"]),
     ("earnest request", ["prayer"]),
     ("paper in the street", ["litter"]),
     ("waste paper", ["litter"]),
     ("not public", ["secret"]),
     ("providing", ["if"]),
     ("provided", ["if"]),
     ("agent", ["m","q"]),
     ("spy", ["m","q"]),
     ("rubbish", ["rot", "tat"]),
     ("by", ["times"]),
     ("side", ["eleven"]),
     ("bribe", ["bung"]),
     ("determined", ["obdurate"]),
     ("fascist", ["duce"]),
     ("party", ["thrash"]),
     ("parties", ["thrashes"]),
     ("address", ["orate"]), 
     ("sober", ["tt"]), 
     ("oven", ["oast"]), 
     ("indications", ["signage"]), 
     ("liberal", ["l"]), 
     ("working", ["on"]), 
     ("notice", ["ack"]), 
     ("notice", ["sign"]), 
     ("corset", ["basque"]),
     ("flying", ["jet"]), 
     ("pause", ["hesitate"]), 
     ("flyer", ["airman"]), 
     ("stuff", ["tuck"]),
     ("school", ["groom"]),
     ("fondness", ["endearment"]),
     ("theme", ["leitmotif"]),
     ("this evening", ["tonight"]),
-- Reverse dictionary synonyms...
     ("holiday apartment", ["timeshare"])]

------- NAME SYNONYMS --------

associate syns names
  = map (\s -> (s,names)) syns

nameSynonyms
  = associate malesynonyms (Set.elems malenames) ++
    associate femalesynonyms (Set.elems femalenames)

malesynonyms
  = ["man", "him", "his name", "name", "boy", "he"]

femalesynonyms
  = ["woman", "her", "her name", "name", "girl", "she"]


------- ABBREVIATONS --------

abbreviations
  = Map.fromList [("12.5 cents", ["dime"]),
     ("45 minutes", ["our","hou"]),
     ("666", ["mb"]),
     ("a", ["i"]),
     ("a follower", ["b"]),
     ("able seaman", ["salt","tar","sailor","ab"]),
     ("able to", ["can"]),
     ("about", ["ca","on","re","c"]),
     ("about turn", ["u"]),
     ("abstaining", ["tt"]),
     ("academic", ["ma","prof"]),
     ("academician", ["ra","a","ara","pra"]),
     ("academy", ["rada","ra"]),
     ("acceptable", ["u","ok"]),
     ("accepted", ["a"]),
     ("account", ["ac","acc"]),
     ("a and e", ["ae"]),
     ("a & e", ["ae"]),
     ("a&e", ["ae"]),
     ("accident and emergency", ["ae"]),
     ("accountant", ["ca","aca","ac"]),
     ("ace", ["a","ai"]),
     ("acknowledge", ["ack"]),
     ("acknowledgement", ["ack"]),
     ("acre", ["a"]),
     ("across", ["x"]),
     ("act", ["do"]),
     ("acting", ["on"]),
     ("active", ["a"]),
     ("actor", ["tree","ham"]),
     ("actuary", ["aia","fia"]),
     ("admitting", ["am","iam","im"]),
     ("adult", ["a"]),
     ("advanced", ["lent","a"]),
     ("advertisement", ["ad"]),
     ("aeroplane", ["mig"]),
     ("after date", ["ad"]),
     ("after the style of", ["ala"]),
     ("afternoon", ["a","iam","pm"]),
     ("again", ["bis","re"]),
     ("against", ["con","v"]),
     ("age", ["eon"]),
     ("aged", ["aet","ae"]),
     ("agent", ["rep","spy","v","g"]),
     ("agreement", ["ay","ja","aye","yea","da","oui","si"]),
     ("airborne soldier", ["para"]),
     ("aircraftsman", ["ac","lac"]),
     ("airline", ["ba","bac","bea"]),
     ("airman", ["po"]),
     ("alabama", ["al","ala"]),
     ("alan", ["al"]),
     ("alaska", ["alas"]),
     ("albania", ["al"]),
     ("albert", ["al"]),
     ("alcoholic state", ["dt"]),
     ("aleph", ["a"]),
     ("alien", ["et"]),
     ("all right", ["ok"]),
     ("allow", ["let"]),
     ("allowed", ["let"]),
     ("alloy", ["y"]),
     ("alpha", ["a"]),
     ("alternating current", ["ac"]),
     ("alternative", ["or"]),
     ("alternatively", ["or"]),
     ("alto", ["a"]),
     ("aluminium", ["al"]),
     ("always", ["ay","ere","aye","eer"]),
     ("amateur", ["a"]),
     ("amateurs department", ["diy"]),
     ("ambassador", ["he"]),
     ("america", ["us","usa","am"]),
     ("american", ["am","amer","us"]),
     ("american detective", ["fed","g man"]),
     ("american lawyer", ["da"]),
     ("american man", ["bo"]),
     ("american policeman", ["bull"]),
     ("american railway", ["el"]),
     ("american soldier", ["joe","gi"]),
     ("ampere", ["a"]),
     ("an", ["a","i"]),
     ("anaesthetic", ["number"]),
     ("anarchist", ["red"]),
     ("ancient city", ["ur","troy"]),
     ("ancient times", ["bc"]),
     ("and", ["et"]),
     ("ane", ["a","i"]),
     ("anger", ["ire"]),
     ("angle", ["l"]),
     ("anglo saxon", ["as"]),
     ("angstrom", ["a"]),
     ("annual meeting", ["agm"]),
     ("answer", ["a","ans"]),
     ("ante", ["a"]),
     ("appeal", ["sos"]),
     ("appearance", ["air"]),
     ("application", ["use"]),
     ("apprentice", ["l"]),
     ("approval", ["ok"]),
     ("approx", ["ca","some","c"]),
     ("approximately", ["some","c","ca"]),
     ("arab", ["ar"]),
     ("archbishop", ["cantuar","laud","ebor"]),
     ("archdeacon", ["ven"]),
     ("archer", ["tell"]),
     ("are", ["r","a"]),
     ("argy", ["rg"]),
     ("argy bargy", ["rg"]),
     ("arithmetic", ["r"]),
     ("army", ["ta"]),
     ("army regulation", ["ar"]),
     ("around", ["o","c"]),
     ("arrival", ["arr","ar"]),
     ("arrive", ["arr","ar"]),
     ("ars", ["rr"]),
     ("art nouveau", ["rat","tar"]),
     ("article", ["a","an","the"]),
     ("french article", ["la","les","le"]),
     ("french friend", ["ami"]),
     ("french way", ["rue"]),
     ("german article", ["der","die","das"]),
     ("italian article", ["il","la"]),
     ("spanish article", ["la","el","los"]),
     ("artillery", ["ra"]),
     ("artist", ["ra","lely","ara","pra","etty"]),
     ("arty", ["rt"]),
     ("as", ["s","qua"]),
     ("as above", ["us"]),
     ("asian", ["e"]),
     ("associate", ["a"]),
     ("at home", ["in"]),
     ("at one on", ["ation"]),
     ("at university", ["up"]),
     ("atomic", ["a"]),
     ("attempt", ["try"]),
     ("aught", ["o"]),
     ("australia", ["aus"]),
     ("austria", ["a"]),
     ("author", ["pen"]),
     ("authorisation", ["ok"]),
     ("autobiography", ["cv"]),
     ("average", ["ave","aver"]),
     ("avogadros number", ["n"]),
     ("award", ["om","obe","ch"]),
     ("away", ["out"]),
     ("ay", ["a","i"]),
     ("aye", ["i","a"]),
     ("ayes", ["is","as"]),
     ("ays", ["is","as"]),
     ("azed", ["az"]),
     ("bach", ["b"]),
     ("bachs works", ["s"]),
     ("bachelor", ["b","ba"]),
     ("bachelor of arts", ["ba"]),
     ("bad actor", ["ham"]),
     ("bad french", ["mal"]),
     ("badly", ["ill"]),
     ("bald patch", ["o"]),
     ("ball", ["o"]),
     ("bandage", ["t"]),
     ("bank rate", ["br"]),
     ("banker", ["river"]),
     ("bar", ["t","z"]),
     ("barbarian", ["hun"]),
     ("bargain", ["go"]),
     ("barium", ["ba"]),
     ("bark", ["woof","tan"]),
     ("baron", ["b"]),
     ("barrel", ["b"]),
     ("barrels", ["b"]),
     ("barrier", ["dam"]),
     ("bass", ["b"]),
     ("batting", ["in"]),
     ("beady", ["bd"]),
     ("beard", ["awn"]),
     ("bears", ["has"]),
     ("beat", ["lam","tan"]),
     ("bed", ["cot"]),
     ("bedbug", ["b"]),
     ("bee", ["b"]),
     ("beer", ["ale"]),
     ("bees", ["bs","bb"]),
     ("beethoven", ["b"]),
     ("before", ["or","a","an","ere"]),
     ("before christ", ["ac","bc"]),
     ("before food", ["ac"]),
     ("before the day", ["ad"]),
     ("beginning", ["alpha"]),
     ("being broadcast", ["on"]),
     ("bel", ["b"]),
     ("belgium", ["b"]),
     ("bend", ["u","z","s"]),
     ("bender", ["knee"]),
     ("beta", ["b"]),
     ("beth", ["b"]),
     ("beware", ["kv"]),
     ("bible", ["rv","av"]),
     ("big", ["os"]),
     ("big banger", ["tnt"]),
     ("big bell", ["tom"]),
     ("big guns", ["ra"]),
     ("big noise", ["vip"]),
     ("bikini", ["atoll"]),
     ("bill", ["ac","acc"]),
     ("bird", ["prison","tit"]),
     ("bishop", ["bp","rr","b","odo"]),
     ("bit", ["ort"]),
     ("black", ["b"]),
     ("blob", ["o"]),
     ("blockbuster", ["sculptor"]),
     ("blood group", ["o","b","a"]),
     ("bloody", ["red","b"]),
     ("bloomer", ["flower"]),
     ("blue", ["sad"]),
     ("bluetit", ["nun"]),
     ("blunder", ["err"]),
     ("boasting", ["am","iam","im"]),
     ("boat", ["q","e","u"]),
     ("bob", ["s"]),
     ("body", ["x"]),
     ("bomb", ["v","a","egg","h"]),
     ("bonds boss", ["m"]),
     ("bone", ["os","t"]),
     ("book", ["b","nt","ot","lib","tome","vol","bk"]),
     ("bookmaker", ["amos","job"]),
     ("books", ["bb","ot","nt"]),
     ("born", ["n","ne","nat","b","nee"]),
     ("boron", ["b"]),
     ("bound", ["bd"]),
     ("bowled", ["b"]),
     ("bowler", ["drake"]),
     ("boy", ["b"]),
     ("brahms", ["b"]),
     ("brakes", ["abs"]),
     ("branch", ["br"]),
     ("brazilian", ["para"]),
     ("breadth", ["b"]),
     ("bridge", ["br"]),
     ("bridge opponents", ["nw","sw","ne","se"]),
     ("bridge partners", ["ns","ew"]),
     ("bridge players", ["n","e","s","w"]),
     ("brief reply", ["ans"]),
     ("brig", ["br"]),
     ("britain", ["b","br"]),
     ("british", ["b","br"]),
     ("british company", ["bl"]),
     ("british museum", ["bm"]),
     ("british rail", ["br"]),
     ("brother", ["bro","br"]),
     ("brown", ["br","tan"]),
     ("bull", ["ox"]),
     ("business", ["co","biz","firm","ado"]),
     ("busy", ["tec"]),
     ("butler", ["rab"]),
     ("butter", ["ram"]),
     ("buzzer", ["bee"]),
     ("by", ["per"]),
     ("cagey", ["kg"]),
     ("cakesville", ["eccles"]),
     ("calcium", ["ca"]),
     ("california", ["cal"]),
     ("can", ["may","tin","able"]),
     ("cape", ["c"]),
     ("capeks play", ["rur"]),
     ("capital", ["ai"]),
     ("capital authority", ["glc"]),
     ("capone", ["al"]),
     ("captain", ["cid","old man"]),
     ("capture", ["net"]),
     ("caput", ["c"]),
     ("car", ["rr","mini"]),
     ("car test", ["mot"]),
     ("carat", ["car","ct"]),
     ("carbon", ["c"]),
     ("carbon monoxide", ["co"]),
     ("card", ["ace"]),
     ("care of", ["co"]),
     ("cart", ["t"]),
     ("cases", ["ca"]),
     ("cash", ["tin"]),
     ("castle", ["oo","r"]),
     ("cat", ["tom","mog","rex"]),
     ("cattle", ["kine","neat"]),
     ("caught", ["ct","c"]),
     ("cave", ["kv"]),
     ("cavity", ["o"]),
     ("cavy", ["kv"]),
     ("cayenne", ["kn"]),
     ("cedi", ["c"]),
     ("cedilla", ["z"]),
     ("celsius", ["c"]),
     ("celt", ["q","p"]),
     ("censor", ["edit","cato"]),
     ("cent", ["red","ct","c"]),
     ("centi ", ["c"]),
     ("centigrade", ["c"]),
     ("centime", ["ct","c"]),
     ("central heating", ["ch"]),
     ("century", ["c"]),
     ("certain", ["sure"]),
     ("champion", ["ace","ch"]),
     ("channel islands", ["ci"]),
     ("chapter", ["ch","cap","c"]),
     ("charles", ["c"]),
     ("che", ["i"]),
     ("cheat", ["do"]),
     ("cheers", ["ta"]),
     ("chemical", ["nitre"]),
     ("chemist", ["mps"]),
     ("cherished", ["pet"]),
     ("chess grandmaster", ["tal"]),
     ("chess piece", ["pawn"]),
     ("chewed", ["bit"]),
     ("chi", ["x"]),
     ("chief", ["ch","cid"]),
     ("chief executive", ["dg"]),
     ("child", ["ch","brat"]),
     ("childless", ["sp"]),
     ("children", ["seed"]),
     ("chimney", ["lum"]),
     ("china", ["ch","ming"]),
     ("china area", ["fare"]),
     ("chinese dynasty", ["han","ming"]),
     ("chlorine", ["cl"]),
     ("christ", ["x"]),
     ("christian era", ["ad"]),
     ("christmas period", ["dec"]),
     ("chromosome", ["y","x"]),
     ("church", ["c","ce","rc","ch"]),
     ("church of England", ["ce"]),
     ("cipher", ["o"]),
     ("circa", ["c"]),
     ("circle", ["ring","disc","o"]),
     ("circuit", ["o"]),
     ("circular letter", ["o"]),
     ("citation", ["cit"]),
     ("city", ["ec","ely"]),
     ("civil service", ["cs"]),
     ("class", ["cl"]),
     ("classical musician", ["orpheus"]),
     ("clause", ["cl"]),
     ("clear", ["rid"]),
     ("clef", ["f","g"]),
     ("cleric", ["bd","dd"]),
     ("close", ["nie"]),
     ("cloth", ["t","rep"]),
     ("cloudy", ["c"]),
     ("club", ["c"]),
     ("clubs", ["c"]),
     ("cobalt", ["co"]),
     ("cockney girl", ["er"]),
     ("cocktail", ["egg"]),
     ("cold", ["c"]),
     ("collection", ["ans"]),
     ("college", ["eton","c","poly"]),
     ("colombia", ["co"]),
     ("commander", ["oc","cinc","co","com"]),
     ("commanding officer", ["co"]),
     ("commotion", ["todo"]),
     ("communist", ["red"]),
     ("companion", ["ch"]),
     ("companion of honour", ["ch"]),
     ("company", ["two","co","firm"]),
     ("completely", ["all"]),
     ("complex number", ["c"]),
     ("concerning", ["re"]),
     ("condition", ["if"]),
     ("confusion", ["pi"]),
     ("connecticut", ["ct"]),
     ("conservative", ["tory","c","blue","con","u"]),
     ("conspirator", ["cade","oates"]),
     ("constant", ["k"]),
     ("contemporary", ["ad"]),
     ("continent", ["eur","asia"]),
     ("contralto", ["c"]),
     ("contrivance", ["art"]),
     ("cook", ["do"]),
     ("copper", ["d","p","cu","pc"]),
     ("copy", ["ape"]),
     ("copyright", ["c"]),
     ("corn", ["rip"]),
     ("corner", ["l"]),
     ("cornwall", ["sw"]),
     ("corporation", ["tum"]),
     ("correct", ["ok"]),
     ("corruption", ["rot"]),
     ("coulomb", ["c"]),
     ("counter", ["gm","geiger"]),
     ("county", ["co","down","som","avon"]),
     ("county council", ["cc"]),
     ("court", ["ct"]),
     ("cove", ["man"]),
     ("cow", ["lower"]),
     ("craft", ["art"]),
     ("credit", ["cr"]),
     ("credit notes", ["ious"]),
     ("cross", ["t","x","zo","tau"]),
     ("crossed", ["t"]),
     ("crown", ["cr"]),
     ("cry of delight", ["ole"]),
     ("cry of triumph", ["io"]),
     ("cuba", ["c"]),
     ("cue", ["q"]),
     ("cunning", ["art"]),
     ("cup holder", ["hebe"]),
     ("current", ["ac","dc"]),
     ("curse", ["ban"]),
     ("curve", ["arc"]),
     ("custom", ["use"]),
     ("cutie", ["qt"]),
     ("czechoslovakia", ["cs"]),
     ("Dads army", ["hg"]),
     ("dagger", ["da"]),
     ("daily", ["times","char"]),
     ("daisy", ["cow"]),
     ("damn", ["d"]),
     ("dance", ["pas"]),
     ("dark blue", ["oxonian"]),
     ("date", ["d"]),
     ("daughter", ["d"]),
     ("dawn", ["nus"]),
     ("day", ["v","d"]),
     ("days", ["dd"]),
     ("dead", ["d","obit"]),
     ("dead reckoning", ["dr"]),
     ("dear", ["chere","cher"]),
     ("debtor", ["dr"]),
     ("decay", ["rot"]),
     ("decentralise", ["core"]),
     ("deci", ["d"]),
     ("decimally", ["intens"]),
     ("decisive blow", ["ko"]),
     ("decree", ["act"]),
     ("Dee", ["d"]),
     ("deep", ["main","sea"]),
     ("degree", ["ma","deg","ba","d"]),
     ("delete", ["d"]),
     ("delta", ["d"]),
     ("Democrat", ["d"]),
     ("Denmark", ["dk"]),
     ("density", ["d"]),
     ("desert", ["rat"]),
     ("desert fighter", ["rat"]),
     ("deserted", ["d"]),
     ("deserter", ["rat"]),
     ("designer", ["dior"]),
     ("dessert", ["fool"]),
     ("detective", ["det","tec"]),
     ("detectives", ["cid","yard"]),
     ("deuterium", ["d"]),
     ("Deutsch", ["d"]),
     ("Devon", ["sw"]),
     ("dial", ["o"]),
     ("diameter", ["d"]),
     ("diamond", ["ice","rock","d"]),
     ("diamonds", ["d","ice"]),
     ("died", ["d","obit"]),
     ("differential operator", ["d"]),
     ("difficulty", ["ado","er"]),
     ("dime", ["ioc"]),
     ("diplomat", ["cd"]),
     ("Diracs constant", ["h"]),
     ("direction", ["e","s","w","n"]),
     ("director", ["d"]),
     ("director general", ["dg"]),
     ("directors", ["board"]),
     ("disadvantage", ["ward"]),
     ("disc", ["o"]),
     ("display", ["air"]),
     ("District attorney", ["da"]),
     ("ditch", ["haha"]),
     ("ditto", ["do"]),
     ("divine", ["dd"]),
     ("doctor", ["bm","mb","who","md","mo","dd","dr","gp","healer"]),
     ("doctor of divinity", ["dd"]),
     ("doctrine", ["ism"]),
     ("dog", ["cur","tail","mutt"]),
     ("doll", ["qp"]),
     ("dollar", ["s"]),
     ("dont change it", ["stet"]),
     ("donkey", ["ned","ass"]),
     ("double", ["di","bi","ka"]),
     ("double act", ["dodo"]),
     ("doubt", ["um"]),
     ("doughboy", ["gi"]),
     ("drag", ["d"]),
     ("dram", ["dr"]),
     ("draw", ["x"]),
     ("drawback", ["ward"]),
     ("drawer", ["dr"]),
     ("dressmaker", ["satin","silk"]),
     ("drinking", ["on"]),
     ("drowned valley", ["ria"]),
     ("drunk", ["lit"]),
     ("dry", ["sec","tt"]),
     ("duck", ["o"]),
     ("ducks eggs", ["oo"]),
     ("duke", ["fist","d"]),
     ("Durham area", ["ne"]),
     ("Dutch uncle", ["oom"]),
     ("each", ["ea"]),
     ("early morning", ["iam"]),
     ("earth", ["ge","e"]),
     ("ease", ["es","ee"]),
     ("east", ["e","ost"]),
     ("East africa", ["ea"]),
     ("eastern", ["e"]),
     ("ecclesiastical title", ["ven"]),
     ("economist", ["mill","smith"]),
     ("ecstatic", ["sent"]),
     ("Ecuador", ["ec"]),
     ("editor", ["ed"]),
     ("educated man", ["ma"]),
     ("educational establishment", ["u","eton"]),
     ("educational journal", ["test"]),
     ("Edward", ["e","ed","ted"]),
     ("eec", ["twelve"]),
     ("effect", ["a"]),
     ("egg", ["o"]),
     ("Egypt", ["et"]),
     ("eight", ["e"]),
     ("eight thousand", ["e"]),
     ("eighty", ["r"]),
     ("eighty thousand", ["r"]),
     ("el", ["l"]),
     ("elected", ["in"]),
     ("electoral system", ["pr"]),
     ("electrical capacity", ["c"]),
     ("electrical charge", ["q"]),
     ("electrical current", ["i"]),
     ("electrical flux", ["d"]),
     ("elevated railway", ["l"]),
     ("eleven", ["xi","o","ii"]),
     ("eleven thousand", ["o"]),
     ("Elizabeth", ["e"]),
     ("ell", ["l"]),
     ("ells", ["ll","ls"]),
     ("els", ["ll","ls"]),
     ("em", ["m"]),
     ("employ", ["use"]),
     ("employment", ["use"]),
     ("empty", ["o"]),
     ("empty container", ["tion"]),
     ("ems", ["mm","ms"]),
     ("en", ["n"]),
     ("enclosure", ["pen"]),
     ("encourage", ["egg"]),
     ("energy", ["go","e"]),
     ("engineer", ["ce","re"]),
     ("engineers", ["re","reme","ce"]),
     ("England", ["eng","e"]),
     ("English", ["eng","e"]),
     ("ens", ["ns","nn"]),
     ("envy", ["nv"]),
     ("epistle", ["ep"]),
     ("epsilon", ["e"]),
     ("era", ["ad"]),
     ("ergo", ["so"]),
     ("err", ["sin"]),
     ("es", ["s"]),
     ("ess", ["s"]),
     ("essay", ["sa","try"]),
     ("Essen", ["sn"]),
     ("Essex", ["sx"]),
     ("estimated time of arrival", ["eta"]),
     ("eta", ["e"]),
     ("ever", ["er","eer","ay","aye"]),
     ("everybody", ["all"]),
     ("everything", ["all"]),
     ("evil", ["sin"]),
     ("ewe", ["u"]),
     ("ewes", ["us","uu"]),
     ("ex", ["x"]),
     ("examination", ["test","a","o","oral"]),
     ("excel", ["xl"]),
     ("excellency", ["he"]),
     ("excited", ["up"]),
     ("Exe", ["x"]),
     ("exist", ["be"]),
     ("existing state", ["asis"]),
     ("exists", ["iss"]),
     ("exotic", ["et"]),
     ("expert", ["ace","dab","able","pro"]),
     ("explosive", ["tnt","he"]),
     ("extraterrestrial", ["et"]),
     ("extremity", ["toe"]),
     ("eye", ["i"]),
     ("eyes", ["ii","is"]),
     ("eyesore", ["stye"]),
     ("fabric", ["net"]),
     ("fabulous bird", ["roc"]),
     ("fabulous hare", ["loser"]),
     ("fabulous tortoise", ["winner"]),
     ("fahrenheit", ["f"]),
     ("fairly quiet", ["mp"]),
     ("fairy queen", ["mab"]),
     ("farad", ["f"]),
     ("farewell", ["vale"]),
     ("farthing", ["q","f"]),
     ("fashion", ["rage","ton"]),
     ("fashionable", ["in"]),
     ("fashionable people", ["ton"]),
     ("fast car", ["gt","rod"]),
     ("father", ["da","pa","dad","pop","time","fr"]),
     ("fathom", ["f"]),
     ("favoured", ["in"]),
     ("favourite", ["pet"]),
     ("feet", ["ft"]),
     ("fellow", ["f","man","gent","don"]),
     ("female", ["her","f","hen","she"]),
     ("female support", ["bra"]),
     ("female supporter", ["bra"]),
     ("feminine", ["f"]),
     ("fertiliser", ["nitre"]),
     ("field", ["ley","lea"]),
     ("fifty", ["a","l"]),
     ("fifty one", ["li"]),
     ("fifty pounds", ["ll"]),
     ("fifty thousand", ["l"]),
     ("fifty fifty", ["ll"]),
     ("fighter", ["man","gi"]),
     ("fighters", ["uff"]),
     ("filly", ["f"]),
     ("film", ["et","u","a","x"]),
     ("filthy place", ["sty"]),
     ("final letter", ["omega","z"]),
     ("final message", ["obit","rip"]),
     ("final word", ["amen","omega"]),
     ("fine", ["scot","ok","f"]),
     ("firm", ["fast","co"]),
     ("first", ["ist"]),
     ("first character", ["a","adam","alpha"]),
     ("first class", ["ai","a"]),
     ("first item in sale", ["loti"]),
     ("first lady", ["eve"]),
     ("first letter", ["a","alpha"]),
     ("first mate", ["eve"]),
     ("first murderer", ["cain"]),
     ("first person", ["me","adam","i"]),
     ("first victim", ["abel"]),
     ("fish", ["ide","id","eel","gar","cod","ling"]),
     ("five", ["v","e"]),
     ("five hundred", ["a","q","d"]),
     ("five hundred and one", ["di"]),
     ("five hundred thousand", ["q"]),
     ("five thousand", ["a","e"]),
     ("fleet", ["rn"]),
     ("fliers", ["raf"]),
     ("florida", ["fla"]),
     ("flourished", ["fl"]),
     ("flower", ["river","lis","rose"]),
     ("flowers", ["lei"]),
     ("fluorine", ["f"]),
     ("fly larva", ["bot"]),
     ("fly by night", ["bat","moth"]),
     ("folio", ["fo","f","fol"]),
     ("folios", ["ff"]),
     ("following", ["f"]),
     ("followings", ["ff"]),
     ("fool", ["ass"]),
     ("foot", ["f","ft"]),
     ("football", ["fa","ru"]),
     ("footnote", ["ps"]),
     ("for", ["pro"]),
     ("for all to see", ["u"]),
     ("for each", ["per"]),
     ("for example", ["eg","vg"]),
     ("for instance", ["eg"]),
     ("force", ["f","vis"]),
     ("forced", ["fz"]),
     ("foreign office", ["fo"]),
     ("former", ["ex"]),
     ("former squadron", ["red"]),
     ("forte", ["f"]),
     ("fortissimo", ["ff"]),
     ("forty", ["f"]),
     ("four", ["d","iv"]),
     ("four feet", ["ell"]),
     ("four hundred", ["p","g"]),
     ("four hundred thousand", ["p"]),
     ("four thousand", ["d"]),
     ("fourth man", ["seth"]),
     ("fox", ["tod"]),
     ("fragment", ["fr","ort"]),
     ("franc", ["fr"]),
     ("france", ["f"]),
     ("franco german agreement", ["ouija"]),
     ("free", ["rid"]),
     ("free of charge", ["foc"]),
     ("free on board", ["fob"]),
     ("free on rail", ["for"]),
     ("french", ["fr"]),
     ("french art", ["es"]),
     ("french king", ["sm","roi"]),
     ("french man", ["m","rene"]),
     ("french men", ["mm"]),
     ("french queen", ["reine","sm"]),
     ("french wine", ["vin"]),
     ("frequency", ["f"]),
     ("frequently", ["fr"]),
     ("friar", ["tuck"]),
     ("friday", ["f","man"]),
     ("from", ["ex","de"]),
     ("from the", ["dela","du"]),
     ("full moon", ["o"]),
     ("fuss", ["ado"]),
     ("gaelic", ["gael","erse"]),
     ("gallery", ["tate"]),
     ("game", ["nim"]),
     ("gamma", ["g"]),
     ("gamut", ["g"]),
     ("gangster", ["al"]),
     ("garden", ["eden","plot"]),
     ("gas", ["he","ne","f","cl","n","h","co","o"]),
     ("gauss", ["g"]),
     ("gee", ["g"]),
     ("gee gee", ["gg"]),
     ("general", ["grant","gen","goc","lee"]),
     ("general service", ["gs"]),
     ("general staff", ["gs"]),
     ("generation", ["era"]),
     ("genesis", ["gen"]),
     ("genius", ["id","ka"]),
     ("george", ["gr","g"]),
     ("georgia", ["ga"]),
     ("german", ["hun"]),
     ("german soldier", ["ss"]),
     ("germany", ["d","g"]),
     ("gift", ["gab"]),
     ("gin cocktail", ["ign","ing"]),
     ("girl", ["gal","g"]),
     ("girlfriend", ["gf"]),
     ("globe", ["o"]),
     ("god", ["ra","pan","lar"]),
     ("gods", ["s"]),
     ("goddess", ["athena","isis","ate","hebe"]),
     ("gold", ["bull","or","au"]),
     ("good", ["g","ai","pi","a"]),
     ("good book", ["ot","nt"]),
     ("good man", ["dean","st"]),
     ("goodbye", ["tata","vale"]),
     ("gorts men", ["bef"]),
     ("gotham", ["ny"]),
     ("government issue", ["gi"]),
     ("governor", ["he"]),
     ("gracious me", ["my"]),
     ("gradually", ["eric"]),
     ("graduate", ["ba","ma"]),
     ("grain", ["gr"]),
     ("gram", ["g"]),
     ("grammar", ["gr"]),
     ("gramme", ["g","gr"]),
     ("grand", ["g"]),
     ("graphite", ["kish"]),
     ("gravity", ["g"]),
     ("great britain", ["gb"]),
     ("greece", ["gr"]),
     ("greek", ["gr"]),
     ("greek character", ["nu","pi","mu"]),
     ("greek letter", ["nu","alpha","lambda","omega","pi","mu","beta","chi","phi","eta","iota"]),
     ("greeting", ["ave","hi"]),
     ("group", ["set"]),
     ("group of workers", ["bee"]),
     ("grouse", ["gr"]),
     ("guerrilla", ["che"]),
     ("guinea", ["gu","g"]),
     ("gulf", ["o","g"]),
     ("gun", ["sten","arm","lewis","bren","gat","maxim"]),
     ("gunmen", ["grs","ra"]),
     ("gunner", ["ra"]),
     ("gunners", ["ra"]),
     ("gym", ["pe"]),
     ("gypsy", ["rom","chal"]),
     ("gypsy woman", ["chai"]),
     ("hail", ["ave"]),
     ("hairdresser", ["comb"]),
     ("half", ["semi","hf","demi"]),
     ("half an em", ["n"]),
     ("half century", ["l"]),
     ("half day", ["pm","am"]),
     ("half ditch", ["ha"]),
     ("half dozen", ["vi"]),
     ("half dry", ["t"]),
     ("half minute", ["min","mo","ute"]),
     ("hand", ["man","h","l","ab","r"]),
     ("handwriting", ["ms"]),
     ("hard", ["h"]),
     ("hard ground", ["hearth"]),
     ("hard water", ["ice"]),
     ("has", ["s"]),
     ("head", ["ras","pate","ness"]),
     ("healer", ["dr"]),
     ("heart", ["h"]),
     ("hearts", ["h"]),
     ("heat", ["j"]),
     ("heath", ["ted"]),
     ("heather", ["ling"]),
     ("hebrew letter", ["lamed","vau","resh","aleph","beth","teth"]),
     ("hedge", ["haw"]),
     ("height", ["h"]),
     ("helium", ["he"]),
     ("hell", ["pit","tor","dis"]),
     ("hello", ["hi"]),
     ("henry", ["h"]),
     ("her majesty", ["hm"]),
     ("here in rome", ["hic"]),
     ("here is", ["hs"]),
     ("hesitation", ["er","um","ur"]),
     ("high class", ["ai","u","a"]),
     ("high explosive", ["he"]),
     ("high tension", ["ht"]),
     ("hill", ["mt","tor"]),
     ("hindrance", ["let"]),
     ("hire purchase", ["hp"]),
     ("his", ["s"]),
     ("his Excellency", ["he"]),
     ("his majesty", ["hm"]),
     ("hole", ["f","o"]),
     ("hollow", ["o"]),
     ("holy writ", ["nt","ot"]),
     ("home counties", ["se"]),
     ("honey", ["mel"]),
     ("honour", ["obe","ch","om"]),
     ("hoop", ["o"]),
     ("horse", ["cob","nag","arab","gg","h","barb","gee"]),
     ("horse race", ["oaks","national","derby"]),
     ("hospital", ["h"]),
     ("hot", ["h"]),
     ("hour", ["h","hr"]),
     ("house", ["semi","ho","co","cot","h"]),
     ("housekeeper", ["lar"]),
     ("humberside", ["ne"]),
     ("hundred", ["c","ton","ic"]),
     ("hundred and fifty", ["cl"]),
     ("hundred and one", ["ci"]),
     ("hundred and sixty", ["t"]),
     ("hundred and sixty thousand", ["t"]),
     ("hundred thousand", ["lac","c","lakh"]),
     ("hundreds", ["cs","d"]),
     ("hungary", ["h"]),
     ("hunter", ["orion"]),
     ("husband", ["h","man"]),
     ("hush", ["st","sh"]),
     ("hydrant", ["h"]),
     ("hydrogen", ["h"]),
     ("hymns", ["am"]),
     ("i", ["ane","an","ay","aye","eye","a"]),
     ("i am", ["am","iam","im"]),
     ("i had", ["id"]),
     ("i have", ["ive"]),
     ("i say", ["eye","aye"]),
     ("i see", ["ic"]),
     ("i shall", ["ill"]),
     ("i would", ["id"]),
     ("i, being french", ["je"]),
     ("iceland", ["is"]),
     ("identification", ["id"]),
     ("if", ["an"]),
     ("if it", ["ant"]),
     ("illegal army", ["ira","plo","eta"]),
     ("illinois", ["ill"]),
     ("illiterates signature", ["x"]),
     ("illness", ["flu"]),
     ("image building", ["pr"]),
     ("imaginary number", ["i"]),
     ("in bed", ["bed"]),
     ("in charge", ["ic"]),
     ("in court", ["up"]),
     ("in fashion", ["in"]),
     ("in good condition", ["go"]),
     ("in paris, i", ["je"]),
     ("in the afternoon", ["pm"]),
     ("in the main", ["deep"]),
     ("in the modern age", ["ad"]),
     ("in the morning", ["am"]),
     ("in the same place", ["ibid","ib"]),
     ("in the style of", ["ala"]),
     ("in the year of our lord", ["ad"]),
     ("indeed", ["deed"]),
     ("indefinite number", ["n","no"]),
     ("india", ["ind"]),
     ("individual", ["i"]),
     ("individuality", ["ka"]),
     ("inductance", ["l"]),
     ("inexperienced driver", ["l"]),
     ("infantry", ["foot"]),
     ("inferior", ["b"]),
     ("inferior horse", ["tit"]),
     ("information", ["gen"]),
     ("informer", ["nose","grass"]),
     ("inn", ["bar"]),
     ("instinct", ["id"]),
     ("integers", ["z"]),
     ("intended", ["ment"]),
     ("international", ["cap","un"]),
     ("international organisation", ["uno"]),
     ("invariably", ["eer"]),
     ("inventor", ["edison"]),
     ("iodine", ["i"]),
     ("iota", ["i"]),
     ("iowa", ["ia"]),
     ("iran", ["ir"]),
     ("ireland", ["irl"]),
     ("irish house", ["dail"]),
     ("irish police", ["ruc"]),
     ("iron", ["fe"]),
     ("is", ["est","s"]),
     ("is able to", ["can"]),
     ("island", ["ait","iom","is","man","eyot","i","inch"]),
     ("isle of man", ["iom"]),
     ("israel", ["il"]),
     ("issue", ["son"]),
     ("it", ["sa","a"]),
     ("italian", ["it"]),
     ("italian banker", ["po"]),
     ("italian flower", ["po"]),
     ("italy", ["i"]),
     ("ivy", ["iv"]),
     ("izzard", ["z"]),
     ("Jack", ["j"]),
     ("jade", ["yu"]),
     ("Jamaica", ["ja"]),
     ("jammed cylinder", ["swiss roll"]),
     ("Japan", ["j"]),
     ("jay", ["j"]),
     ("jazz fan", ["cat"]),
     ("jelly", ["gel"]),
     ("jolly", ["rm"]),
     ("joule", ["j"]),
     ("journalist", ["ed"]),
     ("joyful cry", ["io"]),
     ("judge", ["j"]),
     ("junction", ["t"]),
     ("justice", ["j"]),
     ("kale", ["kl"]),
     ("kappa", ["k"]),
     ("kay", ["k"]),
     ("kelt", ["q","p"]),
     ("kelvin", ["k"]),
     ("kentucky", ["ky"]),
     ("kewpie", ["qp"]),
     ("key", ["c","f","d","e","a","g","b"]),
     ("khmer republic", ["k"]),
     ("kick off", ["ko"]),
     ("killer", ["cain"]),
     ("kilo", ["k"]),
     ("kilometre", ["km"]),
     ("king", ["k","gr","hm","lear","cr","roi","r","sm","er"]),
     ("king emperor", ["ri"]),
     ("king george", ["gr"]),
     ("kirkpatrick", ["k"]),
     ("kiss", ["x"]),
     ("knave", ["j"]),
     ("knew", ["wist"]),
     ("knight", ["kt","k","sir","n"]),
     ("knock out", ["ko"]),
     ("koechel", ["k"]),
     ("koppa", ["q"]),
     ("krypton", ["kr"]),
     ("label", ["tag","tab"]),
     ("laboratory", ["lab"]),
     ("labour", ["lab","l"]),
     ("lady", ["eve","dame","she"]),
     ("lake", ["erie","loch","l"]),
     ("lambda", ["l"]),
     ("lambert", ["l"]),
     ("landline", ["ry","br","rly"]),
     ("large", ["l"]),
     ("large amount", ["ton","lot"]),
     ("large letters", ["os"]),
     ("largesse", ["s"]),
     ("last character", ["z"]),
     ("last letter", ["omega","z"]),
     ("last month", ["ult","dec"]),
     ("last word", ["obit","rip","amen"]),
     ("late", ["ex"]),
     ("latin", ["l"]),
     ("latitude", ["l"]),
     ("laugh", ["haha","hehe","ha"]),
     ("lawgiver", ["moses"]),
     ("lawman", ["earp","bl","da"]),
     ("lawrence", ["te"]),
     ("lawyer", ["bl","da"]),
     ("lawyers", ["bar"]),
     ("layer", ["hen","e"]),
     ("lead", ["pb"]),
     ("leading", ["noi"]),
     ("league", ["l"]),
     ("learner", ["l"]),
     ("learning", ["l"]),
     ("leave", ["part"]),
     ("leaves", ["tea"]),
     ("left", ["l","port"]),
     ("left hand", ["vo","lh"]),
     ("leftist", ["red"]),
     ("leg", ["on"]),
     ("legal document", ["deed"]),
     ("legate", ["he"]),
     ("length", ["ell","l"]),
     ("lettuce", ["cos"]),
     ("level", ["a","y"]),
     ("liberal", ["l","lib"]),
     ("libya", ["lar"]),
     ("licentiate", ["l"]),
     ("lieutenant", ["lt"]),
     ("life symbol", ["ankh"]),
     ("light", ["very"]),
     ("like", ["as"]),
     ("limb", ["leg","arm"]),
     ("lincoln", ["abe"]),
     ("line", ["row","l","i","ry"]),
     ("liner", ["ss"]),
     ("lines", ["ry","br","rly"]),
     ("lira", ["l"]),
     ("lire", ["l"]),
     ("listener", ["ear"]),
     ("litre", ["l"]),
     ("little", ["wee"]),
     ("little devil", ["imp"]),
     ("little horse", ["gg","ned","gee","nag"]),
     ("little way", ["st","rd","ry"]),
     ("little woman", ["jo"]),
     ("live", ["l","be"]),
     ("lived so long", ["av"]),
     ("loaded", ["lit"]),
     ("local", ["ph","inn","pub"]),
     ("loch", ["ness"]),
     ("lock keeper", ["hair net"]),
     ("logarithm base", ["e"]),
     ("london area", ["se"]),
     ("london district", ["ec"]),
     ("long", ["l"]),
     ("long playing", ["lp"]),
     ("long time", ["age"]),
     ("look", ["v","see","la","vide","lo"]),
     ("looker", ["eye"]),
     ("loop", ["o"]),
     ("los angeles", ["la"]),
     ("lot", ["d","m","c"]),
     ("loud", ["f"]),
     ("louisiana", ["la"]),
     ("love", ["o","nil"]),
     ("low", ["moo"]),
     ("low down", ["gen"]),
     ("low grade", ["e"]),
     ("lower", ["cow"]),
     ("lumen", ["l"]),
     ("luminance", ["l"]),
     ("lunchtime", ["one","i"]),
     ("luxembourg", ["l"]),
     ("magnesium", ["mg"]),
     ("magnetic flux", ["b"]),
     ("maiden", ["over","io","m"]),
     ("maiden over", ["m"]),
     ("mailboat", ["rms"]),
     ("main", ["sea","deep"]),
     ("main road", ["ai","mi"]),
     ("male", ["m","he","him"]),
     ("malta", ["m"]),
     ("man", ["isle","iom","g","vir","m"]),
     ("manage", ["run"]),
     ("managed", ["ran"]),
     ("management", ["admin"]),
     ("manuscript", ["ms"]),
     ("manuscripts", ["mss"]),
     ("many", ["l","c","m","d"]),
     ("mare", ["m"]),
     ("marine", ["jolly","rm"]),
     ("mark", ["m","d","dm"]),
     ("mark of the beast", ["mb"]),
     ("married", ["m"]),
     ("marshal", ["ney"]),
     ("masculine", ["m"]),
     ("mass", ["m"]),
     ("massachusetts", ["mass"]),
     ("master", ["ma","m"]),
     ("master of arts", ["ma"]),
     ("master of ceremonies", ["mc"]),
     ("match", ["test"]),
     ("maths function", ["log","tan","sine"]),
     ("mature", ["age"]),
     ("mayfair", ["wi"]),
     ("meal ticket", ["lv"]),
     ("meant", ["ment"]),
     ("measure", ["ell","ft","m","em","el","en","yd","y"]),
     ("medal", ["td","mc","mm"]),
     ("meeting", ["agm"]),
     ("member", ["leg","arm","toe","m","mp"]),
     ("member of parliament", ["mp"]),
     ("memory", ["rom","ram"]),
     ("men", ["or"]),
     ("merchant navy", ["mn"]),
     ("merchant of Venice", ["polo"]),
     ("mercury", ["hg"]),
     ("merseyside", ["nw"]),
     ("meso ", ["m"]),
     ("meta ", ["m"]),
     ("meter", ["m"]),
     ("metre", ["m"]),
     ("midday", ["a","m","n"]),
     ("midnight", ["g"]),
     ("mile", ["m"]),
     ("military police", ["mp"]),
     ("millers corn", ["grist"]),
     ("miners", ["num"]),
     ("minor", ["wee"]),
     ("misanthrope", ["timon"]),
     ("mischevious child", ["imp"]),
     ("mischief", ["ate"]),
     ("missiles", ["ammo"]),
     ("mississippi", ["miss"]),
     ("missouri", ["mo"]),
     ("mister", ["mr"]),
     ("model", ["t"]),
     ("modern journalism", ["eng"]),
     ("modern times", ["ad"]),
     ("modulus", ["m"]),
     ("mole", ["spy","pier"]),
     ("monarch", ["k","r","er"]),
     ("monday", ["mon","m"]),
     ("money", ["tin","cent","m","l","brass"]),
     ("monsieur", ["m"]),
     ("monstrous regiment", ["women"]),
     ("month", ["mo","r","m"]),
     ("months", ["mos"]),
     ("moon", ["m"]),
     ("morning", ["am"]),
     ("moth", ["y"]),
     ("mother", ["mum","ma","dam","mam"]),
     ("motor race", ["carnation"]),
     ("motoring organisation", ["aa","rac"]),
     ("motorway", ["m","mi"]),
     ("mountain", ["mt","tor","alp"]),
     ("mountain retreat", ["pla"]),
     ("mountaineer", ["sherpa"]),
     ("mounted", ["up"]),
     ("mounted police", ["mp"]),
     ("mountie", ["mp"]),
     ("mounties", ["mp"]),
     ("mouthpiece", ["lips"]),
     ("mozarts works", ["k"]),
     ("mu", ["m"]),
     ("murder victim", ["abel"]),
     ("murderer", ["cain"]),
     ("music school", ["ram"]),
     ("muslim leader", ["aga"]),
     ("name", ["n"]),
     ("name unknown", ["nu"]),
     ("named", ["dit"]),
     ("namely", ["sc"]),
     ("national", ["n"]),
     ("nationalist", ["n"]),
     ("nationalists", ["sdp"]),
     ("native", ["abo"]),
     ("naught", ["o"]),
     ("naval commander", ["corn"]),
     ("navy", ["rn"]),
     ("near", ["nie"]),
     ("neat", ["cow","ox","kine","cattle"]),
     ("neat sound", ["lowing","moo"]),
     ("neck", ["col","v"]),
     ("neckline", ["v"]),
     ("neon", ["ne"]),
     ("neper", ["n"]),
     ("network", ["rete"]),
     ("neuter", ["n"]),
     ("neutral", ["n"]),
     ("never never", ["hp"]),
     ("new", ["n"]),
     ("new driver", ["l"]),
     ("new Jersey", ["nj"]),
     ("new orleans", ["no"]),
     ("new testament", ["nt"]),
     ("new York", ["gotham","ny"]),
     ("new York opera", ["met"]),
     ("newspaper", ["sun","ft"]),
     ("newton", ["n"]),
     ("next month", ["prox"]),
     ("nickel", ["ni"]),
     ("nil", ["o"]),
     ("nine", ["ix"]),
     ("ninety", ["xc","n","q"]),
     ("ninety nine", ["ic"]),
     ("ninety thousand", ["n","q"]),
     ("nitrogen", ["n"]),
     ("no", ["o","nae","non","na"]),
     ("no date", ["nd"]),
     ("no good", ["ng","us"]),
     ("no one", ["noi"]),
     ("no way", ["ord"]),
     ("nobleman", ["don"]),
     ("noisy", ["f"]),
     ("non commissioned officer", ["rsm","sgt","sm","nco"]),
     ("non commissioned officers", ["or"]),
     ("noon", ["n","m"]),
     ("north", ["n"]),
     ("north america", ["na"]),
     ("north Dakota", ["nd"]),
     ("north pole", ["np"]),
     ("northeastern", ["ne"]),
     ("northwestern", ["nw"]),
     ("north east", ["ne"]),
     ("north west", ["nw"]),
     ("north north east", ["nne"]),
     ("north north west", ["nnw"]),
     ("northern", ["n"]),
     ("northern ireland", ["ni"]),
     ("northern territories", ["nt"]),
     ("norway", ["n"]),
     ("not", ["nae","na","ne"]),
     ("not at home", ["out"]),
     ("not clear", ["nl"]),
     ("not dated", ["nd"]),
     ("not far", ["nl"]),
     ("not out", ["no","in"]),
     ("not permitted", ["nl"]),
     ("not specific", ["ns"]),
     ("nota bene", ["nb"]),
     ("notch", ["v"]),
     ("note", ["nb","lah","a","me","re","tic","soh","doh","te","g","ti","la","n","c","b","f","si","d","mi","fah","so","e","do","fa","ut","sol"]),
     ("nothing", ["o","nil"]),
     ("nothing to america", ["ous"]),
     ("notice", ["ack", "d","ad"]),
     ("nought", ["o"]),
     ("noun", ["n"]),
     ("novel", ["she"]),
     ("novice", ["l"]),
     ("now", ["anon","ad"]),
     ("nowadays", ["ad"]),
     ("nu", ["n"]),
     ("number", ["n","ether","d","pin","no"]),
     ("number one", ["noi","ein","uno","i","un","adam","une","me","una"]),
     ("number one returning", ["ion"]),
     ("number plate", ["l"]),
     ("nurse", ["srn","vad"]),
     ("objector", ["co"]),
     ("occupational therapy", ["ot"]),
     ("odds", ["sp"]),
     ("of", ["de"]),
     ("of the", ["dela","del","du","des"]),
     ("offensive", ["tet"]),
     ("office", ["loo","den"]),
     ("officer", ["co","lt"]),
     ("officer commanding", ["oc"]),
     ("officer in charge", ["oic"]),
     ("ogee", ["og"]),
     ("oh", ["o"]),
     ("oh, why", ["oy"]),
     ("ohio", ["o"]),
     ("ohs", ["oo","os"]),
     ("okay", ["ok"]),
     ("old age", ["eld"]),
     ("old bob", ["s"]),
     ("old boy", ["ob"]),
     ("old city", ["ur","troy"]),
     ("old contemptibles", ["bef"]),
     ("old English", ["oe"]),
     ("old Etonian", ["oe"]),
     ("old fiddle", ["gue","gu"]),
     ("old fighter", ["gladiator"]),
     ("old goat", ["gate"]),
     ("old injury", ["teen","tene"]),
     ("old irish magistrate", ["rm"]),
     ("old king", ["offa","cole","lud"]),
     ("old man", ["dad","pop","pa"]),
     ("old paint", ["limn"]),
     ("old penny", ["d"]),
     ("old people", ["iceni"]),
     ("old prime minister", ["pitt","eden"]),
     ("old railway", ["sr","lner"]),
     ("old scholar", ["erasmus"]),
     ("old shilling", ["s","bob"]),
     ("old ship", ["argo"]),
     ("old style", ["os"]),
     ("old testament", ["ot"]),
     ("old thing", ["res"]),
     ("old way", ["via"]),
     ("old way of dating", ["auc"]),
     ("old wedding", ["bridal"]),
     ("old woman", ["ma"]),
     ("omega", ["z"]),
     ("omicron", ["o"]),
     ("on", ["leg"]),
     ("on purpose", ["ment"]),
     ("on the menu", ["on"]),
     ("on the wagon", ["tt"]),
     ("on view to all", ["u"]),
     ("one", ["i","un","an","a","j","ane","ace"]),
     ("one answer", ["ians"]),
     ("one fifteen", ["aside"]),
     ("one hundred and fifty", ["y"]),
     ("one hundred and fifty thousand", ["y"]),
     ("one member", ["amp","imp"]),
     ("one pound", ["alb","al","il","l","lb","ilb"]),
     ("one thousand five hundred", ["md"]),
     ("one time", ["ex"]),
     ("ones", ["as","is"]),
     ("open university", ["ou"]),
     ("opener", ["key"]),
     ("opening", ["o"]),
     ("operating", ["on"]),
     ("operation", ["op"]),
     ("opposing", ["v"]),
     ("opposite", ["op"]),
     ("opus", ["op"]),
     ("orb", ["o"]),
     ("orchestra", ["lso"]),
     ("order", ["obe","ch","po","om"]),
     ("ordinary seaman", ["os"]),
     ("organ", ["ear"]),
     ("orient", ["e"]),
     ("oriental", ["e","ine"]),
     ("ortho ", ["o"]),
     ("otorhinolaryngology", ["ent"]),
     ("ought", ["o"]),
     ("ounce", ["oz"]),
     ("our era", ["ad"]),
     ("our islands", ["gb"]),
     ("our man", ["he"]),
     ("our time", ["ad"]),
     ("out of print", ["op"]),
     ("outdated hairdo", ["da"]),
     ("outlaw", ["ban"]),
     ("outsize", ["os"]),
     ("over", ["supra","re"]),
     ("overhead railway", ["l"]),
     ("owe", ["o"]),
     ("owes", ["os","oo"]),
     ("own", ["ain"]),
     ("own goal", ["og"]),
     ("ox", ["neat","kine"]),
     ("oxford dreamer", ["spire"]),
     ("oxygen", ["o"]),
     ("page", ["p"]),
     ("pages", ["pp"]),
     ("painter", ["ra","ara","ney","pra"]),
     ("painting", ["art"]),
     ("pair", ["pr"]),
     ("palladium", ["po"]),
     ("panama", ["pa"]),
     ("paper", ["ms","b","a"]),
     ("papers", ["mss"]),
     ("paradise", ["eden"]),
     ("paragon", ["saint","s","st"]),
     ("park", ["p"]),
     ("parking", ["p"]),
     ("part", ["pt"]),
     ("part of bible", ["nt","ot"]),
     ("part of collar", ["s"]),
     ("participle", ["p"]),
     ("particle", ["x"]),
     ("partnership", ["we","sn","ew","ns"]),
     ("party", ["con","lib","do","lab","tory"]),
     ("pass", ["col"]),
     ("pawn", ["p"]),
     ("paying guest", ["pg"]),
     ("pea", ["p"]),
     ("peacekeepers", ["un"]),
     ("peacemakers", ["acas"]),
     ("peak", ["alp"]),
     ("peas", ["pp","ps"]),
     ("peavy", ["pv"]),
     ("pedal", ["p"]),
     ("pee", ["p"]),
     ("pees", ["pp","ps"]),
     ("peg", ["tee","t","p"]),
     ("pellet", ["o"]),
     ("pen", ["j"]),
     ("penny", ["d","p"]),
     ("people", ["race","men","nation"]),
     ("per", ["a"]),
     ("perfect letter", ["t"]),
     ("performance", ["act"]),
     ("performing", ["on"]),
     ("period", ["age","bc","ad"]),
     ("permit", ["let"]),
     ("permitted", ["let"]),
     ("peru", ["pe"]),
     ("philosopher", ["plato","bacon"]),
     ("phosphorous", ["p"]),
     ("physical education", ["pe"]),
     ("physical training", ["pt"]),
     ("pi", ["p"]),
     ("pianissimo", ["pp"]),
     ("piano", ["p"]),
     ("piece", ["bit","pawn","man"]),
     ("pilot", ["george","ace"]),
     ("pint", ["p","pt"]),
     ("plancks constant", ["h"]),
     ("plate", ["t"]),
     ("platinum", ["pt"]),
     ("play", ["noh","no"]),
     ("playing", ["in","on"]),
     ("plotters street", ["cato"]),
     ("pluto", ["dis"]),
     ("pms address", ["ten","x"]),
     ("poet", ["ae"]),
     ("point", ["head","e","ness","tor","s","pt","w","n"]),
     ("poise", ["p"]),
     ("poland", ["pl"]),
     ("pole", ["rod","po","sp","np","s","n"]),
     ("police", ["force","met","cid"]),
     ("policeman", ["pc","mp"]),
     ("politician", ["con","mp","lib","lab","tory"]),
     ("poor actor", ["ham"]),
     ("poor horse", ["tit","rosinante"]),
     ("port", ["rio","l","aden"]),
     ("port authority", ["pla"]),
     ("portugal", ["p"]),
     ("posh", ["u"]),
     ("post office", ["po"]),
     ("post town", ["pt"]),
     ("postscript", ["ps"]),
     ("potassium", ["k"]),
     ("pound", ["lb","lam","ezra","l"]),
     ("power", ["p","vis"]),
     ("practice", ["use"]),
     ("practise", ["use"]),
     ("present day", ["ad"]),
     ("preservationists", ["nt"]),
     ("president", ["pres","p","pr","chair"]),
     ("pretty girl", ["cutie","dish"]),
     ("prevent", ["bar"]),
     ("price", ["pr"]),
     ("priest", ["pr","eli","abbe","rev","cure"]),
     ("primate", ["ape"]),
     ("prime minister", ["pm"]),
     ("primitive", ["ur"]),
     ("prince", ["p","pr","ras"]),
     ("princess", ["ina","regan","ida","anne","di"]),
     ("printers measure", ["em","el","en"]),
     ("prison", ["bird","jug","quad","cooler","pen","nick","hock","stir","can"]),
     ("private", ["gi"]),
     ("prohibition", ["ban"]),
     ("prominence", ["tor"]),
     ("promises to pay", ["ious"]),
     ("promotion", ["ad"]),
     ("prophet", ["eli"]),
     ("provided", ["if"]),
     ("providing", ["if"]),
     ("psychotic state", ["dt"]),
     ("public relations", ["pr"]),
     ("public relations officer", ["pro"]),
     ("puerto rico", ["pr"]),
     ("puff", ["ad"]),
     ("pupil", ["l"]),
     ("pure", ["net"]),
     ("put", ["set"]),
     ("put on", ["don"]),
     ("qE", ["er"]),
     ("quality", ["q"]),
     ("quart", ["qt","qu"]),
     ("quarter", ["e","s","sw","w","n","nw","ne","se"]),
     ("quebec", ["q"]),
     ("queen", ["r","hm","q","qu","er","mab","bess"]),
     ("queensland", ["q"]),
     ("query", ["q"]),
     ("question", ["q"]),
     ("queue", ["cue","q"]),
     ("quiet", ["p","mum","sh","qt"]),
     ("quintal", ["q"]),
     ("rabbi", ["r"]),
     ("rabbit", ["brer"]),
     ("race", ["nation","tt"]),
     ("radius", ["r"]),
     ("rage", ["ire"]),
     ("rail", ["ry","t"]),
     ("railway", ["br","rly","l","ry"]),
     ("railways", ["br"]),
     ("rain", ["r"]),
     ("rand", ["r"]),
     ("rare", ["r"]),
     ("rate", ["mph"]),
     ("rating", ["ab"]),
     ("rational numbers", ["q"]),
     ("ray", ["x"]),
     ("reading", ["r"]),
     ("ready", ["set","go"]),
     ("real numbers", ["r"]),
     ("reaumur", ["r"]),
     ("recipe", ["r","rec"]),
     ("record", ["log","disc","entry","cd","lp","ep"]),
     ("rector", ["r"]),
     ("refusal", ["no"]),
     ("regina", ["r"]),
     ("relation", ["sib"]),
     ("relationship", ["pi"]),
     ("relative", ["rel"]),
     ("religious", ["pi"]),
     ("religious education", ["re"]),
     ("remains", ["ash"]),
     ("reported", ["dit"]),
     ("representative", ["mp"]),
     ("republican", ["r"]),
     ("reserves", ["ta"]),
     ("resident magistrate", ["rm"]),
     ("resistance", ["r"]),
     ("restrain", ["dam"]),
     ("retreat", ["den"]),
     ("rev up", ["ver"]),
     ("revolutionary", ["che","red"]),
     ("rex", ["r"]),
     ("rho", ["r"]),
     ("rhode island", ["ri"]),
     ("riding", ["up"]),
     ("right", ["r","rt"]),
     ("right hand", ["rh","ro"]),
     ("right reverend", ["rr"]),
     ("ring", ["disc","o"]),
     ("ring road", ["ord"]),
     ("river", ["po","isis","ure","cam","ea","dee","r","alph","aire","fal","tay","exe","ouse","tees"]),
     ("road", ["ave","r","a","rd","st"]),
     ("rolls royce", ["rr"]),
     ("roman", ["vir"]),
     ("roman catholic", ["rc"]),
     ("roman people", ["pr"]),
     ("romania", ["r"]),
     ("romans", ["rom","pr"]),
     ("romeo", ["r"]),
     ("rontgen unit", ["r"]),
     ("roof", ["m"]),
     ("rook", ["r"]),
     ("roughly", ["c","ca"]),
     ("round", ["o"]),
     ("row", ["ado","tier"]),
     ("rowing boat", ["eight","four"]),
     ("royal", ["r"]),
     ("royal academician", ["ra"]),
     ("royal academy", ["ra"]),
     ("royal artillery", ["ra"]),
     ("royal badge", ["er"]),
     ("royal Engineer", ["re"]),
     ("royal Engineers", ["re"]),
     ("royal marine", ["rm"]),
     ("royal marines", ["rm"]),
     ("royal navy", ["rn"]),
     ("rubber", ["ule"]),
     ("rugby", ["ru"]),
     ("run", ["r"]),
     ("runner", ["river"]),
     ("running", ["admin"]),
     ("running water", ["ea"]),
     ("russian river", ["ob"]),
     ("sabbath", ["s"]),
     ("said", ["idem","dit"]),
     ("sailor", ["tar","os","ab","jack"]),
     ("sailors", ["rn"]),
     ("saint", ["s","st"]),
     ("saints", ["sts","ss"]),
     ("salesman", ["rep"]),
     ("salt", ["ab","jack","tar"]),
     ("same", ["do","id"]),
     ("same place", ["ib"]),
     ("sandhurst", ["rma"]),
     ("sapper", ["re"]),
     ("sappers", ["re"]),
     ("saturday", ["s","sat"]),
     ("save", ["bar"]),
     ("say", ["dit"]),
     ("scab", ["rat"]),
     ("scarlattis works", ["k"]),
     ("schmieder", ["s"]),
     ("scholar", ["ma","ba"]),
     ("school", ["eton"]),
     ("schuberts works", ["d"]),
     ("science centre", ["lab"]),
     ("scope, plenty of", ["az"]),
     ("scorer", ["composer"]),
     ("scot", ["mon","jock","mac","ian"]),
     ("scotsman", ["jock","mac","ian","mon"]),
     ("screecher", ["swift"]),
     ("scriptures", ["nt","ot"]),
     ("scruple", ["scr"]),
     ("sea", ["main","c","mer","deep"]),
     ("seabee", ["cb"]),
     ("seaman", ["ab","jack","tar"]),
     ("seas", ["cc","cs"]),
     ("second", ["sec","mo","b","s"]),
     ("second child", ["abel"]),
     ("second class", ["b"]),
     ("second letter", ["b"]),
     ("second thoughts", ["ps"]),
     ("second hand", ["sh"]),
     ("secret service", ["cia"]),
     ("secretary", ["temp"]),
     ("see", ["vid","c","v","vide","lo","ely"]),
     ("see why", ["cy"]),
     ("see you", ["cu"]),
     ("seedy", ["cd"]),
     ("seer", ["eye","optic"]),
     ("self confessed", ["iam","am","im"]),
     ("self contained", ["sc"]),
     ("senior", ["sr"]),
     ("sergeant", ["nco","sgt"]),
     ("service", ["rn","rm","ace","raf","let","mass"]),
     ("serving man", ["gi"]),
     ("settled", ["lit"]),
     ("seven", ["s","z"]),
     ("seven thousand", ["s","z"]),
     ("sex appeal", ["it","sa"]),
     ("shares", ["scrip"]),
     ("shark", ["nurse"]),
     ("sheep", ["ram"]),
     ("shilling", ["s"]),
     ("ship", ["ss"]),
     ("shipping company", ["line"]),
     ("shirt", ["t"]),
     ("short answer", ["ans"]),
     ("short break", ["hol"]),
     ("short time", ["t","sec","mo"]),
     ("show ring", ["manifesto"]),
     ("side", ["xi","l","s","r","xv"]),
     ("siemens", ["s"]),
     ("sign", ["v"]),
     ("sign of love", ["x"]),
     ("sign of the times", ["x"]),
     ("silence", ["mum","st","sh","tace"]),
     ("silicon", ["si"]),
     ("silver", ["ag"]),
     ("simple", ["herb"]),
     ("sin", ["err"]),
     ("single", ["i"]),
     ("sister", ["sis","s"]),
     ("six", ["vi"]),
     ("six footer", ["ant","bee","insect"]),
     ("sixpence", ["vid","vip"]),
     ("sixth sense", ["esp"]),
     ("skill", ["art"]),
     ("skipping", ["omitting"]),
     ("sling", ["ign","ing"]),
     ("sloth", ["ai"]),
     ("small", ["tiny","wee"]),
     ("small capitals", ["sc"]),
     ("small change", ["p"]),
     ("small illustration", ["fig"]),
     ("small measure", ["cc","em","el","en"]),
     ("small quantity", ["cc"]),
     ("small square", ["m","em"]),
     ("small weight", ["wt","oz","gr","ct"]),
     ("smuggle", ["run"]),
     ("smuggled", ["ran"]),
     ("snake", ["asp","boa"]),
     ("snoring", ["zz"]),
     ("snow", ["s"]),
     ("so", ["ergo"]),
     ("soak", ["ret"]),
     ("sober", ["tt"]),
     ("soccer blunder", ["og"]),
     ("social worker", ["ant","bee"]),
     ("socialist", ["red"]),
     ("socially acceptable", ["u"]),
     ("society", ["s"]),
     ("sodium", ["na"]),
     ("soft", ["p","b","pp"]),
     ("softly", ["p","pp"]),
     ("soldier", ["ra","re","ta","ant","man","ney","gi"]),
     ("soldiers", ["ra","re","men","ta","sas","impi","or","gis"]),
     ("solver", ["you"]),
     ("some french", ["du","des"]),
     ("son", ["s"]),
     ("song", ["lay","aria","air"]),
     ("sons", ["s"]),
     ("soprano", ["sop","s"]),
     ("sound of sleep", ["z"]),
     ("sound of snoring", ["zz"]),
     ("source", ["parent"]),
     ("south", ["s"]),
     ("southeastern", ["se"]),
     ("southwestern", ["sw"]),
     ("south east", ["se"]),
     ("south west", ["sw"]),
     ("south south east", ["sse"]),
     ("south south west", ["ssw"]),
     ("south africa", ["sa"]),
     ("south america", ["sa"]),
     ("south Dakota", ["sd"]),
     ("south island", ["si"]),
     ("south pole", ["sp"]),
     ("southern", ["s"]),
     ("sovereign", ["l"]),
     ("soviet union", ["ussr","su"]),
     ("space", ["s"]),
     ("spade", ["s"]),
     ("spades", ["s"]),
     ("spain", ["e"]),
     ("spangle", ["o"]),
     ("spanish hero", ["cid"]),
     ("spasm", ["tic"]),
     ("speakers", ["lips"]),
     ("special", ["s"]),
     ("species", ["sp"]),
     ("specifically", ["as","sc"]),
     ("spectacles", ["oo"]),
     ("spectator", ["eye"]),
     ("speculator", ["stag","bear"]),
     ("speed", ["rate","mph"]),
     ("speed of light", ["c"]),
     ("spies", ["cia"]),
     ("spike", ["ear"]),
     ("sports car", ["rod","gt"]),
     ("spot marked", ["x"]),
     ("spring", ["spa","c"]),
     ("spy", ["agent"]),
     ("spymaster", ["m"]),
     ("square", ["t","s"]),
     ("square root of  1", ["j","i"]),
     ("stand in", ["sub"]),
     ("standard", ["par"]),
     ("starting price", ["sp"]),
     ("steamship", ["ss"]),
     ("step", ["pas"]),
     ("stokes", ["s","st"]),
     ("stone", ["st"]),
     ("stop", ["colon","pt"]),
     ("straight line", ["i"]),
     ("street", ["rue","st"]),
     ("strikebreaker", ["rat"]),
     ("string", ["g","d","a","e"]),
     ("strings", ["d","a","g"]),
     ("strong", ["f"]),
     ("student", ["l"]),
     ("students", ["nus"]),
     ("students union", ["nus"]),
     ("study", ["den","con"]),
     ("stumped", ["st"]),
     ("stunner", ["ko"]),
     ("submariner", ["nemo"]),
     ("substitute", ["sub"]),
     ("succeeded", ["s"]),
     ("success", ["go"]),
     ("suit", ["g"]),
     ("suitable for children", ["u"]),
     ("sulphur", ["s"]),
     ("sum", ["add"]),
     ("summer", ["bst"]),
     ("summer time", ["bst"]),
     ("sun", ["s","ra"]),
     ("sun god", ["ra"]),
     ("sun god", ["sol"]),
     ("sunday school", ["ss"]),
     ("superior", ["u","up"]),
     ("support", ["bra","leg"]),
     ("supposed force", ["od"]),
     ("surgeon", ["vet"]),
     ("sweden", ["s"]),
     ("sweetheart", ["jo"]),
     ("swimmer", ["eel","ling","cod"]),
     ("swindle", ["con"]),
     ("switzerland", ["ch"]),
     ("take", ["r","rec"]),
     ("tales", ["ana"]),
     ("tanner", ["vid","vip"]),
     ("tantalus prisoner", ["decanter"]),
     ("tanzania", ["eat"]),
     ("tap", ["h","c"]),
     ("tar", ["ab"]),
     ("tau", ["t"]),
     ("tax", ["scot","vat"]),
     ("tax officer", ["to"]),
     ("te", ["t"]),
     ("tea", ["cha","t"]),
     ("tea time", ["iv"]),
     ("teachers", ["nut"]),
     ("team", ["xv","xi","side"]),
     ("teas", ["ts","tt"]),
     ("tee", ["t","peg"]),
     ("teepee", ["tp"]),
     ("tees", ["ts","tt"]),
     ("teetotal", ["tt"]),
     ("teetotaller", ["tt"]),
     ("telepathy", ["esp"]),
     ("ten", ["io","x"]),
     ("ten thousand", ["x"]),
     ("tenor", ["t"]),
     ("terriers", ["ta"]),
     ("territorial army", ["ta"]),
     ("territorials", ["ta"]),
     ("terrorists", ["ira","plo","provos","eta"]),
     ("tesla", ["t"]),
     ("test", ["oral","mot"]),
     ("text", ["ms"]),
     ("thailand", ["t"]),
     ("thank you", ["ta","tt"]),
     ("thanks", ["ta"]),
     ("that", ["yt","id"]),
     ("that is", ["ie","sc"]),
     ("thats", ["ie"]),
     ("the", ["der","el","t","la","die","ye","das","le","il"]),
     ("the french", ["le","la","les"]),
     ("the german", ["die","der", "das"]),
     ("the italian", ["il","la"]),
     ("the greatest", ["ali"]),
     ("the man", ["he"]),
     ("the pope", ["hh"]),
     ("the same", ["do"]),
     ("the spanish", ["la","el","los"]),
     ("the thing", ["it","play"]),
     ("the woman", ["she"]),
     ("the womans", ["her"]),
     ("them", ["em"]),
     ("theologian", ["bd","dd"]),
     ("theory", ["ism"]),
     ("therefore", ["so"]),
     ("third man", ["abel"]),
     ("thirty seconds", ["min"]),
     ("this", ["hic","cet","ce"]),
     ("this country", ["uk"]),
     ("this era", ["ad"]),
     ("this island", ["uk"]),
     ("this month", ["inst"]),
     ("this year", ["ha"]),
     ("thoroughfare", ["st"]),
     ("thousand", ["g","x","k","m"]),
     ("a thousand", ["g","x","k","m"]),
     ("three", ["tri","ter"]),
     ("three hundred", ["b"]),
     ("three thousand", ["b"]),
     ("three times a day", ["tid"]),
     ("thrice", ["tri","ter"]),
     ("through", ["per"]),
     ("thus", ["sic","so"]),
     ("time", ["t","eon","sec","mo","age"]),
     ("times", ["by","x"]),
     ("tin", ["sn"]),
     ("tinker", ["sly"]),
     ("to the", ["aux","ala","au"]),
     ("today", ["ad"]),
     ("ton", ["t"]),
     ("tonne", ["t"]),
     ("torpedo boat", ["tb","mtb"]),
     ("tostis song", ["tata"]),
     ("tot", ["add"]),
     ("touching", ["re"]),
     ("track", ["y"]),
     ("tradesmen", ["tu"]),
     ("traffic signal", ["go","stop"]),
     ("trainee", ["l"]),
     ("training", ["pt","pe"]),
     ("trains", ["br"]),
     ("tramp", ["hobo"]),
     ("transaction", ["tr"]),
     ("transatlantic", ["us"]),
     ("translation", ["tr"]),
     ("transport", ["bus","cab","rly","ry","cart","br","tram","car"]),
     ("trap", ["u"]),
     ("traveller", ["rom","rep"]),
     ("tree", ["actor","yew","fir","ash"]),
     ("tree ring", ["mayo"]),
     ("trendy", ["in"]),
     ("tribe", ["dan","gad"]),
     ("trick", ["con"]),
     ("triple", ["tri","ter"]),
     ("tritium", ["t"]),
     ("triumphant cry", ["io"]),
     ("trivial sum", ["ip"]),
     ("troops", ["re"]),
     ("trouble", ["ail","ado"]),
     ("troy", ["t"]),
     ("tube", ["u"]),
     ("tuesday", ["t"]),
     ("tune", ["air"]),
     ("tungsten", ["w"]),
     ("turkey", ["tr"]),
     ("turn", ["u"]),
     ("twenty", ["k"]),
     ("twenty feet", ["rope"]),
     ("twenty five pounds", ["pony"]),
     ("twenty thousand", ["k"]),
     ("twenty five pounds", ["pony"]),
     ("twice", ["bis"]),
     ("twitching", ["tic"]),
     ("two", ["bi","ii","di","pr","bis"]),
     ("two hundred", ["h","cc"]),
     ("two hundred and fifty", ["k","e"]),
     ("two hundred and fifty thousand", ["e"]),
     ("two hundred thousand", ["h"]),
     ("tyneside", ["ne"]),
     ("tyro", ["l"]),
     ("u boat", ["sub"]),
     ("ulster", ["ni"]),
     ("un", ["an","i","a"]),
     ("uncle", ["pawnbroker","eme","sam"]),
     ("undergarment", ["bra"]),
     ("undersecretary", ["us"]),
     ("understood", ["ment"]),
     ("underworld", ["dis"]),
     ("undivided", ["one"]),
     ("unfashionable", ["out","square"]),
     ("unfavourable aspect", ["n"]),
     ("unidentified", ["nu"]),
     ("union", ["u"]),
     ("unionist", ["u"]),
     ("unit", ["i","a"]),
     ("united kingdom", ["uk"]),
     ("united nations", ["un"]),
     ("universal", ["u"]),
     ("universal set", ["e"]),
     ("university", ["u"]),
     ("university teacher", ["don"]),
     ("unknown", ["x","z","y"]),
     ("unknown number", ["n"]),
     ("unlimited number", ["n"]),
     ("unpaid", ["hon"]),
     ("unservicable", ["us"]),
     ("unwell", ["ill"]),
     ("upper class", ["u"]),
     ("uppish", ["u"]),
     ("upright", ["i","pi"]),
     ("upsilon", ["u"]),
     ("uranium", ["u"]),
     ("uruguay", ["uru","u"]),
     ("us", ["s"]),
     ("use", ["uu","us"]),
     ("used", ["sh"]),
     ("useless", ["us"]),
     ("utah", ["u"]),
     ("vacant", ["e"]),
     ("vanadium", ["v"]),
     ("various years", ["vy"]),
     ("Vatican", ["v"]),
     ("vee", ["v"]),
     ("velocity", ["v"]),
     ("verb", ["vb","v"]),
     ("verse", ["v"]),
     ("versus", ["v"]),
     ("very", ["tres","unco","v"]),
     ("very black", ["bb"]),
     ("very hard", ["hh"]),
     ("very large", ["os"]),
     ("very loud", ["ff"]),
     ("very quiet", ["pp"]),
     ("very softly", ["pp"]),
     ("very strong", ["ff"]),
     ("vessel", ["tin","can"]),
     ("vestment", ["alb"]),
     ("vicar", ["rev"]),
     ("victory", ["vj","v","ve"]),
     ("vide", ["v"]),
     ("violin string", ["a","e","g","d"]),
     ("violin strings", ["g","e"]),
     ("Virginia", ["va"]),
     ("viscount", ["vis"]),
     ("vitamin", ["h","k","bi","f","p","b","a","l","c","m","d","e","x"]),
     ("viz", ["sc"]),
     ("volt", ["v"]),
     ("volume", ["v","vol"]),
     ("volunteers", ["ta"]),
     ("vote", ["x"]),
     ("wall", ["mur"]),
     ("wander", ["err"]),
     ("warning", ["fore","cave"]),
     ("warrant officer", ["rsm"]),
     ("warship", ["sub"]),
     ("washington", ["dc"]),
     ("water", ["ea","aq"]),
     ("waterfall", ["rain"]),
     ("watt", ["w"]),
     ("way", ["rly","ry","rd","st","ave"]),
     ("way of working", ["mo"]),
     ("weak", ["w"]),
     ("wearing", ["in"]),
     ("wednesday", ["w"]),
     ("week", ["w"]),
     ("weight", ["g","oz","ton","gr","st","ct","wt","tonne"]),
     ("well", ["so"]),
     ("welsh", ["w"]),
     ("welsh riots", ["rebecca"]),
     ("west", ["w"]),
     ("west indies", ["wi"]),
     ("western", ["w"]),
     ("westminster", ["wi"]),
     ("whales", ["gam"]),
     ("what", ["que"]),
     ("when", ["as"]),
     ("who", ["qui"]),
     ("whole numbers", ["w"]),
     ("why", ["y"]),
     ("wicked sister", ["regan"]),
     ("wicket", ["w"]),
     ("width", ["w"]),
     ("wife", ["ux","rib","dutch","w"]),
     ("will", ["ill","to"]),
     ("william", ["w"]),
     ("win", ["v"]),
     ("wine", ["asti","port","tent"]),
     ("wings", ["ala"]),
     ("winner", ["ace"]),
     ("wise", ["ys","yy"]),
     ("witchcraft", ["obi"]),
     ("with", ["con"]),
     ("with a tenant", ["let"]),
     ("without", ["sin","sine"]),
     ("without a day fixed", ["sd"]),
     ("without children", ["sp"]),
     ("without date", ["sa"]),
     ("wizard place", ["oz"]),
     ("woman", ["f","her","w","eve","she"]),
     ("word processor", ["ear"]),
     ("work", ["opus","go","do","op"]),
     ("worker", ["ant","man","hand","bee"]),
     ("wreath", ["lei"]),
     ("writer", ["pen","elia","nib"]),
     ("writing", ["r","ms"]),
     ("wrong", ["sin"]),
     ("wrong sign", ["x"]),
     ("xi", ["x"]),
     ("Xmas", ["x"]),
     ("yard", ["y"]),
     ("year", ["a","y","yr"]),
     ("year of reign", ["ar"]),
     ("yearly meeting", ["agm"]),
     ("yellow", ["or"]),
     ("yen", ["y"]),
     ("yes", ["ja","oui","si","da","ay","aye"]),
     ("yew", ["u"]),
     ("yews", ["uu","us"]),
     ("you", ["u","ye"]),
     ("you and i", ["us","we"]),
     ("you and me", ["us","we"]),
     ("you are", ["ur"]),
     ("you queue", ["uq"]),
     ("you see", ["uc"]),
     ("you will, say", ["yule"]),
     ("young", ["y"]),
     ("young feller", ["washington"]),
     ("young sheep", ["teg"]),
     ("your", ["yr"]),
     ("yours truly", ["i"]),
     ("youth leaders", ["ys","wise"]),
     ("yttrium", ["y"]),
     ("Zaire", ["zr"]),
     ("Zambia", ["z"]),
     ("zed", ["z"]),
     ("zee", ["z"]),
     ("zero", ["z"]),
     ("zeta", ["z"])]


